insert into fs_origin_code_t (FS_ORIGIN_CD, OBJ_ID, VER_NBR, FS_SERVER_NM, FS_DATABASE_NM, FS_DATABASE_DESC, NEXT_CPTLAST_NBR, NEXT_NONCA_NBR, NEXT_CG_AGENCY_NBR, NEXT_CG_SUBCNR_NBR, NXT_DV_PAYEEID_NBR, NXT_FDOC_ATT_ID, AR_NEXT_CUST_NBR, FDOC_NEXT_ITEM_ID, ROW_ACTV_IND)
values ('46', '054EDFB3B24AC8D2E043814FD881C8D1', 1, 'KMM', 'KMM', 'KMM', null, null, '', '', null, null, null, null, 'Y');

insert into PUR_PO_CST_SRC_T (PO_CST_SRC_CD, OBJ_ID, VER_NBR, PO_CST_SRC_DESC, DOBJ_MAINT_CD_ACTV_IND, ITM_UNIT_PRC_UPR_VAR_PCT, ITM_UNIT_PRC_LWR_VAR_PCT)
values ('STOR', '636024D36C728EC6E0404F8189D80407', 1, 'MM STORES', 'Y', 0, 0);

insert into PUR_REQS_SRC_T (REQS_SRC_CD, OBJ_ID, VER_NBR, REQS_SRC_DESC, DOBJ_MAINT_CD_ACTV_IND)
values ('SROR', SYS_GUID(), 1, 'Requisition Source for Stores Reorder', 'Y');

