truncate table MM_ACTION_T_insert.sql
truncate table MM_ADDITIONAL_COST_TYPE_T_insert.sql
truncate table MM_ADDRESS_TYPE_T_insert.sql
truncate table MM_BATCH_CTRL.sql
truncate table MM_CATALOG_TYPE_T_insert.sql
truncate table MM_COST_CODE_T_insert.sql
truncate table MM_CYCLE_COUNT_T_insert.sql
truncate table MM_DELIVERY_REASON_T_insert.sql
truncate table MM_DISPOSITION_T_insert.sql
truncate table MM_DOT_HAZARDOUS_T_insert.sql
truncate table MM_DRIVER_MANIFEST_T_insert.sql
truncate table MM_EHS_CONTAINER_T_insert.sql
truncate table MM_EHS_HAZARDOUS_STATE_T_insert.sql
truncate table MM_EHS_HAZARDOUS_T_insert.sql
truncate table MM_HAZARDOUS_UN_T_insert.sql
truncate table MM_MARKUP_TYPE_T_insert.sql
truncate table MM_ORDER_STATUS_T_insert.sql
truncate table MM_ORDER_TYPE_T_insert.sql
truncate table MM_PACK_LIST_ANNOUNCEMENT_T_insert.sql
truncate table MM_PACK_STATUS_CODE_T_insert.sql
truncate table MM_PICK_STATUS_CODE_T_insert.sql
truncate table MM_RESTRICTED_ROUTE_CODE_T_insert.sql
truncate table MM_RETURN_STATUS_CODE_T_insert.sql
truncate table MM_RETURN_TYPE_T_insert.sql
truncate table MM_ROUTE_T_insert.sql
truncate table MM_STOCK_ATTRIBUTE_CODE_T_insert.sql
truncate table MM_STOCK_COST_T_insert.sql
truncate table MM_STOCK_TRANS_REASON_T_insert.sql
truncate table MM_STOCK_TYPE_T_insert.sql