insert into MM_ADDRESS_TYPE_T (ADDRESS_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)  
VALUES('01',sys_guid(),1,'BILL TO ADDRESS','Y',CURRENT_DATE);
insert into MM_ADDRESS_TYPE_T (ADDRESS_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)  
VALUES('02',sys_guid(),1,'SHIP TO ADDRESS','Y',CURRENT_DATE);
insert into MM_ADDRESS_TYPE_T (ADDRESS_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)  
VALUES('03',sys_guid(),1,'OTHER ADDRESS','Y',CURRENT_DATE);
insert into MM_ADDRESS_TYPE_T (ADDRESS_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)  
VALUES('04',sys_guid(),1,'PREVIOUS ADDRESS','Y',CURRENT_DATE);
