INSERT INTO mm_catalog_type_t (CATALOG_TYPE_CD,OBJ_ID,VER_NBR,NM,ACTV_IND,LAST_UPDATE_DT)
VALUES('1',SYS_GUID(),1,'WAREHOUSE','Y',CURRENT_DATE);
INSERT INTO mm_catalog_type_t (CATALOG_TYPE_CD,OBJ_ID,VER_NBR,NM,ACTV_IND,LAST_UPDATE_DT)
VALUES('2',SYS_GUID(),1,'HOSTED','Y',CURRENT_DATE);
INSERT INTO mm_catalog_type_t (CATALOG_TYPE_CD,OBJ_ID,VER_NBR,NM,ACTV_IND,LAST_UPDATE_DT)
VALUES('3',SYS_GUID(),1,'PUNCH OUT','Y',CURRENT_DATE);
