INSERT INTO MM_COST_CODE_T ( COST_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('01', SYS_GUID(), '1', 'STANDARD COST',  'Y', CURRENT_DATE ) 
;
INSERT INTO MM_COST_CODE_T ( COST_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('02', SYS_GUID(), '1', 'WEIGHTED AVERAGE',  'Y', CURRENT_DATE ) 
;
