INSERT INTO MM_DELIVERY_REASON_T ( DELIVERY_REASON_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('CLSD', SYS_GUID(), '1', 'DELIVERY POINT CLOSED', 'Y', CURRENT_DATE )
;
INSERT INTO MM_DELIVERY_REASON_T ( DELIVERY_REASON_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('DEST', SYS_GUID(), '1', 'IN ROUTE TO DESTINATION', 'Y', CURRENT_DATE )
;
INSERT INTO MM_DELIVERY_REASON_T ( DELIVERY_REASON_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('RFSD', SYS_GUID(), '1', 'REFUSED DELIVERY', 'Y', CURRENT_DATE )
;
INSERT INTO MM_DELIVERY_REASON_T ( DELIVERY_REASON_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('DLVD', SYS_GUID(), '1', 'DELIVERED', 'Y', CURRENT_DATE )
;