insert into MM_MARKUP_TYPE_T (MARKUP_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)
values ('01', SYS_GUID(), 1, 'ACCOUNT MARKUP', 'Y', sysdate);

insert into MM_MARKUP_TYPE_T (MARKUP_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)
values ('02', SYS_GUID(), 1, 'ORGANIZATION MARKUP', 'Y', sysdate);

insert into MM_MARKUP_TYPE_T (MARKUP_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)
values ('03', SYS_GUID(), 1, 'ACCOUNT + CATALOG ITEM MARKUP', 'Y', sysdate);

insert into MM_MARKUP_TYPE_T (MARKUP_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)
values ('04', SYS_GUID(), 1, 'CATALOG FIX MARKUP', 'Y', sysdate);

insert into MM_MARKUP_TYPE_T (MARKUP_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)
values ('05', SYS_GUID(), 1, 'PASS-THROUGH - NO MARKUP APPLIED', 'Y', sysdate);

insert into MM_MARKUP_TYPE_T (MARKUP_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)
values ('06', SYS_GUID(), 1, 'ITEM CATEGORY MARKUP', 'Y', sysdate);

insert into MM_MARKUP_TYPE_T (MARKUP_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)
values ('07', SYS_GUID(), 1, 'WAREHOUSE MARKUP', 'Y', sysdate);

insert into MM_MARKUP_TYPE_T (MARKUP_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)
values ('08', SYS_GUID(), 1, 'CASH SALE MARKUP', 'Y', sysdate);

insert into MM_MARKUP_TYPE_T (MARKUP_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)
values ('09', SYS_GUID(), 1, 'ITEM CATEGORY + CATALOG ITEM MARKUP', 'Y', sysdate);

insert into MM_MARKUP_TYPE_T (MARKUP_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)
values ('10', SYS_GUID(), 1, 'CASH SALE + CATALOG ITEM MARKUP', 'Y', sysdate);