insert into MM_ORDER_TYPE_T (ORDER_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)  
VALUES('WAREHS',sys_guid(),1,'WAREHOUSE ORDER','Y',CURRENT_DATE);
insert into MM_ORDER_TYPE_T (ORDER_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)  
VALUES('HOSTED',sys_guid(),1,'HOSTED SUPPLIER CATALOG ORDER','Y',CURRENT_DATE);
insert into MM_ORDER_TYPE_T (ORDER_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)  
VALUES('PUNCH',sys_guid(),1,'PUNCH OUT ORDER','Y',CURRENT_DATE);
insert into MM_ORDER_TYPE_T (ORDER_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)  
VALUES('STOCK',sys_guid(),1,'STOCKING ORDER FOR THE WAREHOUSE','Y',CURRENT_DATE);
insert into MM_ORDER_TYPE_T (ORDER_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)  
VALUES('RETURN',sys_guid(),1,'RETURN ORDER','Y',CURRENT_DATE);
