INSERT INTO MM_PACK_STATUS_CODE_T ( PACK_STATUS_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('PRTD', SYS_GUID(), '1', 'PACK LIST PRINTED', 'Y', CURRENT_DATE )
;
INSERT INTO MM_PACK_STATUS_CODE_T ( PACK_STATUS_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('INIT', SYS_GUID(), '1', 'PACK LIST INITIATED', 'Y', CURRENT_DATE )
;
INSERT INTO MM_PACK_STATUS_CODE_T ( PACK_STATUS_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('DLVD', SYS_GUID(), '1', 'PACK LIST DELIVERED', 'Y', CURRENT_DATE )
;
INSERT INTO MM_PACK_STATUS_CODE_T ( PACK_STATUS_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('PCKD', SYS_GUID(), '1', 'PACK LIST PACKED', 'Y', CURRENT_DATE )
;
INSERT INTO MM_PACK_STATUS_CODE_T ( PACK_STATUS_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('RDLV', SYS_GUID(), '1', 'PACK LIST NEEDS REDELIVERY', 'Y', CURRENT_DATE )
;
INSERT INTO MM_PACK_STATUS_CODE_T ( PACK_STATUS_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('CLSD', SYS_GUID(), '1', 'PACK LIST CLOSED', 'Y', CURRENT_DATE )
;
INSERT INTO MM_PACK_STATUS_CODE_T ( PACK_STATUS_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('CNCL', SYS_GUID(), '1', 'PACK LIST CANCELED', 'Y', CURRENT_DATE )
;