insert into MM_RESTRICTED_ROUTE_CODE_T (RESTRICTED_ROUTE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)  
VALUES('HH',sys_guid(),1,'HAZARDOUS MATERIEL','Y',CURRENT_DATE);
insert into MM_RESTRICTED_ROUTE_CODE_T (RESTRICTED_ROUTE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)  
VALUES('BR',sys_guid(),1,'BRIDGE RESTRICTIONS','Y',CURRENT_DATE);
insert into MM_RESTRICTED_ROUTE_CODE_T (RESTRICTED_ROUTE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)  
VALUES('NR',sys_guid(),1,'NARROW ROAD','Y',CURRENT_DATE);
