INSERT INTO MM_RETURN_STATUS_CODE_T (RETURN_STATUS_CD, OBJ_ID, VER_NBR, NM, CUSTOMER_VENDOR_RETURN_IND, ACTV_IND, LAST_UPDATE_DT)
VALUES('02',SYS_GUID(),1,'WRONG ITEM (NOT CHECKED-IN)','V','Y',CURRENT_DATE);
INSERT INTO MM_RETURN_STATUS_CODE_T (RETURN_STATUS_CD, OBJ_ID, VER_NBR, NM, CUSTOMER_VENDOR_RETURN_IND, ACTV_IND, LAST_UPDATE_DT)
VALUES('03',SYS_GUID(),1,'DAMAGED (CHECKED-IN)','V','Y',CURRENT_DATE);
INSERT INTO MM_RETURN_STATUS_CODE_T (RETURN_STATUS_CD, OBJ_ID, VER_NBR, NM, CUSTOMER_VENDOR_RETURN_IND, ACTV_IND, LAST_UPDATE_DT)
VALUES('04',SYS_GUID(),1,'DAMAGED (NOT CHECKED-IN)','V','Y',CURRENT_DATE);
INSERT INTO MM_RETURN_STATUS_CODE_T (RETURN_STATUS_CD, OBJ_ID, VER_NBR, NM, CUSTOMER_VENDOR_RETURN_IND, ACTV_IND, LAST_UPDATE_DT)
VALUES('05',SYS_GUID(),1,'OVER SHIPMENT (CHECKED-IN)','V','Y',CURRENT_DATE);
INSERT INTO MM_RETURN_STATUS_CODE_T (RETURN_STATUS_CD, OBJ_ID, VER_NBR, NM, CUSTOMER_VENDOR_RETURN_IND, ACTV_IND, LAST_UPDATE_DT)
VALUES('06',SYS_GUID(),1,'OVER SHIPMENT (NOT CHECKED-IN)','V','Y',CURRENT_DATE);
INSERT INTO MM_RETURN_STATUS_CODE_T (RETURN_STATUS_CD, OBJ_ID, VER_NBR, NM, CUSTOMER_VENDOR_RETURN_IND, ACTV_IND, LAST_UPDATE_DT)
VALUES('09',SYS_GUID(),1,'RECEIPT CORRECTION','V','Y',CURRENT_DATE);
INSERT INTO MM_RETURN_STATUS_CODE_T (RETURN_STATUS_CD, OBJ_ID, VER_NBR, NM, CUSTOMER_VENDOR_RETURN_IND, ACTV_IND, LAST_UPDATE_DT)
VALUES('01',SYS_GUID(),1,'WRONG ITEM (CHECKED-IN)','V','Y',CURRENT_DATE);
INSERT INTO MM_RETURN_STATUS_CODE_T (RETURN_STATUS_CD, OBJ_ID, VER_NBR, NM, CUSTOMER_VENDOR_RETURN_IND, ACTV_IND, LAST_UPDATE_DT)
VALUES('07',SYS_GUID(),1,'DON''T NEED (CHECKED-IN)','V','Y',CURRENT_DATE);
INSERT INTO MM_RETURN_STATUS_CODE_T (RETURN_STATUS_CD, OBJ_ID, VER_NBR, NM, CUSTOMER_VENDOR_RETURN_IND, ACTV_IND, LAST_UPDATE_DT)
VALUES('08',SYS_GUID(),1,'DON''T NEED (NOT CHECKED-IN)','V','Y',CURRENT_DATE);
INSERT INTO MM_RETURN_STATUS_CODE_T (RETURN_STATUS_CD, OBJ_ID, VER_NBR, NM, CUSTOMER_VENDOR_RETURN_IND, ACTV_IND, LAST_UPDATE_DT)
VALUES('10',SYS_GUID(),1,'MANUFACTURER RECALL (CHECKED-IN)','V','Y',CURRENT_DATE);
INSERT INTO MM_RETURN_STATUS_CODE_T (RETURN_STATUS_CD, OBJ_ID, VER_NBR, NM, CUSTOMER_VENDOR_RETURN_IND, ACTV_IND, LAST_UPDATE_DT)
VALUES('11',SYS_GUID(),1,'MANUFACTURER RECALL (NOT CHECKED-IN)','V','Y',CURRENT_DATE);
INSERT INTO MM_RETURN_STATUS_CODE_T (RETURN_STATUS_CD, OBJ_ID, VER_NBR, NM, CUSTOMER_VENDOR_RETURN_IND, ACTV_IND, LAST_UPDATE_DT)
VALUES('12',SYS_GUID(),1,'PAST EXPIRATION DATE (CHECKED-IN)','V','Y',CURRENT_DATE);
INSERT INTO MM_RETURN_STATUS_CODE_T (RETURN_STATUS_CD, OBJ_ID, VER_NBR, NM, CUSTOMER_VENDOR_RETURN_IND, ACTV_IND, LAST_UPDATE_DT)
VALUES('13',SYS_GUID(),1,'PAST EXPIRATION DATE (NOT CHECKED-IN)','V','Y',CURRENT_DATE);
INSERT INTO MM_RETURN_STATUS_CODE_T (RETURN_STATUS_CD, OBJ_ID, VER_NBR, NM, CUSTOMER_VENDOR_RETURN_IND, ACTV_IND, LAST_UPDATE_DT)
VALUES('14',SYS_GUID(),1,'LOSS PREVENTION (CHECKED-IN)','V','Y',CURRENT_DATE);
INSERT INTO MM_RETURN_STATUS_CODE_T (RETURN_STATUS_CD, OBJ_ID, VER_NBR, NM, CUSTOMER_VENDOR_RETURN_IND, ACTV_IND, LAST_UPDATE_DT)
VALUES('15',SYS_GUID(),1,'LOSS PREVENTION  (NOT CHECKED-IN)','V','Y',CURRENT_DATE);
INSERT INTO MM_RETURN_STATUS_CODE_T (RETURN_STATUS_CD, OBJ_ID, VER_NBR, NM, CUSTOMER_VENDOR_RETURN_IND, ACTV_IND, LAST_UPDATE_DT)
VALUES('16',SYS_GUID(),1,'UNACCEPTABLE SUBSTITUTE (NOT CHECKED-IN)','V','Y',CURRENT_DATE);
INSERT INTO MM_RETURN_STATUS_CODE_T (RETURN_STATUS_CD, OBJ_ID, VER_NBR, NM, CUSTOMER_VENDOR_RETURN_IND, ACTV_IND, LAST_UPDATE_DT)
VALUES('17',SYS_GUID(),1,'UNACCEPTABLE SUBSTITUTE (CHECKED-IN)','V','Y',CURRENT_DATE);
INSERT INTO MM_RETURN_STATUS_CODE_T (RETURN_STATUS_CD, OBJ_ID, VER_NBR, NM, CUSTOMER_VENDOR_RETURN_IND, ACTV_IND, LAST_UPDATE_DT)
VALUES('18',SYS_GUID(),1,'DEFECTIVE/EMPTY (CHECKED-IN)','V','Y',CURRENT_DATE);

insert into mm_return_status_code_t (return_status_cd, obj_id, ver_nbr, nm, customer_vendor_return_ind, actv_ind, last_update_dt)
values ('O', sys_guid(),1,'OPEN','V','Y',CURRENT_DATE);
insert into mm_return_status_code_t (return_status_cd, obj_id, ver_nbr, nm, customer_vendor_return_ind, actv_ind, last_update_dt)
values ('C', sys_guid(),1,'CLOSED','V','Y',CURRENT_DATE);
insert into mm_return_status_code_t (return_status_cd, obj_id, ver_nbr, nm, customer_vendor_return_ind, actv_ind, last_update_dt)
values ('X', sys_guid(),1,'CANCELED','V','Y',CURRENT_DATE);
insert into mm_return_status_code_t (return_status_cd, obj_id, ver_nbr, nm, customer_vendor_return_ind, actv_ind, last_update_dt)
values ('T', sys_guid(),1,'COMPLETE','V','Y',CURRENT_DATE);
