INSERT INTO  MM_RETURN_TYPE_T (RETURN_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT) 
VALUES ('CR', SYS_GUID(),1,'CUSTOMER ORDER RETURN','Y',CURRENT_DATE)
/
INSERT INTO  MM_RETURN_TYPE_T (RETURN_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT) 
VALUES ('VR', SYS_GUID(),1,'VENDOR PURCHASE ORDER RETURN','Y',CURRENT_DATE)
/
