insert into MM_STOCK_ATTRIBUTE_CODE_T (STOCK_ATTRIBUTE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)  
VALUES('01',sys_guid(),1,'FEDERAL TRACKING','Y',CURRENT_DATE);
insert into MM_STOCK_ATTRIBUTE_CODE_T (STOCK_ATTRIBUTE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)  
VALUES('02',sys_guid(),1,'STATE TRACKING','Y',CURRENT_DATE);
insert into MM_STOCK_ATTRIBUTE_CODE_T (STOCK_ATTRIBUTE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)  
VALUES('03',sys_guid(),1,'PANDEMIC STOCK','Y',CURRENT_DATE);
