insert into MM_STOCK_TYPE_T (STOCK_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)  
VALUES('01',sys_guid(),1,'STOCK','Y',CURRENT_DATE);
insert into MM_STOCK_TYPE_T (STOCK_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)  
VALUES('02',sys_guid(),1,'RENTAL','Y',CURRENT_DATE);
insert into MM_STOCK_TYPE_T (STOCK_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)  
VALUES('03',sys_guid(),1,'CYLINDER','Y',CURRENT_DATE);
insert into MM_STOCK_TYPE_T (STOCK_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)  
VALUES('04',sys_guid(),1,'STAMP','Y',CURRENT_DATE);
insert into MM_STOCK_TYPE_T (STOCK_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT)  
VALUES('05',sys_guid(),1,'NONSTOCKED','Y',CURRENT_DATE);
