INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('REPRNTED', SYS_GUID(), '1', 'REPRINTED STOCK FOR COUNT', 'N', NULL, 'Y', CURRENT_DATE ) 
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('COUNT', SYS_GUID(), '1', 'REQUEST TO COUNT STOCK', 'I', 'SHRO', 'Y', CURRENT_DATE ) 
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('SALE', SYS_GUID(), '1', 'STOCK SOLD', 'D', 'SHRO', 'Y', CURRENT_DATE ) 
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('UIOLD', SYS_GUID(), '1', 'UNIT OF ISSUE CHANGE - OLD VALUE', 'D', 'SHRO', 'Y', CURRENT_DATE ) 
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('UINEW', SYS_GUID(), '1', 'UNIT OF ISSUE CHANGE - NEW VALUE', 'I', 'SHRO', 'Y', CURRENT_DATE ) 
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('UIREMAIN', SYS_GUID(), '1', 'UNIT OF ISSUE CHANGE - RESIDUAL VALUE', 'D', 'SHRO', 'Y', CURRENT_DATE ) 
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('AVGCOST', SYS_GUID(), '1', 'WEIGHTED AVERAGE UNIT COST CHANGE', NULL, 'SHRO', 'Y', CURRENT_DATE ) 
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('TRANS_IN', SYS_GUID(), '1', 'TRANSFER STOCK IN', 'I', 'SHRO', 'Y', CURRENT_DATE )
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('TRANSOUT', SYS_GUID(), '1', 'TRANSFER STOCK OUT', 'D', 'SHRO', 'Y', CURRENT_DATE )
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('INVNTORY', SYS_GUID(), '1', 'PHYSICAL INVENTORY', 'N', 'SHRO', 'Y', CURRENT_DATE ) 
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('TOLERANC', SYS_GUID(), '1', 'WITHIN TOLERANCE', 'I', 'SHRO', 'Y', CURRENT_DATE ) 
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('CST_RTRN', SYS_GUID(), '1', 'CUSTOMER RETURN', 'I', 'SHRO', 'Y', CURRENT_DATE ) 
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('VND_RTRN', SYS_GUID(), '1', 'VENDOR RETURN', 'D', 'SHRO', 'Y', CURRENT_DATE ) 
;
