INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('BA',SYS_GUID(),1,'BALL','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('BD',SYS_GUID(),1,'BUNDLE','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('BE',SYS_GUID(),1,'BALE','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('BF',SYS_GUID(),1,'BOARD FOOT','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('BG',SYS_GUID(),1,'BAG','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('BK',SYS_GUID(),1,'BOOK','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('BN',SYS_GUID(),1,'BAND','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('BO',SYS_GUID(),1,'BOLT','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('BR',SYS_GUID(),1,'BAR','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('BT',SYS_GUID(),1,'BOTTLE','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('BX',SYS_GUID(),1,'BOX','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('CB',SYS_GUID(),1,'CARBOY','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('CE',SYS_GUID(),1,'CONE','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('CF',SYS_GUID(),1,'CUBIC FOOT','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('CL',SYS_GUID(),1,'COIL','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('CN',SYS_GUID(),1,'CAN','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('CS',SYS_GUID(),1,'CASE','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('CT',SYS_GUID(),1,'CARTON','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('CY',SYS_GUID(),1,'CYLINDER','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('DR',SYS_GUID(),1,'DRUM','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('DZ',SYS_GUID(),1,'DOZEN','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('EA',SYS_GUID(),1,'EACH','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('FT',SYS_GUID(),1,'FOOT','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('GL',SYS_GUID(),1,'GALLON','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('HD',SYS_GUID(),1,'HUNDRED','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('HK',SYS_GUID(),1,'HANK','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('JG',SYS_GUID(),1,'JAG','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('JR',SYS_GUID(),1,'JAR','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('JU',SYS_GUID(),1,'JUG','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('LF',SYS_GUID(),1,'LINEAR FOOT','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('LG',SYS_GUID(),1,'LENGTH','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('OZ',SYS_GUID(),1,'OUNCE','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('PC',SYS_GUID(),1,'PIECE','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('PD',SYS_GUID(),1,'PAD','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('PG',SYS_GUID(),1,'PACKAGE','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('PK',SYS_GUID(),1,'PACK','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('PL',SYS_GUID(),1,'PAIL','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('PR',SYS_GUID(),1,'PAIR','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('PT',SYS_GUID(),1,'PINT','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('QR',SYS_GUID(),1,'QUIRE','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('QT',SYS_GUID(),1,'QUART','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('RE',SYS_GUID(),1,'REEL','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('RK',SYS_GUID(),1,'RACK','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('RO',SYS_GUID(),1,'ROLL','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('RM',SYS_GUID(),1,'REAM','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('SE',SYS_GUID(),1,'SET','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('SF',SYS_GUID(),1,'SQUARE FOOT','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('SH',SYS_GUID(),1,'SHEET','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('SL',SYS_GUID(),1,'SPOOL','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('SV',SYS_GUID(),1,'SLEEVE','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('TR',SYS_GUID(),1,'TRAY','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('TU',SYS_GUID(),1,'TUBE','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('VI',SYS_GUID(),1,'VIAL','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('YD',SYS_GUID(),1,'YARD','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('CD',SYS_GUID(),1,'CARD','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('LB',SYS_GUID(),1,'POUND','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('QHR',SYS_GUID(),1,'QUARTER HOUR','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('ST',SYS_GUID(),1,'SET (NON STOREHOUSE U/I)','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('C',SYS_GUID(),1,'HUNDRED (NON STOREHOUSE U/I)','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('CA',SYS_GUID(),1,'CASE (NON STOREHOUSE U/I)','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('GR',SYS_GUID(),1,'GROSS (NON STOREHOUSE U/I)','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('KT',SYS_GUID(),1,'KIT (NON STOREHOUSE U/I)','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('RL',SYS_GUID(),1,'ROLL (NON STOREHOUSE U/I)','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('TB',SYS_GUID(),1,'TUBE (NON STOREHOUSE U/I)','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('PA',SYS_GUID(),1,'PALLET (NON STOREHOUSE UI)','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('CO',SYS_GUID(),1,'CUSTOMER-OWNED CYLINDER','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('M',SYS_GUID(),1,'THOUSAND (NON STOREHOUSE UI)','Y',CURRENT_DATE);
INSERT INTO MM_UNIT_OF_ISSUE_T (UNIT_OF_ISSUE_CD, OBJ_ID, VER_NBR, UNIT_OF_ISSUE_DESC, ACTV_IND, LAST_UPDATE_DT)
VALUES('DS',SYS_GUID(),1,'DISPLAY','Y',CURRENT_DATE);




