INSERT INTO MM_WAREHOUSE_OBJECT_TYPE_T ( OBJECT_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('OBSO', SYS_GUID(), '1', 'OBSOLESCENCE OBJECT CODE', 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_OBJECT_TYPE_T ( OBJECT_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('SHRO', SYS_GUID(), '1', 'SHRINKAGE OBJECT CODE', 'Y', CURRENT_DATE )
;
