INSERT INTO MM_WORKSHEET_STATUS_T ( WORKSHEET_STATUS_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('INIT', SYS_GUID(), '1', 'WORKSHEET INITIATED', 'Y', CURRENT_DATE )
;
INSERT INTO MM_WORKSHEET_STATUS_T ( WORKSHEET_STATUS_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('PRTD', SYS_GUID(), '1', 'WORKSHEET PRINTED', 'Y', CURRENT_DATE )
;
INSERT INTO MM_WORKSHEET_STATUS_T ( WORKSHEET_STATUS_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('ENTR', SYS_GUID(), '1', 'WORKSHEET ENTERED', 'Y', CURRENT_DATE )
;
INSERT INTO MM_WORKSHEET_STATUS_T ( WORKSHEET_STATUS_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('CLSD', SYS_GUID(), '1', 'WORKSHEET CLOSED', 'Y', CURRENT_DATE )
;
INSERT INTO MM_WORKSHEET_STATUS_T ( WORKSHEET_STATUS_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('CNCL', SYS_GUID(), '1', 'WORKSHEET CANCELED', 'Y', CURRENT_DATE )
;
INSERT INTO MM_WORKSHEET_STATUS_T ( WORKSHEET_STATUS_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('RPTD', SYS_GUID(), '1', 'WORKSHEET REPRINTED', 'Y', CURRENT_DATE )
;