package org.kuali.ext.mm.businessobject;

// Generated Apr 1, 2009 12:28:16 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cycle generated by hbm2java
 */
@Entity
@Table(name = "MM_ACTION_T")
public class ActionCode extends MMPersistableBusinessObjectBase implements
		java.io.Serializable {

	/**
     *
     */
    private static final long serialVersionUID = 1108950592858302895L;


    @Id
	@Column(name = "ACTION_CD", unique = true, nullable = false, length = 8)
	private String actionCodeValue;


    @Column(name = "NM", length = 80)
	private String actionName;


	public ActionCode() {
	}

    public String getActionCodeValue() {
        return actionCodeValue;
    }


    public void setActionCodeValue(String actionCodeValue) {
        this.actionCodeValue = actionCodeValue;
    }


    public String getActionName() {
        return actionName;
    }


    public void setActionName(String actionName) {
        this.actionName = actionName;
    }


}
