package org.kuali.ext.mm.businessobject;

// Generated May 11, 2009 11:03:40 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AdditionalCostType generated by hbm2java
 */
@Entity
@Table(name = "MM_ADDITIONAL_COST_TYPE_T")
public class AdditionalCostType extends MMPersistableBusinessObjectBase {

	/**
     *
     */
    private static final long serialVersionUID = 8975932116595186066L;

    @Id
	@Column(name = "ADDITIONAL_COST_TYPE_CD", unique = true, nullable = false, length = 12)
	private String additionalCostTypeCode;

	@Column(name = "NM", length = 45)
	private String additionalCostTypeName;

	public AdditionalCostType() {
	}

	public String getAdditionalCostTypeCode() {
		return this.additionalCostTypeCode;
	}

	public void setAdditionalCostTypeCode(String additionalCostTypeCd) {
		this.additionalCostTypeCode = additionalCostTypeCd;
	}

	public String getAdditionalCostTypeLookable(){
	    return this.additionalCostTypeCode;
	}

    public String setAdditionalCostTypeLookable(String additionalCostTypeCode){
        return this.additionalCostTypeCode = additionalCostTypeCode;
    }

	public String getAdditionalCostTypeName() {
		return this.additionalCostTypeName;
	}

	public void setAdditionalCostTypeName(String additionalCostTypeName) {
		this.additionalCostTypeName = additionalCostTypeName;
	}

}
