package org.kuali.ext.mm.businessobject;

// Generated Apr 16, 2009 10:01:00 AM by Hibernate Tools 3.2.4.GA

import org.kuali.ext.mm.integration.vnd.businessobject.FinancialVendorContract;
import org.kuali.rice.core.api.util.type.KualiDecimal;

import javax.persistence.*;
import java.sql.Date;

/**
 * Agreement generated by hbm2java
 */
@Entity
@Table(name = "MM_AGREEMENT_T")
public class Agreement extends MMPersistableBusinessObjectBase implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1096058907336032705L;

    @Temporal(TemporalType.DATE)
    @Column(name = "AGREEMENT_BEGIN_DT", nullable = false, length = 7)
    private Date agreementBeginDt;

    @Temporal(TemporalType.DATE)
    @Column(name = "AGREEMENT_END_DT", nullable = false, length = 7)
    private Date agreementEndDt;

    @Column(name = "AGREEMENT_LAG_DAYS", precision = 8, scale = 0)
    private Integer agreementLagDays;

    @Id
    @Column(name = "AGREEMENT_NBR", unique = true, nullable = false, precision = 9, scale = 0)
    private String agreementNbr;

    @Column(name = "AGREEMENT_USED_AMT", nullable = false)
    private KualiDecimal agreementUsedAmt;

    @Column(name = "B2B_IND", nullable = false, length = 1)
    private boolean b2bInd;

    @Column(name = "E_INVOICE_IND", nullable = false, length = 1)
    private boolean electronicInvoiceInd;

    private FinancialVendorContract financialVendorContract;

    @Column(name = "GHOST_CARD_IND", nullable = false, length = 1)
    private boolean ghostCardInd;


    @Column(name = "NOPRINT_IND", nullable = false, length = 1)
    private boolean noPrintInd;

    @Column(name = "PO_ID", nullable = false, precision = 9, scale = 0)
    private Integer poId;

    @Column(name = "PO_TOTAL_LIMIT", nullable = false)
    private KualiDecimal poTotalLimit;

    @Column(name = "VNDR_CONTR_NM", nullable = false, length = 1)
    private String vendorContractName;
    @Column(name = "VENDOR_NM", nullable = false, length = 45)
    private String vendorNm;
    @Column(name = "VNDR_CONTR_GNRTD_ID", nullable = false, precision = 10, scale = 0)
    private Integer vndrContrGnrtdId;

    @Column(name = "VNDR_DTL_ASND_ID", nullable = false, precision = 10, scale = 0)
    private Integer vndrDetailAsgnId;

    @Column(name = "VNDR_HDR_GNRTD_ID", nullable = false, precision = 10, scale = 0)
    private Integer vndrHeaderGnrtdId;
    
    public Agreement() {
    }

    public Date getAgreementBeginDt() {
        return this.agreementBeginDt;
    }

    public Date getAgreementEndDt() {
        return this.agreementEndDt;
    }

    public Integer getAgreementLagDays() {
        return this.agreementLagDays;
    }

    public String getAgreementNbr() {
        return this.agreementNbr;
    }

    public KualiDecimal getAgreementUsedAmt() {
        return this.agreementUsedAmt;
    }

    /**
     * Gets the financialVendorContract property
     * 
     * @return Returns the financialVendorContract
     */
    public FinancialVendorContract getFinancialVendorContract() {
        return this.financialVendorContract;
    }

    public Integer getPoId() {
        return this.poId;
    }

    public KualiDecimal getPoTotalLimit() {
        return this.poTotalLimit;
    }

    /**
     * Gets the vendorContractName property
     * 
     * @return Returns the vendorContractName
     */
    public String getVendorContractName() {
        return this.vendorContractName;
    }

    public String getVendorNm() {
        return this.vendorNm;
    }

    public Integer getVndrContrGnrtdId() {
        return this.vndrContrGnrtdId;
    }

    /**
     * Gets the vndrDetailAsgnId property
     * 
     * @return Returns the vndrDetailAsgnId
     */
    public Integer getVndrDetailAsgnId() {
        return this.vndrDetailAsgnId;
    }

    /**
     * Gets the vndrHeaderGnrtdId property
     * 
     * @return Returns the vndrHeaderGnrtdId
     */
    public Integer getVndrHeaderGnrtdId() {
        return this.vndrHeaderGnrtdId;
    }


    /**
     * Gets the b2bInd property
     * 
     * @return Returns the b2bInd
     */
    public boolean isB2bInd() {
        return this.b2bInd;
    }

    /**
     * Gets the eInvoiceInd property
     * 
     * @return Returns the eInvoiceInd
     */
    public boolean isElectronicInvoiceInd() {
        return this.electronicInvoiceInd;
    }

    /**
     * Gets the ghostCardInd property
     * 
     * @return Returns the ghostCardInd
     */
    public boolean isGhostCardInd() {
        return this.ghostCardInd;
    }

    /**
     * Gets the noPrintInd property
     * 
     * @return Returns the noPrintInd
     */
    public boolean isNoPrintInd() {
        return this.noPrintInd;
    }

    public void setAgreementBeginDt(Date agreementBeginDt) {
        this.agreementBeginDt = agreementBeginDt;
    }

    public void setAgreementEndDt(Date agreementEndDt) {
        this.agreementEndDt = agreementEndDt;
    }

    public void setAgreementLagDays(Integer agreementLagDays) {
        this.agreementLagDays = agreementLagDays;
    }

    public void setAgreementNbr(String agreementNbr) {
        this.agreementNbr = agreementNbr;
    }

    public void setAgreementUsedAmt(KualiDecimal agreementUsedAmt) {
        this.agreementUsedAmt = agreementUsedAmt;
    }

    /**
     * Sets the b2bInd property value
     * 
     * @param ind The b2bInd to set
     */
    public void setB2bInd(boolean ind) {
        this.b2bInd = ind;
    }

    /**
     * Sets the eInvoiceInd property value
     * 
     * @param invoiceInd The eInvoiceInd to set
     */
    public void setElectronicInvoiceInd(boolean invoiceInd) {
        this.electronicInvoiceInd = invoiceInd;
    }

    /**
     * Sets the financialVendorContract property value
     * 
     * @param financialVendorContract The financialVendorContract to set
     */
    public void setFinancialVendorContract(FinancialVendorContract financialVendorContract) {
        this.financialVendorContract = financialVendorContract;
    }


    /**
     * Sets the ghostCardInd property value
     * 
     * @param ghostCardInd The ghostCardInd to set
     */
    public void setGhostCardInd(boolean ghostCardInd) {
        this.ghostCardInd = ghostCardInd;
    }

    /**
     * Sets the noPrintInd property value
     * 
     * @param noPrintInd The noPrintInd to set
     */
    public void setNoPrintInd(boolean noPrintInd) {
        this.noPrintInd = noPrintInd;
    }

    public void setPoId(Integer poId) {
        this.poId = poId;
    }

    public void setPoTotalLimit(KualiDecimal poTotalLimit) {
        this.poTotalLimit = poTotalLimit;
    }

    /**
     * Sets the vendorContractName property value
     * 
     * @param vendorContractName The vendorContractName to set
     */
    public void setVendorContractName(String vendorContractName) {
        this.vendorContractName = vendorContractName;
    }

    public void setVendorNm(String vendorNm) {
        this.vendorNm = vendorNm;
    }

    public void setVndrContrGnrtdId(Integer vndrContrGnrtdId) {
        this.vndrContrGnrtdId = vndrContrGnrtdId;
    }

    /**
     * Sets the vndrDetailAsgnId property value
     * 
     * @param vndrDetailAsgnId The vndrDetailAsgnId to set
     */
    public void setVndrDetailAsgnId(Integer vndrDetailAsgnId) {
        this.vndrDetailAsgnId = vndrDetailAsgnId;
    }

    /**
     * Sets the vndrHeaderGnrtdId property value
     * 
     * @param vndrHeaderGnrtdId The vndrHeaderGnrtdId to set
     */
    public void setVndrHeaderGnrtdId(Integer vndrHeaderGnrtdId) {
        this.vndrHeaderGnrtdId = vndrHeaderGnrtdId;
    }

    @Override
    public String toString() {
        return "Agreement [agreementBeginDt=" + this.agreementBeginDt + ", agreementEndDt="
                + this.agreementEndDt + ", agreementLagDays=" + this.agreementLagDays
                + ", agreementNbr=" + this.agreementNbr + ", agreementUsedAmt="
                + this.agreementUsedAmt + ", b2bInd=" + this.b2bInd + ", ghostCardInd="
                + this.ghostCardInd + ", poId=" + this.poId + ", poTotalLimit=" + this.poTotalLimit
                + ", vendorNm=" + this.vendorNm + ", vndrContrGnrtdId=" + this.vndrContrGnrtdId
                + "]";
    }


}
