package org.kuali.ext.mm.businessobject;

// Generated Jul 13, 2009 9:05:12 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.ArrayList;
import java.util.List;

/**
 * BackOrder generated by hbm2java
 */
@Entity
@Table(name = "MM_BACK_ORDER_T")
public class BackOrder extends StoresPersistableBusinessObject {

	/**
     *
     */
    private static final long serialVersionUID = 8649848839724957984L;

	private String backOrderId;

	private PickListLine fromPickListLine;

	private Integer backOrderStockQty;
	
	private Stock stock;

	private boolean filled;
	
	private boolean canceled;
	
	private String stockId;
	
	private String fromPickListLineId;
	
	private List<PickListLine> toPickListLines = new ArrayList<PickListLine>();
	
   @Transient
    private String actionCode;

	public BackOrder() {
	}

	public String getBackOrderId() {
		return this.backOrderId;
	}

	public void setBackOrderId(String backOrderId) {
		this.backOrderId = backOrderId;
	}

	public Integer getBackOrderStockQty() {
		return this.backOrderStockQty;
	}

	public void setBackOrderStockQty(Integer backOrderStockQty) {
		this.backOrderStockQty = backOrderStockQty;
	}

	public PickListLine getFromPickListLine() {
		return fromPickListLine;
	}

	public void setFromPickListLine(PickListLine fromPickListLine) {
		this.fromPickListLine = fromPickListLine;
	}

	public String getFromPickListLineId() {
		return fromPickListLineId;
	}

	public void setFromPickListLineId(String fromPickListLineId) {
		this.fromPickListLineId = fromPickListLineId;
	}

	public Stock getStock() {
        return this.stock;
    }

    public void setStock(Stock stock) {
        this.stock = stock;
    }

    public boolean isFilled() {
        return this.filled;
    }

    public void setFilled(boolean filled) {
        this.filled = filled;
    }

    public void setCanceled(boolean canceled) {
        this.canceled = canceled;
    }

    public boolean isCanceled() {
        return canceled;
    }

    public String getStockId() {
        return this.stockId;
    }

    public void setStockId(String stockId) {
        this.stockId = stockId;
    }

    public List<PickListLine> getToPickListLines() {
        return this.toPickListLines;
    }

    public void setToPickListLines(List<PickListLine> toPickListLines) {
        this.toPickListLines = toPickListLines;
    }

    public void setActionCode(String actionCode) {
        this.actionCode = actionCode;
    }

    public String getActionCode() {
        return actionCode;
    }
    
    @Override
    public List buildListOfDeletionAwareLists() {
        List buildListOfDeletionAwareLists = super.buildListOfDeletionAwareLists();
        buildListOfDeletionAwareLists.add(getToPickListLines());
        return buildListOfDeletionAwareLists;
    }


}
