package org.kuali.ext.mm.businessobject;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CatalogImage generated by hbm2java
 */
@Entity
@Table(name = "MM_CATALOG_IMAGE_T")
public class CatalogImage extends MMPersistableBusinessObjectBase implements
		java.io.Serializable {

	private static final long serialVersionUID = 2879783731543814648L;

	@Id
	@Column(name = "CATALOG_IMAGE_ID", unique=true, nullable = false, precision = 8, scale = 0)
	private Integer catalogImageId;

	@Column(name = "CATALOG_IMAGE_NM", nullable = false, length = 12)
	private String catalogImageName;

	@Column(name = "CATALOG_IMAGE_URL", nullable = false, length = 60)
	private String catalogImageUrl;




	public Integer getCatalogImageId() {
		return catalogImageId;
	}




	public void setCatalogImageId(Integer catalogImageId) {
		this.catalogImageId = catalogImageId;
	}




	public String getCatalogImageName() {
		return catalogImageName;
	}




	public void setCatalogImageName(String catalogImageName) {
		this.catalogImageName = catalogImageName;
	}




	public String getCatalogImageUrl() {
		return catalogImageUrl;
	}




	public void setCatalogImageUrl(String catalogImageUrl) {
		this.catalogImageUrl = catalogImageUrl;
	}


	public String getCatalogImagePath() {
        if (this.catalogImageUrl != null && this.catalogImageUrl.toLowerCase().startsWith("http")) {
            return this.catalogImageUrl;
        }
        else if (this.catalogImageUrl != null) {
            return "item.do?methodToCall=streamImage&imagePath=" + this.catalogImageUrl;
        }

        return "";
    }


}
