package org.kuali.ext.mm.businessobject;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Catalog generated by hbm2java
 */
@Entity
@Table(name = "MM_CATALOG_TYPE_T")
public class CatalogType extends MMPersistableBusinessObjectBase implements
		java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "CATALOG_TYPE_CD", unique = true, nullable = false, length = 1)
	private String 	catalogTypeCd;

	@Column(name = "NM", length = 45)
	private String 	catalogTypeName;

	public String getCatalogTypeCd() {
		return catalogTypeCd;
	}

	public void setCatalogTypeCd(String catalogTypeCd) {
		this.catalogTypeCd = catalogTypeCd;
	}

	public String getCatalogTypeName() {
		return catalogTypeName;
	}

	public void setCatalogTypeName(String catalogTypeName) {
		this.catalogTypeName = catalogTypeName;
	}

}
