package org.kuali.ext.mm.businessobject;

// Generated May 11, 2009 11:03:40 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.*;
import java.sql.Date;
import java.sql.Timestamp;

/**
 * CatalogPndDoc generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "MM_CATALOG_PENDING_DOC_T")
public class CatalogPendingDoc extends MMPersistableBusinessObjectBase implements
java.io.Serializable {

	@Id
	@Column(name = "FDOC_NBR", unique = true, nullable = false, length = 36)
	private String fdocNbr;

	@Column(name = "CATALOG_CD", nullable = false, length = 2)
	private String catalogCd;

	@Column(name = "CATALOG_DESC", length = 200)
	private String catalogDesc;

	@Temporal(TemporalType.DATE)
	@Column(name = "CATALOG_BEGIN_DT", length = 7)
	private Date catalogBeginDt;

	@Temporal(TemporalType.DATE)
	@Column(name = "CATALOG_END_DT", length = 7)
	private Date catalogEndDt;

	@Column(name = "PRIORITY_NBR", precision = 8, scale = 0)
	private Integer priorityNbr;

	@Column(name = "AGREEMENT_NBR", precision = 9, scale = 0)
	private String agreementNbr;

	@Column(name = "CATALOG_TIMESTAMP")
	private Timestamp catalogTimestamp;

    @Column (name= "CATALOG_FILE" )
    private String catalogFile;

    @Column (name="BATCH_LOG")
    private String batchLog;

    @Column (name = "CATALOG_UPLOAD_STATUS")
    private String catalogUploadStatus;

    /**
     * Gets the catalogUploadStatus property
     * @return Returns the catalogUploadStatus
     */
    public String getCatalogUploadStatus() {
        return this.catalogUploadStatus;
    }

    /**
     * Sets the catalogUploadStatus property value
     * @param catalogUploadStatus The catalogUploadStatus to set
     */
    public void setCatalogUploadStatus(String catalogUploadStatus) {
        this.catalogUploadStatus = catalogUploadStatus;
    }

    /**
     * Gets the catalogFile property
     * @return Returns the catalogFile
     */
    public String getCatalogFile() {
        return this.catalogFile;
    }

    /**
     * Sets the catalogFile property value
     * @param catalogFile The catalogFile to set
     */
    public void setCatalogFile(String catalogFile) {
        this.catalogFile = catalogFile;
    }

    /**
     * Gets the batchLog property
     * @return Returns the batchLog
     */
    public String getBatchLog() {
        return this.batchLog;
    }

    /**
     * Sets the batchLog property value
     * @param batchLog The batchLog to set
     */
    public void setBatchLog(String batchLog) {
        this.batchLog = batchLog;
    }

    /**
     * Gets the catalogTimestamp property
     * @return Returns the catalogTimestamp
     */
    public Timestamp getCatalogTimestamp() {
        return this.catalogTimestamp;
    }

    /**
     * Sets the catalogTimestamp property value
     * @param catalogTimestamp The catalogTimestamp to set
     */
    public void setCatalogTimestamp(Timestamp catalogTimestamp) {
        this.catalogTimestamp = catalogTimestamp;
    }

    public CatalogPendingDoc() {
	}

	public String getFdocNbr() {
		return this.fdocNbr;
	}

	public void setFdocNbr(String fdocNbr) {
		this.fdocNbr = fdocNbr;
	}

	public String getCatalogCd() {
		return this.catalogCd;
	}

	public void setCatalogCd(String catalogCd) {
		this.catalogCd = catalogCd;
	}

	public String getCatalogDesc() {
		return this.catalogDesc;
	}

	public void setCatalogDesc(String catalogDesc) {
		this.catalogDesc = catalogDesc;
	}

	public Date getCatalogBeginDt() {
		return this.catalogBeginDt;
	}

	public void setCatalogBeginDt(Date catalogBeginDt) {
		this.catalogBeginDt = catalogBeginDt;
	}

	public Date getCatalogEndDt() {
		return this.catalogEndDt;
	}

	public void setCatalogEndDt(Date catalogEndDt) {
		this.catalogEndDt = catalogEndDt;
	}

	public Integer getPriorityNbr() {
		return this.priorityNbr;
	}

	public void setPriorityNbr(Integer priorityNbr) {
		this.priorityNbr = priorityNbr;
	}


	/**
     * Gets the agreementNbr property
     * @return Returns the agreementNbr
     */
    public String getAgreementNbr() {
        return this.agreementNbr;
    }

    /**
     * Sets the agreementNbr property value
     * @param agreementNbr The agreementNbr to set
     */
    public void setAgreementNbr(String agreementNbr) {
        this.agreementNbr = agreementNbr;
    }

}
