package org.kuali.ext.mm.businessobject;

// Generated Apr 16, 2009 10:01:00 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

/**
 * CatalogGroup generated by hbm2java
 */
@Entity
@Table(name = "MM_CATALOG_GROUP_T")
public class CatalogGroup extends MMPersistableBusinessObjectBase implements
		java.io.Serializable {

	private static final long serialVersionUID = 6424522615413365783L;

	@Id
	@Column(name = "CATALOG_GROUP_CD", unique = true, nullable = false, length = 12)
	private String catalogGroupCd;

	@Column(name = "CATALOG_GROUP_NM", length = 80)
	private String catalogGroupNm;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catalogGroup")
	private List<CatalogSubgroup> catalogSubgroups = new ArrayList<CatalogSubgroup>();
	
	private boolean displayableInd;

	@Transient
	private Integer resultSetCount;

	public CatalogGroup() {
	}

	public String getCatalogGroupCd() {
		return this.catalogGroupCd;
	}

	public void setCatalogGroupCd(String catalogGroupCd) {
		this.catalogGroupCd = catalogGroupCd;
	}

	public String getCatalogGroupNm() {
		return this.catalogGroupNm;
	}

	public boolean isDisplayableInd() {
        return displayableInd;
    }

    public void setDisplayableInd(boolean displayableInd) {
        this.displayableInd = displayableInd;
    }

    public void setCatalogGroupNm(String catalogGroupNm) {
		this.catalogGroupNm = catalogGroupNm;
	}

	public List<CatalogSubgroup> getCatalogSubgroups() {
		return this.catalogSubgroups;
	}

	public void setCatalogSubgroups(List<CatalogSubgroup> catalogSubgroups) {
		this.catalogSubgroups = catalogSubgroups;
	}

	public void setResultSetCount(Integer resultSetCount) {
		this.resultSetCount = resultSetCount;
	}

	public Integer getResultSetCount() {
		return resultSetCount;
	}


}
