package org.kuali.ext.mm.businessobject;

import javax.persistence.*;
import java.sql.Date;

/**
 * Catalog generated by hbm2java
 */
@Entity
@Table(name = "MM_CATALOG_T")
public class Catalog extends MMPersistableBusinessObjectBase implements
		java.io.Serializable {

	private static final long serialVersionUID = 4269561608993763928L;

	@Id
	@Column(name = "CATALOG_ID", unique = true, nullable = false, length = 18)
	private String 	catalogId;

	@Column(name = "CATALOG_CD", length = 2)
	private String catalogCd;

	@Column(name = "CATALOG_DESC", length = 200)
	private String 	catalogDesc;

	@Column(name = "CATALOG_BEGIN_DT", length = 7)
	private Date 	catalogBeginDt;

	@Column(name = "CATALOG_END_DT", length = 7)
	private Date 	catalogEndDt;

	@Column(name = "CATALOG_TYPE_CD", length = 1)
	private String 	catalogTypeCd;

	@Column(name = "PRIORITY_NBR", precision = 8)
	private Integer priorityNbr;

	@Column(name = "AGREEMENT_NBR", precision = 15)
	private String agreementNbr;

	private Agreement agreement;

	@Column(name = "CURRENT_IND", precision = 1)
	private boolean currentInd;

	@Column(name = "CATALOG_PENDING_DOC_NBR", length = 14)
	private String 	catalogPendingDocNbr;

	@Column(name = "WAREHOUSE_CD")
	private String warehouseCd;

	@Column(name= "DEFAULT_OBJECT_CD")
	private String defaultObjectCd;
	
	private boolean fromItemMaint;

	/**
     * Gets the defaultObjectCd property
     * @return Returns the defaultObjectCd
     */
    public String getDefaultObjectCd() {
        return this.defaultObjectCd;
    }

    /**
     * Sets the defaultObjectCd property value
     * @param defaultObjectCd The defaultObjectCd to set
     */
    public void setDefaultObjectCd(String defaultObjectCd) {
        this.defaultObjectCd = defaultObjectCd;
    }

    /**
     * Gets the serialVersionUID property
     * @return Returns the serialVersionUID
     */
    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    @ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "WAREHOUSE_CD", nullable = true)
	private Warehouse warehouse;

	public String getWarehouseCd() {
		return warehouseCd;
	}

	public void setWarehouseCd(String warehouseCd) {
		this.warehouseCd = warehouseCd;
	}

	public Warehouse getWarehouse() {
		return warehouse;
	}

	public void setWarehouse(Warehouse warehouse) {
		this.warehouse = warehouse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CATALOG_TYPE_CD", nullable = false)
	private CatalogType catalogType;



	public String getCatalogCd() {
		return catalogCd;
	}

	public void setCatalogCd(String catalogCd) {
		this.catalogCd = catalogCd;
	}

	public String getCatalogId() {
		return catalogId;
	}

	public void setCatalogId(String catalogId) {
		this.catalogId = catalogId;
	}

	public String getCatalogDesc() {
		return catalogDesc;
	}

	public void setCatalogDesc(String catalogDesc) {
		this.catalogDesc = catalogDesc;
	}

	public Date getCatalogBeginDt() {
		return catalogBeginDt;
	}

	public void setCatalogBeginDt(Date catalogBeginDt) {
		this.catalogBeginDt = catalogBeginDt;
	}

	public Date getCatalogEndDt() {
		return catalogEndDt;
	}

	public void setCatalogEndDt(Date catalogEndDt) {
		this.catalogEndDt = catalogEndDt;
	}

	public String getCatalogTypeCd() {
		return catalogTypeCd;
	}

	public void setCatalogTypeCd(String catalogTypeCd) {
		this.catalogTypeCd = catalogTypeCd;
	}

	public Integer getPriorityNbr() {
		return priorityNbr;
	}

	public void setPriorityNbr(Integer priorityNbr) {
		this.priorityNbr = priorityNbr;
	}

	public String getAgreementNbr() {
		return agreementNbr;
	}

	public void setAgreementNbr(String agreementNbr) {
		this.agreementNbr = agreementNbr;
	}

	public void setAgreement(Agreement agreement) {
		this.agreement = agreement;
	}

	public Agreement getAgreement() {
		return agreement;
	}

	public boolean isCurrentInd() {
		return currentInd;
	}

	public void setCurrentInd(boolean currentInd) {
		this.currentInd = currentInd;
	}

	public String getCatalogPendingDocNbr() {
		return catalogPendingDocNbr;
	}

	public void setCatalogPendingDocNbr(String catalogPendingDocNbr) {
		this.catalogPendingDocNbr = catalogPendingDocNbr;
	}

	public CatalogType getCatalogType() {
		return catalogType;
	}

	public void setCatalogType(CatalogType catalogType) {
		this.catalogType = catalogType;
	}


    /**
     * Gets the fromItemMaint property
     * @return Returns the fromItemMaint
     */
    public boolean isFromItemMaint() {
        return this.fromItemMaint;
    }

    /**
     * Sets the fromItemMaint property value
     * @param fromItemMaint The fromItemMaint to set
     */
    public void setFromItemMaint(boolean fromItemMaint) {
        this.fromItemMaint = fromItemMaint;
    }

}
