package org.kuali.ext.mm.businessobject;

// Generated Apr 14, 2009 9:40:31 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.ArrayList;
import java.util.List;
/**
 * PriceCode generated by hbm2java
 */
@Entity
@Table(name = "MM_COST_CODE_T")
public class CostCode extends MMPersistableBusinessObjectBase {

	private static final long serialVersionUID = -6928054231044486993L;

	@Id
	@Column(name = "COST_CD", unique = true, nullable = false, length = 2)
	private String costCd;

	@Column(name = "NM", length = 45)
	private String itemCostDesc;

	private List<StockCost> stockPrices = new ArrayList<StockCost>();
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "priceCode")
//	private Set<ItemPrice> itemPrices = new HashSet<ItemPrice>(0);

	public CostCode() {
	}

	public String getCostCd() {
		return this.costCd;
	}

	public void setCostCd(String costCd) {
		this.costCd = costCd;
	}

	public String getItemCostDesc() {
		return this.itemCostDesc;
	}

	public void setItemCostDesc(String itemCostDesc) {
		this.itemCostDesc = itemCostDesc;
	}

//	public Set<ItemPrice> getItemPrices() {
//		return this.itemPrices;
//	}
//
//	public void setItemPrices(Set<ItemPrice> itemPrices) {
//		this.itemPrices = itemPrices;
//	}

	public void setStockPrices(List<StockCost> stockPrices) {
		this.stockPrices = stockPrices;
	}

	public List<StockCost> getStockPrices() {
		return stockPrices;
	}

}
