package org.kuali.ext.mm.businessobject;

// Generated Apr 10, 2009 8:50:50 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.*;

/**
 * CountParameter generated by hbm2java
 */
@Entity
@Table(name = "MM_COUNT_PARAMETER_T")
public class CountParameter extends MMPersistableBusinessObjectBase implements
		java.io.Serializable {

	private static final long serialVersionUID = 5248308258951770753L;

	@Id
	@Column(name = "COUNT_PARAMETER_ID", unique = true, nullable = false, precision = 8, scale = 0)
	private Integer countParameterId;

	@Column(name = "FROM_WAREHOUSE_CD", nullable = false, length = 2)
	private String fromWarehouseCode;

	@Column(name = "TO_WAREHOUSE_CD", nullable = false, length = 2)
	private String toWarehouseCode;

	// TODO: We need to remove all these references and also remove "defaultExistenceChecks"  for these from xml file (this is a special case)

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FROM_WAREHOUSE_CD")
	private Warehouse fromWarehouse;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TO_WAREHOUSE_CD")
	private Warehouse toWarehouse;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FROM_ZONE_CD")
	private Zone fromZone;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FROM_BIN_CD")
	private Bin fromBin;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TO_BIN_CD")
	private Bin toBin;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FROM_ZONE_CD")
	private Zone toZone;

	@Column(name = "COUNT_PARAMETER_DESC", nullable = false, length = 200)
	private String countParameterDesc;

	@Column(name = "FROM_CYCLE_COUNT_CD", nullable = false, length = 1)
	private String fromCycleCountCode;

	@Column(name = "FROM_ZONE_CD", length = 2)
	private String fromZoneCode;

	@Column(name = "FROM_BIN_NBR", length = 6)
	private String fromBinNumber;

	@Column(name = "FROM_SHELF_ID", length = 2)
	private String fromShelfId;

	@Column(name = "FROM_SHELF_ID_NBR", length = 2)
	private String fromShelfIdNumber;

	@Column(name = "TO_CYCLE_COUNT_CD", nullable = false, length = 1)
	private String toCycleCountCode;

	@Column(name = "TO_ZONE_CD", length = 2)
	private String toZoneCode;

	@Column(name = "TO_BIN_NBR", length = 6)
	private String toBinNumber;

	@Column(name = "TO_SHELF_ID", length = 2)
	private String toShelfId;

	@Column(name = "TO_SHELF_ID_NBR", length = 2)
	private String toShelfIdNumber;

	@Column(name = "COUNT_FREQUENCY_CD", nullable = false, length = 12)
	private String countFrequencyCode;

	public CountParameter() {
	}

	public Integer getCountParameterId() {
		return this.countParameterId;
	}

	public void setCountParameterId(Integer countParameterId) {
		this.countParameterId = countParameterId;
	}

	public void setFromWarehouseCode(String fromWarehouseCode) {
		this.fromWarehouseCode = fromWarehouseCode;
	}

	public String getFromWarehouseCode() {
		return this.fromWarehouseCode;
	}

	public Warehouse getFromWarehouse() {
		return this.fromWarehouse;
	}

	public void setFromWarehouse(Warehouse warehouse) {
		this.fromWarehouse = warehouse;
	}

	public String getToWarehouseCode() {
		return this.toWarehouseCode;
	}

	public void setToWarehouseCode(String toWarehouseCode) {
		this.toWarehouseCode = toWarehouseCode;
	}

	public String getCountParameterDesc() {
		return this.countParameterDesc;
	}

	public void setCountParameterDesc(String countParameterDesc) {
		this.countParameterDesc = countParameterDesc;
	}

	public String getFromCycleCountCode() {
		return this.fromCycleCountCode;
	}

	public void setFromCycleCountCode(String fromCycleCountCode) {
		this.fromCycleCountCode = fromCycleCountCode;
	}

	public String getFromZoneCode() {
		return this.fromZoneCode;
	}

	public void setFromZoneCode(String fromZoneCode) {
		this.fromZoneCode = fromZoneCode;
	}

	public String getFromBinNumber() {
		return this.fromBinNumber;
	}

	public void setFromBinNumber(String fromBinNumber) {
		this.fromBinNumber = fromBinNumber;
	}

	public String getFromShelfId() {
		return this.fromShelfId;
	}

	public void setFromShelfId(String fromShelfId) {
		this.fromShelfId = fromShelfId;
	}

	public String getFromShelfIdNumber() {
		return this.fromShelfIdNumber;
	}

	public void setFromShelfIdNumber(String fromShelfIdNumber) {
		this.fromShelfIdNumber = fromShelfIdNumber;
	}

	public String getToCycleCountCode() {
		return this.toCycleCountCode;
	}

	public void setToCycleCountCode(String toCycleCountCode) {
		this.toCycleCountCode = toCycleCountCode;
	}

	public String getToZoneCode() {
		return this.toZoneCode;
	}

	public void setToZoneCode(String toZoneCode) {
		this.toZoneCode = toZoneCode;
	}

	public String getToBinNumber() {
		return this.toBinNumber;
	}

	public void setToBinNumber(String toBinNumber) {
		this.toBinNumber = toBinNumber;
	}

	public String getToShelfId() {
		return this.toShelfId;
	}

	public void setToShelfId(String toShelfId) {
		this.toShelfId = toShelfId;
	}

	public String getToShelfIdNumber() {
		return this.toShelfIdNumber;
	}

	public void setToShelfIdNumber(String toShelfIdNumber) {
		this.toShelfIdNumber = toShelfIdNumber;
	}

	public String getCountFrequencyCode() {
		return this.countFrequencyCode;
	}

	public void setCountFrequencyCode(String countFrequencyCode) {
		this.countFrequencyCode = countFrequencyCode;
	}

	public Warehouse getToWarehouse() {
		return toWarehouse;
	}

	public void setToWarehouse(Warehouse toWarehouse) {
		this.toWarehouse = toWarehouse;
	}

	public Bin getFromBin() {
		return fromBin;
	}

	public void setFromBin(Bin fromBin) {
		this.fromBin = fromBin;
	}

	public Bin getToBin() {
		return toBin;
	}

	public void setToBin(Bin toBin) {
		this.toBin = toBin;
	}

	public Zone getFromZone() {
		return fromZone;
	}

	public void setFromZone(Zone fromZone) {
		this.fromZone = fromZone;
	}

	public Zone getToZone() {
		return toZone;
	}

	public void setToZone(Zone toZone) {
		this.toZone = toZone;
	}



}
