package org.kuali.ext.mm.businessobject;

// Generated Jun 5, 2009 2:34:57 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CountFrequency generated by hbm2java
 */
@Entity
@Table(name = "MM_COUNT_FREQUENCY_T")
public class CountFrequency extends MMPersistableBusinessObjectBase {

	/**
     *
     */
    private static final long serialVersionUID = 1338434259641834863L;

    @Id
	@Column(name = "COUNT_FREQUENCY_CD", unique = true, nullable = false, length = 12)
	private String countFrequencyCode;

	@Column(name = "NM", length = 45)
	private String countFrequencyName;

	@Column(name = "TIMES_PER_YEAR_NBR", nullable = false, precision = 8, scale = 0)
	private Integer timesPerYearNumber;

	public CountFrequency() {
	}

	public String getCountFrequencyCode() {
		return this.countFrequencyCode;
	}

	public void setCountFrequencyCode(String countFrequencyCode) {
		this.countFrequencyCode = countFrequencyCode;
	}

	public String getCountFrequencyName() {
		return this.countFrequencyName;
	}

	public void setCountFrequencyName(String countFrequencyName) {
		this.countFrequencyName = countFrequencyName;
	}

	public Integer getTimesPerYearNumber() {
		return this.timesPerYearNumber;
	}

	public void setTimesPerYearNumber(Integer timesPerYearNumber) {
		this.timesPerYearNumber = timesPerYearNumber;
	}

}
