package org.kuali.ext.mm.businessobject;

// Generated Apr 10, 2009 8:50:50 AM by Hibernate Tools 3.2.4.GA

import org.apache.commons.lang.StringUtils;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "MM_CUSTOMER_T")
public class Customer extends MMPersistableBusinessObjectBase {

    private static final long serialVersionUID = 7758362955045442356L;

    @Id
    @Column(name = "PRNCPL_NM", unique = true, nullable = false, length = 12)
    private String principalName;

    @Column(name = "FIRST_NM")
    private String firstName;

    @Column(name = "LAST_NM")
    private String lastName;

    @Column(name = "FIRST_NM")
    private String customerPassword;

    @Transient
    private String confirmPassword;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
    private List<Profile> profiles = new ArrayList<Profile>(0);

    public Customer() {
    }

    public String getPrincipalName() {
        return this.principalName;
    }

    public void setPrincipalName(String principalName) {
        this.principalName = principalName;
    }

    public String getCustomerName() {
        if (StringUtils.isBlank(this.lastName)) {
            if (StringUtils.isNotBlank(this.firstName))
                return this.firstName;
            return null;
        }
        if (StringUtils.isBlank(this.firstName))
            return this.lastName;

        return this.firstName + " " + this.lastName;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getCustomerPassword() {
        return this.customerPassword;
    }

    public void setCustomerPassword(String customerPassword) {
        this.customerPassword = customerPassword;
    }

    public void setConfirmPassword(String confirmPassword) {
        this.confirmPassword = confirmPassword;
    }

    public String getConfirmPassword() {
        return confirmPassword;
    }

    public List<Profile> getProfiles() {
        return this.profiles;
    }

    public void setProfiles(List<Profile> Profiles) {
        this.profiles = Profiles;
    }

}
