package org.kuali.ext.mm.businessobject;

// Generated Apr 1, 2009 12:28:16 PM by Hibernate Tools 3.2.2.GA

import org.kuali.rice.core.api.util.type.KualiDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cycle generated by hbm2java
 */
@Entity
@Table(name = "MM_CYCLE_COUNT_T")
public class CycleCount extends MMPersistableBusinessObjectBase implements
		java.io.Serializable {
	private static final long serialVersionUID = 2867548595304349798L;

	@Id
	@Column(name = "CYCLE_CNT_CD", unique = true, nullable = false, length = 1)
	private String cycleCntCd;

    @Column(name = "TOLERANCE_AMT", precision = 8, scale = 3)
    private KualiDecimal toleranceAmt;

	@Column(name = "CYCLE_CNT_DESC", length = 80)
	private String cycleCntDesc;

 	@Column(name = "TIMES_PER_YEAR_NBR", precision = 8, scale = 0)
	private Long timesPerYearNbr;

	public CycleCount() {
	}

	public CycleCount(String cycleCntCd) {
		this.cycleCntCd = cycleCntCd;
	}

	public String getCycleCntCd() {
		return this.cycleCntCd;
	}

	public String getCycleCntCdLookable() {
		return this.cycleCntCd;
	}

	public void setCycleCntCd(String cycleCntCd) {
		this.cycleCntCd = cycleCntCd;
	}

	public void setCycleCntCdLookable(String cycleCntCd) {
		this.cycleCntCd = cycleCntCd;
	}

	public String getCycleCntDesc() {
		return this.cycleCntDesc;
	}

	public void setCycleCntDesc(String cycleCntDesc) {
		this.cycleCntDesc = cycleCntDesc;
	}

    public KualiDecimal getToleranceAmt() {
        return this.toleranceAmt;
    }

    public void setToleranceAmt(KualiDecimal toleranceAmt) {
        this.toleranceAmt = toleranceAmt;
    }

	public Long getTimesPerYearNbr() {
		return this.timesPerYearNbr;
	}

	public void setTimesPerYearNbr(Long timesPerYearNbr) {
		this.timesPerYearNbr = timesPerYearNbr;
	}

}
