package org.kuali.ext.mm.businessobject;

// Generated Apr 1, 2009 12:28:16 PM by Hibernate Tools 3.2.2.GA

import java.util.LinkedHashMap;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cycle generated by hbm2java
 */
@Entity
@Table(name = "MM_DISPOSITION_T")
public class DispositionCode extends MMPersistableBusinessObjectBase implements
		java.io.Serializable {

	/**
     *
     */
    private static final long serialVersionUID = 9128765683943733371L;


    @Id
	@Column(name = "DISPOSITION_CD", unique = true, nullable = false, length = 12)
	private String dispositionCode;


    @Column(name = "NM", length = 80)
	private String dispositionName;


	public DispositionCode() {
	}

    public String getDispositionCode() {
        return dispositionCode;
    }


    public void setDispositionCode(String dispositionCode) {
        this.dispositionCode = dispositionCode;
    }


    public String getDispositionName() {
        return dispositionName;
    }


    public void setDispositionName(String dispositionName) {
        this.dispositionName = dispositionName;
    }

	/**
	 * toStringMapper
	 * @return LinkedHashMap
	 */
	@Override
    public LinkedHashMap toStringMapper() {
		LinkedHashMap propMap = new LinkedHashMap();
		//TODO:  Autogenerated method

		return propMap;
	}

}
