package org.kuali.ext.mm.businessobject;

// Generated Apr 16, 2009 10:01:00 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.*;

/**
 * DotHazardous generated by hbm2java
 */
@Entity
@Table(name = "MM_DOT_HAZARDOUS_T")
public class DotHazardous extends MMPersistableBusinessObjectBase implements
		java.io.Serializable {

	private static final long serialVersionUID = 7044471280708464541L;

	@Id
	@Column(name = "DOT_HAZARDOUS_CD", unique = true, nullable = false, length = 5)
	private String dotHazardousCd;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DRIVER_MANIFEST_CD")
	private DriverManifest driverManifest;

	@Column(name = "NM", nullable = false, length = 45)
	private String dotHazardousName;

	@Column(name = "DRIVER_MANIFEST_CD", length = 2)
	private String driverManifestCd;

	public DotHazardous() {
	}

	public String getDotHazardousCd() {
		return this.dotHazardousCd;
	}

	public void setDotHazardousCd(String dotHazardousCd) {
		this.dotHazardousCd = dotHazardousCd;
	}

	public String getDotHazardousName() {
		return this.dotHazardousName;
	}

	public void setDotHazardousName(String dotHazardousName) {
		this.dotHazardousName = dotHazardousName;
	}

	public String getDriverManifestCd() {
		return this.driverManifestCd;
	}

	public void setDriverManifestCd(String driverManifestCd) {
		this.driverManifestCd = driverManifestCd;
	}

	public DriverManifest getDriverManifest() {
		return this.driverManifest;
	}

	public void setDriverManifest(DriverManifest dotDriverManifest) {
		this.driverManifest = dotDriverManifest;
	}

}
