package org.kuali.ext.mm.businessobject;

// Generated Apr 16, 2009 10:01:00 AM by Hibernate Tools 3.2.4.GA

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DriverManifest generated by hbm2java
 */
@Entity
@Table(name = "MM_DRIVER_MANIFEST_T")
public class DriverManifest extends MMPersistableBusinessObjectBase {

	private static final long serialVersionUID = -838128224766383700L;

	@Id
	@Column(name = "DRIVER_MANIFEST_CD", unique = true, nullable = false, length = 2)
	private String driverManifestCode;

	@Column(name = "NM", length = 45)
	private String driverManifestName;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "driverManifest")
	private List<Route> routes = new ArrayList<Route>();

	public DriverManifest() {
	}

	public String getDriverManifestCode() {
		return this.driverManifestCode;
	}

	public void setDriverManifestCode(String driverManifestCode) {
		this.driverManifestCode = driverManifestCode;
	}

	public String getDriverManifestName() {
		return this.driverManifestName;
	}

	public void setDriverManifestName(String driverManifestName) {
		this.driverManifestName = driverManifestName;
	}

	public List<Route> getRoutes() {
		return this.routes;
	}

	public void setRoutes(List<Route> routes) {
		this.routes = routes;
	}

	/**
	 * toStringMapper
	 * @return LinkedHashMap
	 */
	@Override
    public LinkedHashMap toStringMapper() {
		LinkedHashMap propMap = new LinkedHashMap();
		//TODO:  Autogenerated method

		return propMap;
	}

}
