package org.kuali.ext.mm.businessobject;

// Generated Apr 2, 2009 11:05:56 AM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EhsHazardousState generated by hbm2java
 */
@Entity
@Table(name = "MM_EHS_HAZARDOUS_STATE_T")
public class EhsHazardousState extends MMPersistableBusinessObjectBase
		implements java.io.Serializable {

	private static final long serialVersionUID = -4628612682080859468L;

	@Id
	@Column(name = "EHS_HAZARDOUS_STATE_CD", unique = true, nullable = false, length = 1)
	private String ehsHazardousStateCode;

	@Column(name = "NM", length = 45)
	private String ehsHazardousStateName;

	public EhsHazardousState() {
	}

	public EhsHazardousState(String ehsHazardousStateCode) {
		this.ehsHazardousStateCode = ehsHazardousStateCode;
	}

	public EhsHazardousState(String ehsHazardousStateCode,
			String ehsHazardousStateName) {
		this.ehsHazardousStateCode = ehsHazardousStateCode;
		this.ehsHazardousStateName = ehsHazardousStateName;
	}

	public String getEhsHazardousStateCode() {
		return this.ehsHazardousStateCode;
	}

	public void setEhsHazardousStateCode(String ehsHazardousStateCode) {
		this.ehsHazardousStateCode = ehsHazardousStateCode;
	}

	public String getEhsHazardousStateName() {
		return this.ehsHazardousStateName;
	}

	public void setEhsHazardousStateName(String ehsHazardousStateName) {
		this.ehsHazardousStateName = ehsHazardousStateName;
	}

}
