package org.kuali.ext.mm.businessobject;

import org.kuali.ext.mm.common.sys.MMConstants;
import org.kuali.rice.core.api.util.type.KualiDecimal;

import javax.persistence.*;
import java.math.BigDecimal;


/**
 * HazardousMateriel generated by hbm2java
 */
@Entity
@Table(name = "MM_HAZARDOUS_MATERIEL_T")
public class HazardousMateriel extends MMPersistableBusinessObjectBase implements
        java.io.Serializable {

    private static final long serialVersionUID = -7419414245788580422L;

    @Id
    @Column(name = "HAZARDOUS_MATERIEL_ID", nullable = false, unique = true, precision = 18)
    private Integer hazardousMaterielId;

    @Column(name = "STOCK_ID", length = 18)
    private String stockId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STOCK_ID")
    private Stock stock;

    @Column(name = "HAZARDOUS_UN_CD", length = 12)
    private String hazardousUnCode;

    @Column(name = "EHS_HAZARDOUS_CD", length = 3)
    private String ehsHazardousCd;

    @Column(name = "EHS_CONTAINER_CD", length = 6)
    private String ehsContainerCode;

    @Column(name = "EHS_CAS_NBR", length = 20)
    private String ehsCasNbr;

    @Column(name = "EHS_HAZARDOUS_STATE_CD", length = 1)
    private String ehsHazardousStateCode;

    @Column(name = "EHS_CONVERSION_UNIT_FACTOR", precision = 4, scale = 3)
    private BigDecimal ehsConversionUnitFactor;

    @Column(name = "EHS_UNIT_OF_ISSUE_CD", length = 10)
    private String ehsUnitOfIssueCd;

    @Column(name = "DOT_HAZARDOUS_CD", length = 5)
    private String dotHazardousCd;

    @Column(name = "TYPE_OF_USE", length = 10)
    private String typeOfUse;

    @Column(name = "HAZARDOUS_PRESSURE", precision = 10, scale = 3)
    private KualiDecimal hazardousPressure;

    @Column(name = "HAZARDOUS_TEMPERATURE", precision = 10, scale = 3)
    private KualiDecimal hazardousTemperature;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "HAZARDOUS_UN_CD")
    private HazardousUn hazardousUn;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "EHS_HAZARDOUS_CD")
    private EhsHazardous ehsHazardous;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "EHS_CONTAINER_CD")
    private EhsContainer ehsContainer;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "EHS_HAZARDOUS_STATE_CD")
    private EhsHazardousState ehsHazardousState;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "EHS_UNIT_OF_ISSUE_CD")
    private UnitOfIssue unitOfIssue;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DOT_HAZARDOUS_CD")
    private DotHazardous dotHazardous;

    public Stock getStock() {
        return stock;
    }

    public void setStock(Stock stock) {
        this.stock = stock;
    }

    public Integer getHazardousMaterielId() {
        return hazardousMaterielId;
    }


    public void setHazardousMaterielId(Integer hazardousMaterielId) {
        this.hazardousMaterielId = hazardousMaterielId;
    }


    public String getEhsHazardousStateCode() {
        return ehsHazardousStateCode;
    }


    public void setEhsHazardousStateCode(String ehsHazardousStateCode) {
        this.ehsHazardousStateCode = ehsHazardousStateCode;
    }

    public String getehsHazardousStateCode() {
        return ehsHazardousStateCode;
    }


    public void setehsHazardousStateCode(String ehsHazardousStateCode) {
        this.ehsHazardousStateCode = ehsHazardousStateCode;
    }

    public String getStockId() {
        return stockId;
    }


    public void setStockId(String stockId) {
        this.stockId = stockId;
    }


    public String getHazardousUnCode() {
        return hazardousUnCode;
    }


    public void setHazardousUnCode(String hazardousUnCode) {
        this.hazardousUnCode = hazardousUnCode;
    }


    public String getEhsHazardousCd() {
        return ehsHazardousCd;
    }


    public void setEhsHazardousCd(String ehsHazardousCd) {
        this.ehsHazardousCd = ehsHazardousCd;
    }


    public String getEhsContainerCode() {
        return ehsContainerCode;
    }


    public void setEhsContainerCode(String ehsContainerCode) {
        this.ehsContainerCode = ehsContainerCode;
    }


    public String getEhsCasNbr() {
        return ehsCasNbr;
    }


    public void setEhsCasNbr(String ehsCasNbr) {
        this.ehsCasNbr = ehsCasNbr;
    }


    public BigDecimal getEhsConversionUnitFactor() {
        return ehsConversionUnitFactor;
    }


    public void setEhsConversionUnitFactor(BigDecimal ehsConversionUnitFactor) {
        if (ehsConversionUnitFactor != null) {
            this.ehsConversionUnitFactor = ehsConversionUnitFactor.setScale(
                    MMConstants.AMOUNT_MIN_SCALE, KualiDecimal.ROUND_BEHAVIOR);
        }
    }


    public String getEhsUnitOfIssueCd() {
        return ehsUnitOfIssueCd;
    }


    public void setEhsUnitOfIssueCd(String ehsUnitOfIssueCd) {
        this.ehsUnitOfIssueCd = ehsUnitOfIssueCd;
    }


    public String getDotHazardousCd() {
        return dotHazardousCd;
    }


    public void setDotHazardousCd(String dotHazardousCd) {
        this.dotHazardousCd = dotHazardousCd;
    }


    public String getTypeOfUse() {
        return typeOfUse;
    }


    public void setTypeOfUse(String typeOfUse) {
        this.typeOfUse = typeOfUse;
    }


    public KualiDecimal getHazardousPressure() {
        return hazardousPressure;
    }


    public void setHazardousPressure(KualiDecimal hazardousPressure) {
        this.hazardousPressure = hazardousPressure;
    }


    public KualiDecimal getHazardousTemperature() {
        return hazardousTemperature;
    }


    public void setHazardousTemperature(KualiDecimal hazardousTemperature) {
        this.hazardousTemperature = hazardousTemperature;
    }


    public HazardousUn getHazardousUn() {
        return hazardousUn;
    }


    public void setHazardousUn(HazardousUn hazardousUn) {
        this.hazardousUn = hazardousUn;
    }


    public EhsHazardous getEhsHazardous() {
        return ehsHazardous;
    }


    public void setEhsHazardous(EhsHazardous ehsHazardous) {
        this.ehsHazardous = ehsHazardous;
    }


    public EhsContainer getEhsContainer() {
        return ehsContainer;
    }


    public void setEhsContainer(EhsContainer ehsContainer) {
        this.ehsContainer = ehsContainer;
    }


    public EhsHazardousState getEhsHazardousState() {
        return ehsHazardousState;
    }


    public void setEhsHazardousState(EhsHazardousState ehsHazardousState) {
        this.ehsHazardousState = ehsHazardousState;
    }


    public UnitOfIssue getUnitOfIssue() {
        return unitOfIssue;
    }


    public void setUnitOfIssue(UnitOfIssue unitOfIssue) {
        this.unitOfIssue = unitOfIssue;
    }


    public DotHazardous getDotHazardous() {
        return dotHazardous;
    }


    public void setDotHazardous(DotHazardous dotHazardous) {
        this.dotHazardous = dotHazardous;
    }


}
