package org.kuali.ext.mm.businessobject;

// Generated Apr 13, 2009 2:30:37 PM by Hibernate Tools 3.2.4.GA

import java.util.LinkedHashMap;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MarkupType generated by hbm2java
 */
@Entity
@Table(name = "MM_MARKUP_TYPE_T")
public class MarkupType extends MMPersistableBusinessObjectBase {

	private static final long serialVersionUID = -1244036279157406546L;

	@Id
	@Column(name = "MARKUP_TYPE_CD", unique = true, nullable = false, length = 2)
	private String markupTypeCd;

	@Column(name = "NM", length = 45)
	private String markupTypeDesc;

	public MarkupType() {
	}

	public String getMarkupTypeCd() {
		return this.markupTypeCd;
	}

	public void setMarkupTypeCd(String markupTypeCd) {
		this.markupTypeCd = markupTypeCd;
	}

	public String getMarkupTypeDesc() {
		return this.markupTypeDesc;
	}

	public void setMarkupTypeDesc(String markupTypeDesc) {
		this.markupTypeDesc = markupTypeDesc;
	}


	/**
	 * toStringMapper
	 * @return LinkedHashMap
	 */
	@Override
    public LinkedHashMap toStringMapper() {
		LinkedHashMap propMap = new LinkedHashMap();
		//TODO:  Autogenerated method

		return propMap;
	}

}
