package org.kuali.ext.mm.businessobject;

// Generated Apr 14, 2009 9:40:31 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OrderStatus generated by hbm2java
 */
@Entity
@Table(name = "MM_ORDER_STATUS_T")
public class OrderStatus extends MMPersistableBusinessObjectBase implements
		java.io.Serializable {

	private static final long serialVersionUID = 3856644054113686016L;

	@Id
	@Column(name = "ORDER_STATUS_CD", unique = true, nullable = false, length = 4)
	private String orderStatusCd;

	@Column(name = "NM", length = 45)
	private String orderStatusDesc;

	public OrderStatus() {
	}

	public String getOrderStatusCd() {
		return this.orderStatusCd;
	}

	public void setOrderStatusCd(String orderStatusCd) {
		this.orderStatusCd = orderStatusCd;
	}

	public String getOrderStatusDesc() {
		return this.orderStatusDesc;
	}

	public void setOrderStatusDesc(String orderStatusDesc) {
		this.orderStatusDesc = orderStatusDesc;
	}

	public String getOrderStatusCodeLookable(){
		return this.getOrderStatusCd();
	}


}
