package org.kuali.ext.mm.businessobject;

// Generated May 11, 2009 11:03:40 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

/**
 * PackListDoc generated by hbm2java
 */
@Entity
@Table(name = "MM_PACK_LIST_DOC_T")
public class PackListDoc extends MMPersistableBusinessObjectBase {

	/**
     *
     */
    private static final long serialVersionUID = 6501560721104956971L;
    @Id
	@Column(name = "FDOC_NBR", unique = true, nullable = false, length = 36)
	private String fdocNbr;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PACK_STATUS_CD", nullable = false)
	private PackStatusCode packStatusCode;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "packListDoc")
	private List<PackListLine> packListLines = new ArrayList<PackListLine>();

	public PackListDoc() {
	}

	public String getFdocNbr() {
		return this.fdocNbr;
	}

	public void setFdocNbr(String fdocNbr) {
		this.fdocNbr = fdocNbr;
	}

	public PackStatusCode getPackStatusCode() {
		return this.packStatusCode;
	}

	public void setPackStatusCode(PackStatusCode packStatusCode) {
		this.packStatusCode = packStatusCode;
	}

	public List<PackListLine> getPackListLines() {
		return this.packListLines;
	}

	public void setPackListLines(List<PackListLine> packListLines) {
		this.packListLines = packListLines;
	}


}
