package org.kuali.ext.mm.businessobject;

// Generated Apr 13, 2009 2:30:37 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PackListAnnouncement generated by hbm2java
 */
@Entity
@Table(name = "MM_PACK_LIST_ANNOUNCEMENT_T")
public class PackListAnnouncement extends MMPersistableBusinessObjectBase {

	private static final long serialVersionUID = 6184857906860456200L;

	@Id
	@Column(name = "PACK_LIST_ANNOUNCEMENT_CD", unique = true, nullable = false, length = 8)
	private String packListAnnouncementCode;

	@Column(name = "PACK_LIST_ANNOUNCEMENT_DESC", length = 200)
	private String packListAnnouncementDesc;

	public PackListAnnouncement() {
	}

	public String getPackListAnnouncementCode() {
		return this.packListAnnouncementCode;
	}

	public void setPackListAnnouncementCode(String packListAnnouncementCode) {
		this.packListAnnouncementCode = packListAnnouncementCode;
	}

	public String getPackListAnnouncementDesc() {
		return this.packListAnnouncementDesc;
	}

	public void setPackListAnnouncementDesc(String packListAnnouncementDesc) {
		this.packListAnnouncementDesc = packListAnnouncementDesc;
	}


}
