package org.kuali.ext.mm.businessobject;

// Generated Apr 8, 2009 10:12:44 AM by Hibernate Tools 3.2.4.GA


import java.util.LinkedHashMap;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Zone generated by hbm2java
 */
@Entity
@Table(name = "MM_PUNCH_OUT_VNDR_T")
public class PCard extends MMPersistableBusinessObjectBase implements java.io.Serializable {
	
    private static final long serialVersionUID = 5424136791184917323L;

    private String cardId;

	private String cardNumber;
    
    private String cardExpireDate;
    
    private String cardName;
	
	public PCard() {
	}

    public String getCardId() {
        return this.cardId;
    }

    public void setCardId(String cardId) {
        this.cardId = cardId;
    }

    public String getCardNumber() {
        return this.cardNumber;
    }

    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }

    public String getCardExpireDate() {
        return this.cardExpireDate;
    }

    public void setCardExpireDate(String cardExpireDate) {
        this.cardExpireDate = cardExpireDate;
    }

    public String getCardName() {
        return this.cardName;
    }

    public void setCardName(String cardName) {
        this.cardName = cardName;
    }

    /**
	 * toStringMapper
	 * @return LinkedHashMap
	 */
	@Override
    public LinkedHashMap toStringMapper() {
		LinkedHashMap propMap = new LinkedHashMap();
		//TODO:  Autogenerated method

		return propMap;
	}

}
