package org.kuali.ext.mm.businessobject;

// Generated May 19, 2009 9:29:05 AM by Hibernate Tools 3.2.4.GA

import org.apache.commons.lang.StringUtils;
import org.kuali.ext.mm.common.sys.MMConstants;
import org.kuali.ext.mm.common.sys.context.SpringContext;
import org.kuali.ext.mm.document.PickListDocument;
import org.kuali.ext.mm.service.RentalService;
import org.kuali.ext.mm.service.StockService;
import org.kuali.rice.krad.util.ObjectUtils;

import javax.persistence.*;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;


/**
 * PickListLine generated by hbm2java
 */
@Entity
@Table(name = "MM_PICK_LIST_LINE_T")
public class PickListLine extends MMPersistableBusinessObjectBase implements Cloneable{

	/**
     *
     */
    private static final long serialVersionUID = -8893748443266637406L;

    @Id
	@Column(name = "PICK_LIST_LINE_ID", unique = true, nullable = false, length = 36)
	private String pickListLineId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PICK_LIST_DOC_NBR", nullable = false)
	private PickTicket pickTicket;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PICK_LIST_DOC_NBR", nullable = false)
	private PickListDocument pickListDocument;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PICK_STATUS_CD",  nullable = false)
	private PickStatusCode pickStatusCode;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORDER_DETAIL_ID",  nullable = false)
	private OrderDetail orderDetail;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STOCK_ID",  nullable = false)
	private Stock stock;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORDER_ID", nullable = false)
	private SalesInstance salesInstance;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BIN_ID", nullable = false)
	private Bin bin;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROUTE_CD", nullable = false)
	private Route route;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BACK_ORDER_ID", nullable = true)
	private BackOrder backOrder;

	//BEGIN OJB
	@Column(name = "PICK_TICKET_NBR")
	private String pickTicketNumber;

	@Column(name = "PICK_TICKET_NBR")
	private String pickListDocumentNumber;

	@Column(name = "PICK_STATUS_CD")
	private String pickStatusCodeCd;

	@Column(name = "SALES_INSTANCE_ID", nullable = false)
	private Integer salesInstanceId;

	@Column(name = "STOCK_ID", nullable = false, length = 12)
	private String stockId;

	@Column(name = "ORDER_DETAIL_ID")
	private Integer orderDetailId;

	@Column(name = "ROUTE_CD", length = 2)
	private String routeCd;

	@Column(name = "BACK_ORDER_ID", length = 14)
	private String backOrderId;
	//END OJB

	@Column(name = "PICK_TUB_NBR", precision = 8, scale = 0)
	private Integer pickTubNbr;

	@Column(name = "ORDER_LINE_NBR", nullable = false, precision = 8, scale = 0)
	private Integer orderLineNbr;

	@Column(name = "BIN_ID", length = 36)
	private Integer binId;

	@Column(name = "STOCK_QTY", nullable = false, precision = 11, scale = 4)
	private Integer stockQty;

	@Column(name = "PICK_STOCK_QTY", nullable = false, precision = 11, scale = 4)
	private Integer pickStockQty;

	@Column(name = "BACK_ORDER_QTY", nullable = false, precision = 11, scale = 4)
	private Integer backOrderQty;

	@Column(name = "PICK_LIST_LINE_CREATED_DT")
	private Timestamp createdDate;
	
	@Column(name = "PICK_LIST_LINE_VERIFY_DT")
    private Timestamp verifyDate;

	@Column(name = "CHARGE_DOC_NBR")
	private String chargeDocumentNumber;
	
	private Integer chargeDocumentItemNumber;

	private List<Rental> rentals = new ArrayList<Rental>();

	@Transient
    private List<PickListLine> additionalLines = new ArrayList<PickListLine>();
	
	public PickListLine() {
	}

	protected void prePersist() {
		super.prePersist();
		setRentals(SpringContext.getBean(RentalService.class).cleanupRentalList(getRentals()));
	}

	protected void preUpdate() {
		super.preUpdate();
		setRentals(SpringContext.getBean(RentalService.class).cleanupRentalList(getRentals()));
	}

	public String getPickListLineId() {
		return this.pickListLineId;
	}

	public void setPickListLineId(String pickListLineId) {
		this.pickListLineId = pickListLineId;
	}

	public PickTicket getPickTicket() {
		return this.pickTicket;
	}

	public void setPickTicket(PickTicket PickTicket) {
		this.pickTicket = PickTicket;
	}

	public PickListDocument getPickListDocument() {
		return pickListDocument;
	}

	public void setPickListDocument(PickListDocument pickListDocument) {
		this.pickListDocument = pickListDocument;
	}

	public String getStockId() {
		return this.stockId;
	}

	public void setStockId(String stockId) {
		this.stockId = stockId;
	}

	//BEGIN OJB
	public void setPickTicketNumber(String PickTicketNumber) {
		this.pickTicketNumber = PickTicketNumber;
	}

	public String getPickTicketNumber() {
		return pickTicketNumber;
	}

	public String getPickListDocumentNumber() {
		return pickListDocumentNumber;
	}

	public void setPickListDocumentNumber(String pickListDocumentNumber) {
		this.pickListDocumentNumber = pickListDocumentNumber;
	}

	public String getPickStatusCodeCd() {
		return pickStatusCodeCd;
	}

	public void setPickStatusCodeCd(String pickStatusCodeCd) {
		this.pickStatusCodeCd = pickStatusCodeCd;
	}

	public Integer getSalesInstanceId() {
		return salesInstanceId;
	}

	public void setOrderDetailId(Integer orderDetailId) {
		this.orderDetailId = orderDetailId;
	}

	public Integer getOrderDetailId() {
		return orderDetailId;
	}

	public void setSalesInstanceId(Integer salesInstanceId) {
		this.salesInstanceId = salesInstanceId;
	}

	public String getRouteCd() {
		return this.routeCd;
	}

	public void setRouteCd(String routeCd) {
		this.routeCd = routeCd;
	}

	public String getBackOrderId() {
		return this.backOrderId;
	}

	public void setBackOrderId(String backOrderId) {
		this.backOrderId = backOrderId;
	}
	//END OJB

	public PickStatusCode getPickStatusCode() {
		return this.pickStatusCode;
	}

	public void setPickStatusCode(PickStatusCode pickStatusCode) {
		this.pickStatusCode = pickStatusCode;
	}

	public SalesInstance getSalesInstance() {
		return this.salesInstance;
	}

	public void setSalesInstance(SalesInstance salesInstance) {
		this.salesInstance = salesInstance;
	}

	public void setOrderDetail(OrderDetail orderDetail) {
		this.orderDetail = orderDetail;
	}

	public OrderDetail getOrderDetail() {
		return orderDetail;
	}

	public Integer getPickTubNbr() {
		return this.pickTubNbr;
	}

	public void setPickTubNbr(Integer pickTubNbr) {
		this.pickTubNbr = pickTubNbr;
	}

	public Integer getOrderLineNbr() {
		return this.orderLineNbr;
	}

	public void setOrderLineNbr(Integer orderLineNbr) {
		this.orderLineNbr = orderLineNbr;
	}

	public Integer getBinId() {
		return this.binId;
	}

	public void setBinId(Integer binId) {
		this.binId = binId;
	}

	public void setBin(Bin bin) {
		this.bin = bin;
	}

	public Bin getBin() {
		return bin;
	}

	public void setRoute(Route route) {
		this.route = route;
	}

	public Route getRoute() {
		return route;
	}

	public void setBackOrder(BackOrder backOrder) {
		this.backOrder = backOrder;
	}

	public BackOrder getBackOrder() {
		return backOrder;
	}

	public Integer getStockQty() {
		return this.stockQty;
	}

	public void setStockQty(Integer stockQty) {
		this.stockQty = stockQty;
	}

	public Integer getPickStockQty() {
		return this.pickStockQty;
	}

	public void setPickStockQty(Integer pickStockQty) {
		this.pickStockQty = pickStockQty;
	}

	public Integer getBackOrderQty() {
		return this.backOrderQty;
	}

	public void setBackOrderQty(Integer backOrderQty) {
		this.backOrderQty = backOrderQty;
	}

	public void setCreatedDate(Timestamp createdDate) {
		this.createdDate = createdDate;
	}

	public Timestamp getCreatedDate() {
		return createdDate;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	public Stock getStock() {
		return stock;
	}
	
	/**
	 * @return the total pickStockQty for this item and any additionalLines
	 */
	public Integer getTotalPickStockQty() {
        Integer qtyPicked = this.getPickStockQty();
        for(PickListLine addLine : this.getAdditionalLines()) {
            qtyPicked += addLine.getPickStockQty();
        }
        return qtyPicked;
	}

	/**
	 * @return String value of location as a compilation of Warehouse / Zone / Bin / Shelf / Shelf number
	 */
	public String getItemLocation() {
	    if(ObjectUtils.isNull(getBin()) && getBinId() != null)
	        this.refreshReferenceObject(MMConstants.PickListLine.BIN);
	    if(ObjectUtils.isNotNull(getBin())
	            && ObjectUtils.isNull(getBin().getZone()) 
	            && StringUtils.isNotBlank(getBin().getZoneId())) {
	        this.getBin().refreshReferenceObject(MMConstants.Bin.ZONE);
	    }
	    
	    String location = getBin().getZone().getWarehouseCd() + " / ";
		location += getBin().getZone().getZoneCd() + " / ";
		location += getBin().getBinNbr() + " / ";
		location += getBin().getShelfId() + " / ";
		location += getBin().getShelfIdNbr();
		return location;
	}

	public boolean isTrackableWithSerialNumber() {
		return SpringContext.getBean(StockService.class).isTrackableWithSerialNumber(this.getStock());
	}


	public void setRentals(List<Rental> rental) {
		this.rentals = rental;
	}

	public List<Rental> getRentals() {
		return rentals;
	}

    public void setAdditionalLines(List<PickListLine> additionalLines) {
        this.additionalLines = additionalLines;
    }

    public List<PickListLine> getAdditionalLines() {
        return additionalLines;
    }

    @Override
    public Object clone()  {
        try
        {
            return super.clone();
        }
        catch (CloneNotSupportedException e)
        {
            throw new InternalError(e.toString());
        }
    }

    /**
     * Gets the chargeDocumentNumber property
     * @return Returns the chargeDocumentNumber
     */
    public String getChargeDocumentNumber() {
        return this.chargeDocumentNumber;
    }

    /**
     * Sets the chargeDocumentNumber property value
     * @param chargeDocumentNumber The chargeDocumentNumber to set
     */
    public void setChargeDocumentNumber(String chargeDocumentNumber) {
        this.chargeDocumentNumber = chargeDocumentNumber;
    }

    public void setChargeDocumentItemNumber(Integer chargeDocumentItemNumber) {
        this.chargeDocumentItemNumber = chargeDocumentItemNumber;
    }

    public Integer getChargeDocumentItemNumber() {
        return chargeDocumentItemNumber;
    }

    /**
     * Gets the verifyDate property
     * @return Returns the verifyDate
     */
    public Timestamp getVerifyDate() {
        return this.verifyDate;
    }

    /**
     * Sets the verifyDate property value
     * @param verifyDate The verifyDate to set
     */
    public void setVerifyDate(Timestamp verifyDate) {
        this.verifyDate = verifyDate;
    }


}
