package org.kuali.ext.mm.businessobject;

// Generated May 11, 2009 11:03:40 AM by Hibernate Tools 3.2.4.GA

import java.util.LinkedHashMap;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PickStatusCode generated by hbm2java
 */
@Entity
@Table(name = "MM_PICK_STATUS_CODE_T")
public class PickStatusCode extends MMPersistableBusinessObjectBase {

	/**
     *
     */
    private static final long serialVersionUID = 6951545393415884991L;

    @Id
	@Column(name = "PICK_STATUS_CD", unique = true, nullable = false, length = 4)
	private String pickStatusCode;

	@Column(name = "NM", nullable = false, length = 45)
	private String pickStatusCodeName;

	public PickStatusCode() {
	}

	public String getPickStatusCode() {
		return this.pickStatusCode;
	}

	public void setPickStatusCode(String pickStatusCode) {
		this.pickStatusCode = pickStatusCode;
	}

	public String getPickStatusCodeName() {
		return this.pickStatusCodeName;
	}

	public void setPickStatusCodeName(String pickStatusCodeName) {
		this.pickStatusCodeName = pickStatusCodeName;
	}

	/**
	 * toStringMapper
	 * @return LinkedHashMap
	 */
	@Override
    public LinkedHashMap toStringMapper() {
		LinkedHashMap propMap = new LinkedHashMap();
		//TODO:  Autogenerated method

		return propMap;
	}

}
