package org.kuali.ext.mm.businessobject;

// Generated Apr 7, 2009 1:12:56 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Profile generated by hbm2java
 */
@Entity
@Table(name = "MM_PROFILE_T")
public class Profile extends MMPersistableBusinessObjectBase {

	private static final long serialVersionUID = 5207582589680778340L;

	@Column(name = "PROFILE_ID", nullable = false, length = 18)
	private String profileId;

	@Column(name = "CUSTOMER_PRNCPL_ID", nullable = false, length = 12)
	private String principalName;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER_PRNCPL_NM", nullable = false, insertable = false, updatable = false)
	private Customer customer;

	@Column(name = "PROFILE_NM", nullable = false, length = 40)
	private String profileName;

	@Column(name = "PROFILE_EMAIL", nullable = false, length = 200)
	private String profileEmail;

	@Column(name = "PROFILE_PHONE_NBR", nullable = false, length = 200)
	private String profilePhoneNumber;

	@Column(name = "DELIVERY_BUILDING_CD", length = 4)
	private String deliveryBuildingCode;

	@Column(name = "DELIVERY_BUILDING_RM_NBR", length = 8)
	private String deliveryBuildingRoomNumber;

	@Column(name = "BILLING_BUILDING_CD", length = 4)
	private String billingBuildingCode;

	@Column(name = "CAMPUS_CD", length = 2)
	private String campusCode;

	@Column(name = "FIN_COA_CD", length = 2)
	private String finacialChartOfAccountsCode;

	@Column(name = "ACCOUNT_NBR", length = 7)
	private String accountNumber;

	@Column(name = "SUB_ACCOUNT_NBR", length = 5)
	private String subAccountNumber;

	private String organizationCode;

	private String projectCode;

	@Column(name = "PROFILE_DEFAULT_IND")
	private boolean profileDefaultIndicator;

	private boolean notifyIndicator;

	private boolean personalUseIndicator;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profileId")
	private List<Address> addresses = new ArrayList<Address>();

	@Transient
	private List<ShoppingCart> savedShoppingCarts = new ArrayList<ShoppingCart>();

	//BEGIN OJB
	public String getPrincipalName() {
		return this.principalName;
	}

	public void setPrincipalName(String principalName) {
		this.principalName = principalName;
	}
	//END OJB

	public String getProfileId() {
		return this.profileId;
	}

	public void setProfileId(String profileId) {
		this.profileId = profileId;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}
	public String getProfileName() {
		return profileName;
	}

	public void setProfileName(String profileName) {
		this.profileName = profileName;
	}

	public String getProfileEmail() {
		return profileEmail;
	}

	public void setProfileEmail(String profileEmail) {
		this.profileEmail = profileEmail;
	}

	public void setProfilePhoneNumber(String profilePhoneNumber) {
		this.profilePhoneNumber = profilePhoneNumber;
	}

	public String getProfilePhoneNumber() {
		return profilePhoneNumber;
	}

	public String getDeliveryBuildingCode() {
		return this.deliveryBuildingCode;
	}

	public void setDeliveryBuildingCode(String deliveryBuildingCode) {
		this.deliveryBuildingCode = deliveryBuildingCode;
	}

	public String getDeliveryBuildingRoomNumber() {
		return this.deliveryBuildingRoomNumber;
	}

	public void setDeliveryBuildingRoomNumber(String deliveryBuildingRoomNumber) {
		this.deliveryBuildingRoomNumber = deliveryBuildingRoomNumber;
	}

	public String getBillingBuildingCode() {
		return this.billingBuildingCode;
	}

	public void setBillingBuildingCode(String billingBuildingCode) {
		this.billingBuildingCode = billingBuildingCode;
	}

	public String getCampusCode() {
		return this.campusCode;
	}

	public void setCampusCode(String campusCode) {
		this.campusCode = campusCode;
	}

	public String getFinacialChartOfAccountsCode() {
		return this.finacialChartOfAccountsCode;
	}

	public void setFinacialChartOfAccountsCode(String finacialChartOfAccountsCode) {
		this.finacialChartOfAccountsCode = finacialChartOfAccountsCode;
	}

	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	public String getSubAccountNumber() {
		return this.subAccountNumber;
	}

	public void setSubAccountNumber(String subAccountNumber) {
		this.subAccountNumber = subAccountNumber;
	}

	public void setOrganizationCode(String organizationCode) {
		this.organizationCode = organizationCode;
	}

	public String getOrganizationCode() {
		return organizationCode;
	}

	public void setProjectCode(String projectCode) {
		this.projectCode = projectCode;
	}

	public String getProjectCode() {
		return projectCode;
	}

	public boolean isProfileDefaultIndicator() {
		return profileDefaultIndicator;
	}

	public void setProfileDefaultIndicator(boolean profileDefaultIndicator) {
		this.profileDefaultIndicator = profileDefaultIndicator;
	}

	public void setNotifyIndicator(boolean notifyIndicator) {
		this.notifyIndicator = notifyIndicator;
	}

	public boolean isNotifyIndicator() {
		return notifyIndicator;
	}

	public void setPersonalUseIndicator(boolean personalUseIndicator) {
		this.personalUseIndicator = personalUseIndicator;
	}

	public boolean isPersonalUseIndicator() {
		return personalUseIndicator;
	}

	public void setAddresses(List<Address> addresses) {
		this.addresses = addresses;
	}

	public List<Address> getAddresses() {
		return addresses;
	}

	public void setSavedShoppingCarts(List<ShoppingCart> savedShoppingCarts) {
		this.savedShoppingCarts = savedShoppingCarts;
	}

	public List<ShoppingCart> getSavedShoppingCarts() {
		return savedShoppingCarts;
	}





}
