package org.kuali.ext.mm.businessobject;

// Generated Jul 13, 2009 9:05:12 AM by Hibernate Tools 3.2.4.GA

import org.kuali.ext.mm.document.OrderDocument;

import javax.persistence.*;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;

/**
 * RecurringOrder generated by hbm2java
 */
@Entity
@Table(name = "MM_RECURRING_ORDER_T")
public class RecurringOrder extends MMPersistableBusinessObjectBase  {

	/**
     *
     */
    private static final long serialVersionUID = 5939144358046654403L;

    @Id
	@Column(name = "RECURRING_ORDER_ID", unique = true, nullable = false, precision = 8, scale = 0)
	private Integer recurringOrderId;

	@Column(name = "TIMES_PER_YR", precision = 8, scale = 0)
	private Integer timesPerYr;

	@Column(name = "NO_END_DATE_IND", nullable = false, length = 1)
	private boolean noEndDateInd;
	@Temporal(TemporalType.DATE)
	@Column(name = "START_DT", nullable = false, length = 7)
	private Date startDt;
	@Temporal(TemporalType.DATE)
	@Column(name = "END_DT", length = 7)
	private Date endDt;
	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_RECURRING_DT", length = 7)
	private Date lastRecurringDt;
	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_RECURRING_DT", length = 7)
	private Date nextRecurringDt;

	private List<OrderDocument> ordersCreated = new ArrayList<OrderDocument>();

	public RecurringOrder() {
	}

	public Integer getRecurringOrderId() {
		return this.recurringOrderId;
	}

	public void setRecurringOrderId(Integer recurringOrderId) {
		this.recurringOrderId = recurringOrderId;
	}

	public Integer getTimesPerYr() {
		return this.timesPerYr;
	}

	public void setTimesPerYr(Integer timesPerYr) {
		this.timesPerYr = timesPerYr;
	}

	public boolean isNoEndDateInd() {
		return this.noEndDateInd;
	}

	public void setNoEndDateInd(boolean noEndDateInd) {
		this.noEndDateInd = noEndDateInd;
	}

	public Date getStartDt() {
		return this.startDt;
	}

	public void setStartDt(Date startDt) {
		this.startDt = startDt;
	}

	public Date getEndDt() {
		return this.endDt;
	}

	public void setEndDt(Date endDt) {
		this.endDt = endDt;
	}

	public Date getLastRecurringDt() {
		return this.lastRecurringDt;
	}

	public void setLastRecurringDt(Date lastRecurringDt) {
		this.lastRecurringDt = lastRecurringDt;
	}

	public void setNextRecurringDt(Date nextRecurringDt) {
		this.nextRecurringDt = nextRecurringDt;
	}

	public Date getNextRecurringDt() {
		return nextRecurringDt;
	}


	public void setOrdersCreated(List<OrderDocument> ordersCreated) {
		this.ordersCreated = ordersCreated;
	}

	public List<OrderDocument> getOrdersCreated() {
		return ordersCreated;
	}

}
