package org.kuali.ext.mm.businessobject;

// Generated Apr 13, 2009 2:30:37 PM by Hibernate Tools 3.2.4.GA

import java.util.LinkedHashMap;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ReturnType generated by hbm2java
 */
@Entity
@Table(name = "MM_RETURN_TYPE_T")
public class ReturnType extends MMPersistableBusinessObjectBase implements
		java.io.Serializable {

	private static final long serialVersionUID = -4728928939576660223L;

	@Id
	@Column(name = "RETURN_TYPE_CD", unique = true, nullable = false, length = 8)
	private String returnTypeCode;

	@Column(name = "NM", length = 45)
	private String returnTypeName;

	public ReturnType() {
	}

	public String getReturnTypeCode() {
		return this.returnTypeCode;
	}

	public void setReturnTypeCode(String returnTypeCode) {
		this.returnTypeCode = returnTypeCode;
	}

	public String getReturnTypeName() {
		return this.returnTypeName;
	}

	public void setReturnTypeName(String returnTypeName) {
		this.returnTypeName = returnTypeName;
	}

	/**
	 * toStringMapper
	 * @return LinkedHashMap
	 */
	@Override
    public LinkedHashMap toStringMapper() {
		LinkedHashMap propMap = new LinkedHashMap();
		//TODO:  Autogenerated method

		return propMap;
	}

}
