package org.kuali.ext.mm.businessobject;

// Generated Jul 13, 2009 9:05:12 AM by Hibernate Tools 3.2.4.GA

import org.kuali.ext.mm.common.sys.MMConstants;
import org.kuali.ext.mm.util.MMDecimal;
import org.kuali.rice.core.api.util.type.KualiDecimal;
import org.kuali.rice.krad.util.ObjectUtils;

import javax.persistence.*;


/**
 * ShopCartDetail generated by hbm2java
 */
@Entity
@Table(name = "MM_SHOP_CART_DETAIL_T")
public class ShopCartDetail extends MMPersistableBusinessObjectBase  {

	/**
     *
     */
    private static final long serialVersionUID = -4427746436930574753L;
    @Id
	@Column(name = "SHOP_CART_DETAIL_ID", unique = true, nullable = false, length = 36)
	private String shopCartDetailId;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SHOP_CART_DOC_NBR", nullable = false)
	private ShoppingCart shoppingCart;

	@Transient
	private Integer shopCartLineNbr;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CATALOG_ITEM_ID", nullable = false)
	private CatalogItem catalogItem;

	@Column(name = "CATALOG_ITEM_ID", nullable = false, length = 36)
	private String catalogItemId;

	@Column(name = "SHOP_CART_DOC_NBR", nullable = false)
	private String shoppingCartId;

	@Column(name = "WILLCALL_IND", length = 1)
	private boolean willcallInd;

	@Column(name = "SHOP_CART_ITEM_QTY", nullable = false, precision = 11, scale = 4)
	private Integer shopCartItemQty;

	@Column(name = "ITEM_UNIT_OF_ISSUE_CD", nullable = false, length = 10)
	private String itemUnitOfIssueCd;
	
	private String distributorNumber;
	
	private String supplierPartAuxId;

	@Column(name = "SHOP_CART_ITEM_COST_AMT", nullable = false, scale = 4)
	private MMDecimal shopCartItemCostAmt;

	@Column(name = "SHOP_CART_ITEM_PRICE_AMT", nullable = false, scale = 4)
	private MMDecimal shopCartItemPriceAmt;

	@Column(name = "SHOP_CART_ITEM_MARKUP_AMT", nullable = false, scale = 4)
	private MMDecimal shopCartItemMarkupAmt;

	@Column(name = "SHOP_CART_ITEM_TAX_AMT", nullable = false, scale = 4)
	private MMDecimal shopCartItemTaxAmt;

	private MMDecimal shopCartItemAdditionalCostAmt;

	@Column(name = "SHOP_CART_ITEM_DETAIL_DESC", nullable = false, length = 4000)
	private String shopCartItemDetailDesc;

	@Column(name = "MANUFACTURER_NBR", nullable = false, length = 30)
	private String manufacturerNbr;

	@Column(name = "SHIPPING_WGT", precision = 8)
	private KualiDecimal shippingWgt;

	@Column(name = "SHIPPING_HT", precision = 8)
	private KualiDecimal shippingHt;

	@Column(name = "SHIPPING_WD", precision = 8)
	private KualiDecimal shippingWd;

	@Column(name = "SHIPPING_LH", precision = 8)
	private KualiDecimal shippingLh;

	@Column(name = "WAREHOUSE_CD", length = 2)
	private String warehouseCd;

	@Column(name = "VENDOR_HEADER_GENERATED_ID", precision = 10, scale = 0)
	private Integer vendorHeaderGeneratedId;

	@Column(name = "VENDOR_DETAIL_ASSIGNED_ID", precision = 10, scale = 0)
	private Integer vendorDetailAssignedId;

	@Column(name = "VENDOR_NM", length = 45)
	private String vendorNm;
	
	@Transient
	private boolean fromPunchOut;
	
	@Transient
    private String cxmlPayloadId;

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shopCartDetail")
//	private Set<ShopCartDtlAddlCost> shopCartDtlAddlCosts = new HashSet<ShopCartDtlAddlCost>(
//			0);

	public String getShopCartDetailId() {
		return this.shopCartDetailId;
	}

	public void setShopCartDetailId(String shopCartDetailId) {
		this.shopCartDetailId = shopCartDetailId;
	}

	public ShoppingCart getShoppingCart() {
		return this.shoppingCart;
	}

	public void setShoppingCart(ShoppingCart shoppingCart) {
		this.shoppingCart = shoppingCart;
	}

	public String getShoppingCartId() {
		return shoppingCartId;
	}

	public void setShoppingCartId(String shoppingCartId) {
		this.shoppingCartId = shoppingCartId;
	}

	public Integer getShopCartLineNbr() {
		return this.shopCartLineNbr;
	}

	public void setShopCartLineNbr(Integer shopCartLineNbr) {
		this.shopCartLineNbr = shopCartLineNbr;
	}

	public void setCatalogItem(CatalogItem catalogItem) {
		this.catalogItem = catalogItem;
	}

	public CatalogItem getCatalogItem() {
		return catalogItem;
	}

	public String getCatalogItemId() {
		return this.catalogItemId;
	}

	public void setCatalogItemId(String catalogItemId) {
		this.catalogItemId = catalogItemId;
	}

	public boolean isWillcallInd() {
		return this.willcallInd;
	}

	public void setWillcallInd(boolean willcallInd) {
		this.willcallInd = willcallInd;
	}

	public Integer getShopCartItemQty() {
		return this.shopCartItemQty;
	}

	public void setShopCartItemQty(Integer shopCartItemQty) {
		this.shopCartItemQty = shopCartItemQty;
	}

	public String getItemUnitOfIssueCd() {
		return this.itemUnitOfIssueCd;
	}

	public void setItemUnitOfIssueCd(String itemUnitOfIssueCd) {
		this.itemUnitOfIssueCd = itemUnitOfIssueCd;
	}

	public void setDistributorNumber(String distributorNumber) {
        this.distributorNumber = distributorNumber;
    }

    public String getDistributorNumber() {
        return distributorNumber;
    }

    public void setSupplierPartAuxId(String supplierPartAuxId) {
        this.supplierPartAuxId = supplierPartAuxId;
    }

    public String getSupplierPartAuxId() {
        return supplierPartAuxId;
    }

    public MMDecimal getShopCartItemCostAmt() {
		return this.shopCartItemCostAmt;
	}

	public void setShopCartItemCostAmt(MMDecimal shopCartItemCostAmt) {
		this.shopCartItemCostAmt = shopCartItemCostAmt;
	}

	public MMDecimal getShopCartItemPriceAmt() {
		return this.shopCartItemPriceAmt;
	}

	public void setShopCartItemPriceAmt(MMDecimal shopCartItemPriceAmt) {
		this.shopCartItemPriceAmt = shopCartItemPriceAmt;
	}

	public MMDecimal getShopCartItemMarkupAmt() {
		return this.shopCartItemMarkupAmt;
	}

	public void setShopCartItemMarkupAmt(MMDecimal shopCartItemMarkupAmt) {
		this.shopCartItemMarkupAmt = shopCartItemMarkupAmt;
	}

	public MMDecimal getShopCartItemTaxAmt() {
		return this.shopCartItemTaxAmt;
	}

	public void setShopCartItemTaxAmt(MMDecimal shopCartItemTaxAmt) {
		this.shopCartItemTaxAmt = shopCartItemTaxAmt;
	}

	public void setShopCartItemAdditionalCostAmt(MMDecimal shopCartItemAdditionalCostAmt) {
		this.shopCartItemAdditionalCostAmt = shopCartItemAdditionalCostAmt;
	}

	public MMDecimal getShopCartItemAdditionalCostAmt() {
		return shopCartItemAdditionalCostAmt;
	}

	public String getShopCartItemDetailDesc() {
		return this.shopCartItemDetailDesc;
	}

	public void setShopCartItemDetailDesc(String shopCartItemDetailDesc) {
		this.shopCartItemDetailDesc = shopCartItemDetailDesc;
	}

	public String getManufacturerNbr() {
		return this.manufacturerNbr;
	}

	public void setManufacturerNbr(String manufacturerNbr) {
		this.manufacturerNbr = manufacturerNbr;
	}

	public KualiDecimal getShippingWgt() {
		return this.shippingWgt;
	}

	public void setShippingWgt(KualiDecimal shippingWgt) {
		this.shippingWgt = shippingWgt;
	}

	public KualiDecimal getShippingHt() {
		return this.shippingHt;
	}

	public void setShippingHt(KualiDecimal shippingHt) {
		this.shippingHt = shippingHt;
	}

	public KualiDecimal getShippingWd() {
		return this.shippingWd;
	}

	public void setShippingWd(KualiDecimal shippingWd) {
		this.shippingWd = shippingWd;
	}

	public KualiDecimal getShippingLh() {
		return this.shippingLh;
	}

	public void setShippingLh(KualiDecimal shippingLh) {
		this.shippingLh = shippingLh;
	}

	public String getWarehouseCd() {
		return this.warehouseCd;
	}

	public void setWarehouseCd(String warehouseCd) {
		this.warehouseCd = warehouseCd;
	}

	public Integer getVendorHeaderGeneratedId() {
		return this.vendorHeaderGeneratedId;
	}

	public void setVendorHeaderGeneratedId(Integer vendorHeaderGeneratedId) {
		this.vendorHeaderGeneratedId = vendorHeaderGeneratedId;
	}

	public Integer getVendorDetailAssignedId() {
		return this.vendorDetailAssignedId;
	}

	public void setVendorDetailAssignedId(Integer vendorDetailAssignedId) {
		this.vendorDetailAssignedId = vendorDetailAssignedId;
	}

	public String getVendorNm() {
		return this.vendorNm;
	}

	public void setVendorNm(String vendorNm) {
		this.vendorNm = vendorNm;
	}

//
//	public Set<ShopCartDtlAddlCost> getShopCartDtlAddlCosts() {
//		return this.shopCartDtlAddlCosts;
//	}
//
//	public void setShopCartDtlAddlCosts(
//			Set<ShopCartDtlAddlCost> shopCartDtlAddlCosts) {
//		this.shopCartDtlAddlCosts = shopCartDtlAddlCosts;
//	}

    public void setFromPunchOut(boolean fromPunchOut) {
        this.fromPunchOut = fromPunchOut;
    }

    public boolean isFromPunchOut() {
        return fromPunchOut;
    }

    public void setCxmlPayloadId(String cxmlPayloadId) {
        this.cxmlPayloadId = cxmlPayloadId;
    }

    public String getCxmlPayloadId() {
        return cxmlPayloadId;
    }
    
    public boolean isTrueBuyout() {
        if(ObjectUtils.isNull(this.getCatalogItem()) 
                || ObjectUtils.isNull(this.getCatalogItem().getCatalog()))
            return false;
        
        return MMConstants.CatalogType.TRUE_BUYOUT.equals(this.getCatalogItem().getCatalog().getCatalogTypeCd());
    }



}
