package org.kuali.ext.mm.businessobject;

// Generated Apr 16, 2009 10:01:00 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

/**
 * ShopCartHeader generated by hbm2java
 */
@Entity
@Table(name = "MM_SHOP_CART_HEADER_T")
public class ShopCartHeader extends MMPersistableBusinessObjectBase implements
		java.io.Serializable {

	private static final long serialVersionUID = 6743306810253601203L;
	/* BEGIN JPA
	   @EmbeddedId

	   @AttributeOverrides( {
	       @AttributeOverride(name="customerId", column=@Column(name="CUSTOMER_ID", nullable=false, length=12) ),
	       @AttributeOverride(name="shopCartId", column=@Column(name="SHOP_CART_ID", nullable=false, length=12) ) } )
	private ShopCartHeaderId id;
	END JPA */
	//BEGIN OJB
	@Id
	@Column(name = "CUSTOMER_ID", nullable = false, length = 12)
	private String customerId;
	@Id
	@Column(name = "SHOP_CART_ID", nullable = false, length = 12)
	private String shopCartId;
	//END OJB
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER_ID", nullable = false, insertable = false, updatable = false)
	private Customer customer;

	@Column(name = "SHOP_CART_HEADER_NM", nullable = false, length = 40)
	private String shopCartHeaderNm;

	@Column(name = "DELIVERY_BUILDING_CD", length = 4)
	private String deliveryBuildingCd;

	@Column(name = "DELIVERY_BUILDING_RM_NBR", length = 8)
	private String deliveryBuildingRmNbr;

	@Column(name = "DELIVERY_INSTRUCTION_TXT")
	private String deliveryInstructionTxt;

	@Column(name = "BILLING_BUILDING_CD", length = 4)
	private String billingBuildingCd;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shopCartHeader")
	private List<Accounts> accountses = new ArrayList<Accounts>();
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shopCartHeader")
	private List<ShopCartDetail> shopCartDetails = new ArrayList<ShopCartDetail>();

	public ShopCartHeader() {
	}

	/* BEGIN JPA
	 public ShopCartHeaderId getId() {
	 return this.id;
	 }

	 public void setId(ShopCartHeaderId id) {
	 this.id = id;
	 }
	 END JPA */
	//BEGIN OJB
	public String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	public String getShopCartId() {
		return this.shopCartId;
	}

	public void setShopCartId(String shopCartId) {
		this.shopCartId = shopCartId;
	}

	//END OJB
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getShopCartHeaderNm() {
		return this.shopCartHeaderNm;
	}

	public void setShopCartHeaderNm(String shopCartHeaderNm) {
		this.shopCartHeaderNm = shopCartHeaderNm;
	}

	public String getDeliveryBuildingCd() {
		return this.deliveryBuildingCd;
	}

	public void setDeliveryBuildingCd(String deliveryBuildingCd) {
		this.deliveryBuildingCd = deliveryBuildingCd;
	}

	public String getDeliveryBuildingRmNbr() {
		return this.deliveryBuildingRmNbr;
	}

	public void setDeliveryBuildingRmNbr(String deliveryBuildingRmNbr) {
		this.deliveryBuildingRmNbr = deliveryBuildingRmNbr;
	}

	public String getDeliveryInstructionTxt() {
		return this.deliveryInstructionTxt;
	}

	public void setDeliveryInstructionTxt(String deliveryInstructionTxt) {
		this.deliveryInstructionTxt = deliveryInstructionTxt;
	}

	public String getBillingBuildingCd() {
		return this.billingBuildingCd;
	}

	public void setBillingBuildingCd(String billingBuildingCd) {
		this.billingBuildingCd = billingBuildingCd;
	}

	public List<Accounts> getAccountses() {
		return this.accountses;
	}

	public void setAccountses(List<Accounts> accountses) {
		this.accountses = accountses;
	}

	public List<ShopCartDetail> getShopCartDetails() {
		return this.shopCartDetails;
	}

	public void setShopCartDetails(List<ShopCartDetail> shopCartDetails) {
		this.shopCartDetails = shopCartDetails;
	}


}
