package org.kuali.ext.mm.businessobject;

import java.sql.Date;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * StockBalance generated by hbm2java
 */
@Entity
@Table(name = "MM_STOCK_BALANCE_T")
public class StockBalance extends StoresPersistableBusinessObject implements java.io.Serializable {

    private static final long serialVersionUID = -6568357829437221149L;

    @Id
    @Column(name = "STOCK_BALANCE_ID", unique = true, nullable = false, length = 36)
    private Integer stockBalanceId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "BIN_ID", nullable = false)
    private BinLookable binLookable;

    private Bin bin;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STOCK_ID", nullable = false)
    private Stock stock;

    @Column(name = "BIN_ID", unique = true, nullable = false, length = 18)
    private Integer binId;

    private String zoneId;

    @Column(name = "STOCK_ID", unique = true, nullable = false, length = 36)
    private String stockId;

    @Column(name = "QTY_ON_HAND", nullable = false, precision = 8, scale = 0)
    private Integer qtyOnHand = new Integer("0");

    @Temporal(TemporalType.DATE)
    @Column(name = "LAST_CHECKIN_DT", length = 7)
    private Date lastCheckinDt;

    @Column(name = "STOCK_PERISHABLE_DT", length = 10)
    private Date stockPerishableDt;

    @Transient
    private String quantityBeingAdjusted;

    @Transient
    private String quantityBeingAdjustedFromOldToNew;

    @Transient
    private Integer transferSourceBinId;

    // private Integer oldQtyOnHand = new Integer(0);

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "stockBalance")
    private Set<StockHistory> stockHistories = new HashSet<StockHistory>(0);

    @Transient
    private StockTransReason stockTransReason;
    
    private transient boolean unassign;
    
    public StockBalance() {
        stockTransReason = new StockTransReason();
    }

    public StockBalance(StockBalance stockBalance) {
        this.stockBalanceId = stockBalance.getStockBalanceId();
        this.versionNumber = stockBalance.getVersionNumber();
        this.setObjectId(stockBalance.getObjectId());
        this.stockId = stockBalance.getStockId();
        this.stock = stockBalance.getStock();
        this.qtyOnHand = stockBalance.getQtyOnHand();
        this.binId = stockBalance.getBinId();
        this.bin = stockBalance.getBin();
        this.lastCheckinDt = stockBalance.getLastCheckinDt();
        this.lastUpdateDate = stockBalance.getLastUpdateDate();
    }
    
    public void addItemQuantityToBin(Integer qty) {
        this.qtyOnHand = this.qtyOnHand + qty;
    }

    public Bin getBin() {
        return this.bin;
    }

    public Integer getBinAvailableQuantity() {
        return this.bin.getAvailableQty();
    }

    public Integer getBinId() {
        return binId;
    }

    public BinLookable getBinLookable() {
        return binLookable;
    }

    public Date getLastCheckinDt() {
        return this.lastCheckinDt;
    }

    public Integer getQtyOnHand() {
        return this.qtyOnHand;
    }

    public String getQuantityBeingAdjusted() {
        return this.quantityBeingAdjusted;
    }

    public String getQuantityBeingAdjustedFromOldToNew() {
        return this.quantityBeingAdjustedFromOldToNew;
    }

    public Stock getStock() {
        return this.stock;
    }

    public Integer getStockBalanceId() {
        return this.stockBalanceId;
    }

    public Set<StockHistory> getStockHistories() {
        return this.stockHistories;
    }

    public String getStockId() {
        return stockId;
    }

    public String getStockLocation() {
        return binLookable.getBinNbr() + "/" + binLookable.getShelfId() + "/"
                + binLookable.getShelfIdNbr() + "/" + binLookable.getZone().getZoneCd() + "/"
                + binLookable.getZone().getWarehouseCd();
    }

    public Date getStockPerishableDt() {
        return stockPerishableDt;
    }

    public StockTransReason getStockTransReason() {
        return stockTransReason;
    }

    public Integer getTransferSourceBinId() {
        return transferSourceBinId;
    }

    public Zone getZone() {
        return this.bin.getZone();
    }

    public String getZoneId() {
        return zoneId;
    }

    public boolean isBinFull() {
        return this.qtyOnHand >= this.getBin().getMaximumShelfQty();
    }

    public void setBin(Bin bin) {
        this.bin = bin;
    }

    public void setBinId(Integer binId) {
        this.binId = binId;
    }

    public void setBinLookable(BinLookable binLookable) {
        this.binLookable = binLookable;
    }

    public void setLastCheckinDt(Date lastCheckinDt) {
        this.lastCheckinDt = lastCheckinDt;
    }

    public void setQtyOnHand(Integer qtyOnHand) {
        this.qtyOnHand = qtyOnHand;
    }

    public void setQuantityBeingAdjusted(String quantityBeingAdjusted) {
        this.quantityBeingAdjusted = quantityBeingAdjusted;
    }


    public void setQuantityBeingAdjustedFromOldToNew(String quantityBeingAdjustedFromOldToNew) {
        this.quantityBeingAdjustedFromOldToNew = quantityBeingAdjustedFromOldToNew;
    }

    public void setStock(Stock stock) {
        this.stock = stock;
    }
    
    public void setStockBalanceId(Integer stockBalanceId) {
        this.stockBalanceId = stockBalanceId;
    }

    public void setStockHistories(Set<StockHistory> stockHistories) {
        this.stockHistories = stockHistories;
    }

    public void setStockId(String stockId) {
        this.stockId = stockId;
    }

    public void setStockPerishableDt(Date stockPerishableDt) {
        this.stockPerishableDt = stockPerishableDt;
    }

    public void setStockTransReason(StockTransReason stockTransReason) {
        this.stockTransReason = stockTransReason;
    }

    public void setTransferSourceBinId(Integer transferSourceBinId) {
        this.transferSourceBinId = transferSourceBinId;
    }

    public void setZoneId(String zoneId) {
        this.zoneId = zoneId;
    }

    @Override
    public String toString() {
        return "StockBalance [binId=" + binId + ", lastCheckinDt=" + lastCheckinDt + ", qtyOnHand="
                + qtyOnHand + ", stock=" + stock + ", stockBalanceId=" + stockBalanceId
                + ", stockHistories=" + stockHistories + ", stockId=" + stockId
                + ", stockPerishableDt=" + stockPerishableDt + ", stockTransReason="
                + stockTransReason + ", zoneId=" + zoneId + "]";
    }

    /**
     * toStringMapper
     * 
     * @return LinkedHashMap
     */
    @Override
    public LinkedHashMap toStringMapper() {
        LinkedHashMap propMap = new LinkedHashMap();
        // TODO: Autogenerated method

        return propMap;
    }

    public boolean isUnassign() {
        return this.unassign;
    }

    public void setUnassign(boolean unassign) {
        this.unassign = unassign;
    }

}
