package org.kuali.ext.mm.businessobject;

// Generated May 11, 2009 11:03:40 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StockAttributeCode generated by hbm2java
 */
@Entity
@Table(name = "MM_STOCK_ATTRIBUTE_CODE_T")
public class StockAttributeCode extends MMPersistableBusinessObjectBase {

	/**
     *
     */
    private static final long serialVersionUID = 7128700883992761856L;

    @Id
	@Column(name = "STOCK_ATTRIBUTE_CD", unique = true, nullable = false, length = 2)
	private String stockAttributeCd;

	@Column(name = "NM", nullable = false, length = 45)
	private String nm;

	public StockAttributeCode() {
	}

	public String getStockAttributeCd() {
		return this.stockAttributeCd;
	}

	public void setStockAttributeCd(String stockAttributeCd) {
		this.stockAttributeCd = stockAttributeCd;
	}

	public String getNm() {
		return this.nm;
	}

	public void setNm(String nm) {
		this.nm = nm;
	}


}
