package org.kuali.ext.mm.businessobject;

import java.sql.Timestamp;
import java.util.LinkedHashMap;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.log4j.Logger;
import org.kuali.ext.mm.util.MMDecimal;

/**
 * StockHistory generated by hbm2java
 */
@Entity
@Table(name = "MM_STOCK_HISTORY_T")
public class StockHistory extends StoresPersistableBusinessObject {
    private static final Logger LOG = Logger.getLogger(StockHistory.class);
    private static final long serialVersionUID = 4629676828439665550L;
    @Id
    @Column(name = "STOCK_HISTORY_ID", unique = true, nullable = false, length = 36)
    private Integer stockHistoryId;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STOCK_TRANS_REASON_CD", nullable = false)
    private StockTransReason stockTransReason;

    // BEGIN OJB
    @Column(name = "STOCK_TRANS_REASON_CD", nullable = false)
    private String stockTransReasonCode;

    @Column(name = "BEFORE_STOCK_QTY", nullable = false, precision = 11, scale = 4)
    private Integer beforeStockQty;

    @Column(name = "BEFORE_STOCK_UNIT_OF_ISSUE_CD", nullable = false, length = 10)
    private String beforeStockUnitOfIssueCd;

    @Column(name = "BEFORE_STOCK_PRC", nullable = false, scale = 4)
    private MMDecimal beforeStockPrc;

    @Column(name = "TRANS_STOCK_QTY", precision = 11, scale = 4)
    private Double transStockQty;

    @Column(name = "TRANS_STOCK_UNIT_OF_ISSUE_CD", length = 10)
    private String transStockUnitOfIssueCd;

    @Column(name = "TRANS_STOCK_PRC", scale = 4)
    private MMDecimal transStockPrc;

    @Column(name = "AFTER_STOCK_QTY", nullable = false, precision = 11, scale = 4)
    private Double afterStockQty;

    @Column(name = "AFTER_STOCK_UNIT_OF_ISSUE_CD", nullable = false, length = 10)
    private String afterStockUnitOfIssueCd;

    @Column(name = "AFTER_STOCK_PRC", nullable = false, scale = 4)
    private MMDecimal afterStockPrc;

    @Column(name = "RESIDUAL_TAG", nullable = true, length = 20)
    private String residualTag;

    public String getResidualTag() {
        return residualTag;
    }

    public void setResidualTag(String residualTag) {
        this.residualTag = residualTag;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "HISTORY_TRANS_TIMESTAMP", nullable = false, length = 11)
    private Timestamp historyTransTimestamp;


    private String checkinDocNbr;

    private String pickVerifyDocNbr;

    private String returnDocNbr;

    private String worksheetCountDocNbr;

    private Integer binId;

    private String stockId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "BIN_ID", nullable = false)
    private BinLookable binLookable;

    private Bin bin;

    private Stock stock;

    public Integer getStockHistoryId() {
        return this.stockHistoryId;
    }

    public void setStockHistoryId(Integer stockHistoryId) {
        this.stockHistoryId = stockHistoryId;
    }

    public StockTransReason getStockTransReason() {
        return this.stockTransReason;
    }

    public void setStockTransReason(StockTransReason stockTransReason) {
        this.stockTransReason = stockTransReason;
    }

    public Integer getBeforeStockQty() {
        return this.beforeStockQty;
    }

    public void setBeforeStockQty(Integer beforeStockQty) {
        this.beforeStockQty = beforeStockQty;
    }

    public String getBeforeStockUnitOfIssueCd() {
        return this.beforeStockUnitOfIssueCd;
    }

    public void setBeforeStockUnitOfIssueCd(String beforeStockUnitOfIssueCd) {
        this.beforeStockUnitOfIssueCd = beforeStockUnitOfIssueCd;
    }

    public MMDecimal getBeforeStockPrc() {
        return this.beforeStockPrc;
    }

    public void setBeforeStockPrc(MMDecimal beforeStockPrc) {
        this.beforeStockPrc = beforeStockPrc;
    }

    public Double getTransStockQty() {
        return this.transStockQty;
    }

    public void setTransStockQty(Double transStockQty) {
        this.transStockQty = transStockQty;
    }

    public String getTransStockUnitOfIssueCd() {
        return this.transStockUnitOfIssueCd;
    }

    public void setTransStockUnitOfIssueCd(String transStockUnitOfIssueCd) {
        this.transStockUnitOfIssueCd = transStockUnitOfIssueCd;
    }

    public MMDecimal getTransStockPrc() {
        return this.transStockPrc;
    }

    public void setTransStockPrc(MMDecimal d) {
        this.transStockPrc = d;
    }

    public Double getAfterStockQty() {
        return afterStockQty;
    }

    public void setAfterStockQty(Double afterStockQty) {
        this.afterStockQty = afterStockQty;
    }

    public String getAfterStockUnitOfIssueCd() {
        return this.afterStockUnitOfIssueCd;
    }

    public void setAfterStockUnitOfIssueCd(String afterStockUnitOfIssueCd) {
        this.afterStockUnitOfIssueCd = afterStockUnitOfIssueCd;
    }

    public MMDecimal getAfterStockPrc() {
        return this.afterStockPrc;
    }

    public void setAfterStockPrc(MMDecimal afterStockPrc) {
        this.afterStockPrc = afterStockPrc;
    }

    public Timestamp getHistoryTransTimestamp() {
        return this.historyTransTimestamp;
    }

    public void setHistoryTransTimestamp(Timestamp historyTransTimestamp) {
        this.historyTransTimestamp = historyTransTimestamp;
    }

    // BEGIN OJB
    public void setStockTransReasonCode(String stockTransReasonCode) {
        this.stockTransReasonCode = stockTransReasonCode;
    }

    public String getStockTransReasonCode() {
        return stockTransReasonCode;
    }

    public String getCheckinDocNbr() {
        return checkinDocNbr;
    }

    public void setCheckinDocNbr(String checkinDocNbr) {
        this.checkinDocNbr = checkinDocNbr;
    }

    public String getPickVerifyDocNbr() {
        return pickVerifyDocNbr;
    }

    public void setPickVerifyDocNbr(String pickVerifyDocNbr) {
        this.pickVerifyDocNbr = pickVerifyDocNbr;
    }

    public String getReturnDocNbr() {
        return returnDocNbr;
    }

    public void setReturnDocNbr(String returnDocNbr) {
        this.returnDocNbr = returnDocNbr;
    }

    public String getWorksheetCountDocNbr() {
        return worksheetCountDocNbr;
    }

    public void setWorksheetCountDocNbr(String worksheetCountDocNbr) {
        this.worksheetCountDocNbr = worksheetCountDocNbr;
    }

    public Integer getBinId() {
        return binId;
    }

    public void setBinId(Integer binId) {
        this.binId = binId;
    }

    public String getStockId() {
        return stockId;
    }

    public void setStockId(String stockId) {
        this.stockId = stockId;
    }

    public Bin getBin() {
        return bin;
    }

    public void setBin(Bin bin) {
        this.bin = bin;
    }

    public Stock getStock() {
        return stock;
    }

    public void setStock(Stock stock) {
        this.stock = stock;
    }


    // END OJB

    public BinLookable getBinLookable() {
        return this.binLookable;
    }

    public void setBinLookable(BinLookable binLookable) {
        this.binLookable = binLookable;
    }

    /**
     * toStringMapper
     * 
     * @return LinkedHashMap
     */
    @Override
    public LinkedHashMap toStringMapper() {
        LinkedHashMap propMap = new LinkedHashMap();
        return propMap;
    }
}
