package org.kuali.ext.mm.businessobject;

import javax.persistence.*;

/**
 * StockAttribute generated by hbm2java
 */
@Entity
@Table(name = "MM_STOCK_ATTRIBUTE_T")
public class StockAttribute extends MMPersistableBusinessObjectBase {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "STOCK_ATTRIBUTE_ID", unique = true, nullable = false, length = 36)
	private String stockAttributeId;

	public String getStockAttributeId() {
		return this.stockAttributeId;
	}

	public void setStockAttributeId(String stockAttributeId) {
		this.stockAttributeId = stockAttributeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STOCK_ATTRIBUTE_CD", nullable = false)
	private StockAttributeCode stockAttributeCode;

	public StockAttributeCode getStockAttributeCode() {
		return this.stockAttributeCode;
	}

	public void setStockAttributeCode(StockAttributeCode stockAttributeCode) {
		this.stockAttributeCode = stockAttributeCode;
	}

	@Column(name = "STOCK_ATTRIBUTE_CD")
	private String stockAttributeCd;

	public String getStockAttributeCd() {
		return stockAttributeCd;
	}

	public void setStockAttributeCd(String stockAttributeCd) {
		this.stockAttributeCd = stockAttributeCd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STOCK_ID", nullable = false)
	private Stock stock;

	@Column(name = "STOCK_ID", unique = true, nullable = false, length = 36)
	private String stockId;

	public Stock getStock() {
		return stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	public String getStockId() {
		return stockId;
	}

	public void setStockId(String stockId) {
		this.stockId = stockId;
	}


}
