package org.kuali.ext.mm.businessobject;

// Generated Apr 7, 2009 2:56:37 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StockTransReason generated by hbm2java
 */
@Entity
@Table(name = "MM_STOCK_TRANS_REASON_T")
public class StockTransReason extends MMPersistableBusinessObjectBase implements
        java.io.Serializable {

    private static final long serialVersionUID = -884834419653502424L;

    @Id
    @Column(name = "STOCK_TRANS_REASON_CD", unique = true, nullable = false, length = 8)
    private String stockTransReasonCd;

    @Column(name = "NM", length = 45)
    private String stockTransReasonDesc;

    @Column(name = "OBJECT_TYPE_CD", length = 4)
    private String objectTypeCode;

    private WarehouseObjectType objectType;
    
    private String incrementDecrementInd;

    public StockTransReason() {
    }

    public String getStockTransReasonCd() {
        return this.stockTransReasonCd;
    }

    public void setStockTransReasonCd(String stockTransReasonCd) {
        this.stockTransReasonCd = stockTransReasonCd;
    }

    public String getStockTransReasonDesc() {
        return this.stockTransReasonDesc;
    }

    public void setStockTransReasonDesc(String stockTransReasonDesc) {
        this.stockTransReasonDesc = stockTransReasonDesc;
    }

    public String getIncrementDecrementInd() {
        return incrementDecrementInd;
    }

    public void setIncrementDecrementInd(String incrementDecrementInd) {
        this.incrementDecrementInd = incrementDecrementInd;
    }


    /**
     * Gets the objectTypeCode property
     *
     * @return Returns the objectTypeCode
     */
    public String getObjectTypeCode() {
        return this.objectTypeCode;
    }

    /**
     * Sets the objectTypeCode property value
     *
     * @param objectTypeCode The objectTypeCode to set
     */
    public void setObjectTypeCode(String objectTypeCode) {
        this.objectTypeCode = objectTypeCode;
    }

    /**
     * Gets the objectType property
     *
     * @return Returns the objectType
     */
    public WarehouseObjectType getObjectType() {
        return this.objectType;
    }

    /**
     * Sets the objectType property value
     *
     * @param objectType The objectType to set
     */
    public void setObjectType(WarehouseObjectType objectType) {
        this.objectType = objectType;
    }

}
