package org.kuali.ext.mm.businessobject;

// Generated May 19, 2009 9:29:05 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StockDoc generated by hbm2java
 */
@Entity
@Table(name = "MM_STOCK_DOC_T")
public class StockDoc extends MMPersistableBusinessObjectBase  {

	/**
     *
     */
    private static final long serialVersionUID = 2178419943923262312L;

    @Id
	@Column(name = "FDOC_NBR", unique = true, nullable = false, length = 36)
	private String fdocNbr;

	@Column(name = "STOCK_HEADER_DESC", length = 400)
	private String stockHeaderDesc;

	@Column(name = "SHORT_STOCK_NM", length = 45)
	private String shortStockNm;

	@Column(name = "AGREEMENT_NBR", precision = 9, scale = 0)
	private Integer agreementNbr;
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stockDoc")
//	private Set<StockAttribute> stockAttributes = new HashSet<StockAttribute>(0);
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stockDoc")
	private Set<Stock> stocks = new HashSet<Stock>(0);

	public StockDoc() {
	}

	public String getFdocNbr() {
		return this.fdocNbr;
	}

	public void setFdocNbr(String fdocNbr) {
		this.fdocNbr = fdocNbr;
	}

	public String getStockHeaderDesc() {
		return this.stockHeaderDesc;
	}

	public void setStockHeaderDesc(String stockHeaderDesc) {
		this.stockHeaderDesc = stockHeaderDesc;
	}

	public String getShortStockNm() {
		return this.shortStockNm;
	}

	public void setShortStockNm(String shortStockNm) {
		this.shortStockNm = shortStockNm;
	}

	public Integer getAgreementNbr() {
		return this.agreementNbr;
	}

	public void setAgreementNbr(Integer agreementNbr) {
		this.agreementNbr = agreementNbr;
	}

//	public Set<StockAttribute> getStockAttributes() {
//		return this.stockAttributes;
//	}
//
//	public void setStockAttributes(Set<StockAttribute> stockAttributes) {
//		this.stockAttributes = stockAttributes;
//	}

	public Set<Stock> getStocks() {
		return this.stocks;
	}

	public void setStocks(Set<Stock> stocks) {
		this.stocks = stocks;
	}

	/**
	 * toStringMapper
	 * @return LinkedHashMap
	 */
	@Override
    public LinkedHashMap toStringMapper() {
		LinkedHashMap propMap = new LinkedHashMap();
		//TODO:  Autogenerated method

		return propMap;
	}

}
