package org.kuali.ext.mm.businessobject;

import java.util.LinkedHashMap;

import javax.persistence.Entity;
import javax.persistence.Table;

import org.kuali.ext.mm.util.MMDecimal;

/**
 * StockPrice generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "MM_STOCK_COST_T")
public class StockCost extends MMPersistableBusinessObjectBase  {

	private String stockCostId;

	private Stock stock;

	private StockTransReason stockTransReason;
	
	private String stockId;

	private CostCode costCode;

	private String costCd;

	private MMDecimal stockCst;

	public MMDecimal getStockCst() {
		return stockCst;
	}

	public void setStockCst(MMDecimal stockCst) {
		this.stockCst = stockCst;
	}

	public StockTransReason getStockTransReason() {
		return stockTransReason;
	}

	public void setStockTransReason(StockTransReason stockTransReason) {
		this.stockTransReason = stockTransReason;
	}
	
	public String getStockCostId() {
        return stockCostId;
    }

    public void setStockCostId(String stockCostId) {
        this.stockCostId = stockCostId;
    }
    
    public Stock getStock() {
        return this.stock;
    }

    public void setStock(Stock stock) {
        this.stock = stock;
    }
    
    public String getStockId() {
        return stockId;
    }

    public void setStockId(String stockId) {
        this.stockId = stockId;
    }
    
    public CostCode getCostCode() {
        return costCode;
    }

    public void setCostCode(CostCode costCode) {
        this.costCode = costCode;
    }
    
    public String getCostCd() {
        return costCd;
    }

    public void setCostCd(String costCd) {
        this.costCd = costCd;
    }

	/**
	 * toStringMapper
	 * @return LinkedHashMap
	 */
	@Override
    public LinkedHashMap toStringMapper() {
		LinkedHashMap propMap = new LinkedHashMap();
		//TODO:  Autogenerated method
		return propMap;
	}
}
