package org.kuali.ext.mm.businessobject;

// Generated Apr 16, 2009 10:01:00 AM by Hibernate Tools 3.2.4.GA

import java.util.LinkedHashMap;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UnitOfIssue generated by hbm2java
 */
@Entity
@Table(name = "MM_UNIT_OF_ISSUE_T")
public class UnitOfIssue extends MMPersistableBusinessObjectBase {

	private static final long serialVersionUID = 7945677950511185071L;

	@Id
	@Column(name = "UNIT_OF_ISSUE_CD", unique = true, nullable = false, length = 10)
	private String unitOfIssueCode;

	@Column(name = "UNIT_OF_ISSUE_DESC", length = 40)
	private String unitOfIssueDesc;

	public UnitOfIssue() {
	}

	public String getUnitOfIssueCode() {
		return this.unitOfIssueCode;
	}

	public void setUnitOfIssueCode(String unitOfIssueCode) {
		this.unitOfIssueCode = unitOfIssueCode;
	}

	public String getUnitOfIssueDesc() {
		return this.unitOfIssueDesc;
	}

	public void setUnitOfIssueDesc(String unitOfIssueDesc) {
		this.unitOfIssueDesc = unitOfIssueDesc;
	}

	public String getUnitOfIssueCodeLookable() {
		return this.getUnitOfIssueCode();
	}

	/**
	 * toStringMapper
	 * @return LinkedHashMap
	 */
	@Override
    public LinkedHashMap toStringMapper() {
		LinkedHashMap propMap = new LinkedHashMap();
		//TODO:  Autogenerated method

		return propMap;
	}

}
