package org.kuali.ext.mm.businessobject;

// Generated Mar 3, 2009 10:13:32 AM by Hibernate Tools 3.2.2.GA

import java.util.LinkedHashMap;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.kuali.ext.mm.common.sys.context.SpringContext;
import org.kuali.ext.mm.integration.FinancialSystemAdaptorFactory;
import org.kuali.ext.mm.integration.coa.businessobject.FinancialAccount;
import org.kuali.ext.mm.integration.coa.businessobject.FinancialChart;
import org.kuali.ext.mm.integration.coa.businessobject.FinancialObjectCode;
import org.kuali.ext.mm.integration.coa.businessobject.FinancialSubAccount;
import org.kuali.ext.mm.integration.coa.businessobject.FinancialSubObjectCode;


/**
 * Cycle generated by hbm2java
 */
@Entity
@Table(name = "MM_WAREHOUSE_ACCOUNTS_T")
public class WarehouseAccounts extends MMPersistableBusinessObjectBase implements
        java.io.Serializable {

    private static final long serialVersionUID = -2524328427681488463L;

    @Id
    @Column(name = "WAREHOUSE_ACCOUNT_ID", nullable = false, length = 36)
    private String warehouseAccountId;

    @Column(name = "WAREHOUSE_CD", length = 2)
    private String warehouseCd;

    @Column(name = "WAREHOUSE_ACCOUNT_TYPE_CD", length = 2)
    private String warehouseAccountTypeCode;

    @Column(name = "FIN_COA_CD", length = 2)
    private String finCoaCd;

    @Column(name = "ACCOUNT_NBR", length = 7)
    private String accountNbr;

    @Column(name = "SUB_ACCT_NBR", length = 5)
    private String subAcctNbr;

    @Column(name = "FIN_OBJECT_CD", length = 4)
    private String finObjectCd;

    @Column(name = "FIN_SUB_OBJ_CD", length = 3)
    private String finSubObjCd;

    @Column(name = "OFFSET_OBJECT_CD", length = 4)
    private String offsetObjectCd;

    @Column(name = "OFFSET_SUB_OBJ_CD", length = 3)
    private String offsetSubObjCd;

    @Column(name = "PROJECT_CD", length = 10)
    private String projectCd;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "WAREHOUSE_CD", nullable = false, insertable = false, updatable = false)
    private Warehouse warehouse;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "WAREHOUSE_ACCOUNT_TYPE_CD", nullable = false, insertable = false, updatable = false)
    private WarehouseAccountType warehouseAccountType;

    /*
     * Financial object references
     */
    private FinancialChart financialChart;
    private FinancialAccount financialAccount;
    private FinancialSubAccount financialSubAccount;
    private FinancialObjectCode financialObjectCode;
    private FinancialSubObjectCode financialSubObjectCode;
    private FinancialObjectCode financialOffsetObjectCode;
    private FinancialSubObjectCode financialOffsetSubObjectCode;
    private Integer currentFiscalYear;

    public WarehouseAccounts() {
    }

    public String getWarehouseAccountId() {
        return warehouseAccountId;
    }

    public void setWarehouseAccountId(String warehouseAccountId) {
        this.warehouseAccountId = warehouseAccountId;
    }

    public String getWarehouseCd() {
        return this.warehouseCd;
    }

    public void setWarehouseCd(String warehouseCd) {
        this.warehouseCd = warehouseCd;
    }

    public String getWarehouseAccountTypeCode() {
        return this.warehouseAccountTypeCode;
    }

    public void setWarehouseAccountTypeCode(String warehouseAccountTypeCode) {
        this.warehouseAccountTypeCode = warehouseAccountTypeCode;
    }

    public String getFinCoaCd() {
        return this.finCoaCd;
    }

    public void setFinCoaCd(String finCoaCd) {
        this.finCoaCd = finCoaCd;
    }

    public String getAccountNbr() {
        return this.accountNbr;
    }

    public void setAccountNbr(String accountNbr) {
        this.accountNbr = accountNbr;
    }

    public String getSubAcctNbr() {
        return this.subAcctNbr;
    }

    public void setSubAcctNbr(String subAcctNbr) {
        this.subAcctNbr = subAcctNbr;
    }

    public String getFinObjectCd() {
        return this.finObjectCd;
    }

    public void setFinObjectCd(String finObjectCd) {
        this.finObjectCd = finObjectCd;
    }

    public String getFinSubObjCd() {
        return this.finSubObjCd;
    }

    public void setFinSubObjCd(String finSubObjCd) {
        this.finSubObjCd = finSubObjCd;
    }

    public String getOffsetObjectCd() {
        return this.offsetObjectCd;
    }

    public void setOffsetObjectCd(String offsetObjectCd) {
        this.offsetObjectCd = offsetObjectCd;
    }

    public String getOffsetSubObjCd() {
        return this.offsetSubObjCd;
    }

    public void setOffsetSubObjCd(String offsetSubObjCd) {
        this.offsetSubObjCd = offsetSubObjCd;
    }

    public String getProjectCd() {
        return this.projectCd;
    }

    public void setProjectCd(String projectCd) {
        this.projectCd = projectCd;
    }

    public Warehouse getWarehouse() {
        return this.warehouse;
    }

    public void setWarehouse(Warehouse warehouse) {
        this.warehouse = warehouse;
    }

    public WarehouseAccountType getWarehouseAccountType() {
        return this.warehouseAccountType;
    }

    public void setWarehouseAccountType(WarehouseAccountType warehouseAccountType) {
        this.warehouseAccountType = warehouseAccountType;
    }

    /**
     * Gets the financialChart property
     *
     * @return Returns the financialChart
     */
    public FinancialChart getFinancialChart() {
        return this.financialChart;
    }

    /**
     * Sets the financialChart property value
     *
     * @param financialChart The financialChart to set
     */
    public void setFinancialChart(FinancialChart financialChart) {
        this.financialChart = financialChart;
    }

    /**
     * Gets the financialAccount property
     *
     * @return Returns the financialAccount
     */
    public FinancialAccount getFinancialAccount() {
        return this.financialAccount;
    }

    /**
     * Sets the financialAccount property value
     *
     * @param financialAccount The financialAccount to set
     */
    public void setFinancialAccount(FinancialAccount financialAccount) {
        this.financialAccount = financialAccount;
    }

    /**
     * Gets the financialSubAccount property
     *
     * @return Returns the financialSubAccount
     */
    public FinancialSubAccount getFinancialSubAccount() {
        return this.financialSubAccount;
    }

    /**
     * Sets the financialSubAccount property value
     *
     * @param financialSubAccount The financialSubAccount to set
     */
    public void setFinancialSubAccount(FinancialSubAccount financialSubAccount) {
        this.financialSubAccount = financialSubAccount;
    }

    /**
     * Gets the financialObjectCode property
     *
     * @return Returns the financialObjectCode
     */
    public FinancialObjectCode getFinancialObjectCode() {
        return this.financialObjectCode;
    }

    /**
     * Sets the financialObjectCode property value
     *
     * @param financialObjectCode The financialObjectCode to set
     */
    public void setFinancialObjectCode(FinancialObjectCode financialObjectCode) {
        this.financialObjectCode = financialObjectCode;
    }

    /**
     * Gets the financialSubObjectCode property
     *
     * @return Returns the financialSubObjectCode
     */
    public FinancialSubObjectCode getFinancialSubObjectCode() {
        return this.financialSubObjectCode;
    }

    /**
     * Sets the financialSubObjectCode property value
     *
     * @param financialSubObjectCode The financialSubObjectCode to set
     */
    public void setFinancialSubObjectCode(FinancialSubObjectCode financialSubObjectCode) {
        this.financialSubObjectCode = financialSubObjectCode;
    }

    /**
     * Gets the financialOffsetObjectCode property
     *
     * @return Returns the financialOffsetObjectCode
     */
    public FinancialObjectCode getFinancialOffsetObjectCode() {
        return this.financialOffsetObjectCode;
    }

    /**
     * Sets the financialOffsetObjectCode property value
     *
     * @param financialOffsetObjectCode The financialOffsetObjectCode to set
     */
    public void setFinancialOffsetObjectCode(FinancialObjectCode financialOffsetObjectCode) {
        this.financialOffsetObjectCode = financialOffsetObjectCode;
    }

    /**
     * Gets the financialOffsetSubObjectCode property
     *
     * @return Returns the financialOffsetSubObjectCode
     */
    public FinancialSubObjectCode getFinancialOffsetSubObjectCode() {
        return this.financialOffsetSubObjectCode;
    }

    /**
     * Sets the financialOffsetSubObjectCode property value
     *
     * @param financialOffsetSubObjectCode The financialOffsetSubObjectCode to set
     */
    public void setFinancialOffsetSubObjectCode(FinancialSubObjectCode financialOffsetSubObjectCode) {
        this.financialOffsetSubObjectCode = financialOffsetSubObjectCode;
    }

    /**
     * toStringMapper
     *
     * @return LinkedHashMap
     */
    @Override
    public LinkedHashMap toStringMapper() {
        LinkedHashMap propMap = new LinkedHashMap();
        // TODO: Autogenerated method

        return propMap;
    }

    /**
     * Gets the currentFiscalYear property
     *
     * @return Returns the currentFiscalYear
     */
    public Integer getCurrentFiscalYear() {
        FinancialSystemAdaptorFactory factory = SpringContext
                .getBean(FinancialSystemAdaptorFactory.class);
        if (this.currentFiscalYear == null && factory.isSystemAvailable()) {
            this.currentFiscalYear = factory.getFinancialUniversityDateService()
                    .getCurrentFiscalYear();
        }
        return this.currentFiscalYear;
    }

    /**
     * Sets the currentFiscalYear property value
     *
     * @param currentFiscalYear The currentFiscalYear to set
     */
    public void setCurrentFiscalYear(Integer currentFiscalYear) {
        this.currentFiscalYear = currentFiscalYear;
    }
}
