package org.kuali.ext.mm.businessobject;

// Generated Mar 3, 2009 10:13:32 AM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cycle generated by hbm2java
 */
@Entity
@Table(name = "MM_WAREHOUSE_ACCOUNT_TYPE_T")
public class WarehouseAccountType extends MMPersistableBusinessObjectBase implements
		java.io.Serializable {

	private static final long serialVersionUID = -2524328427681488463L;

	@Id
	@Column(name = "WAREHOUSE_ACCOUNT_TYPE_CD", unique = true, nullable = false, length = 2)
	private String warehouseAccountTypeCode;

	@Column(name = "NM", length = 45)
	private String warehouseAccountTypeName;

	public WarehouseAccountType() {
	}

	public WarehouseAccountType(String warehouseAccountTypeCode) {
		this.warehouseAccountTypeCode = warehouseAccountTypeCode;
	}

	public WarehouseAccountType(String warehouseAccountTypeCode, String warehouseAccountTypeName) {
		super();
		this.warehouseAccountTypeCode = warehouseAccountTypeCode;
		this.warehouseAccountTypeName = warehouseAccountTypeName;
	}

	public String getWarehouseAccountTypeCode() {
		return this.warehouseAccountTypeCode;
	}

	public void setWarehouseAccountTypeCode(String warehouseAccountTypeCode) {
		this.warehouseAccountTypeCode = warehouseAccountTypeCode;
	}

	public String getWarehouseAccountTypeName() {
		return this.warehouseAccountTypeName;
	}

	public void setWarehouseAccountTypeName(String warehouseAccountTypeName) {
		this.warehouseAccountTypeName = warehouseAccountTypeName;
	}

}
