package org.kuali.ext.mm.businessobject;

// Generated Apr 14, 2009 9:59:03 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WorksheetStatus generated by hbm2java
 */
@Entity
@Table(name = "MM_WORKSHEET_STATUS_T")
public class WorksheetStatus extends MMPersistableBusinessObjectBase implements
		java.io.Serializable {

	private static final long serialVersionUID = -5303178519270160910L;

	@Id
	@Column(name = "WORKSHEET_STATUS_CD", unique = true, nullable = false, length = 4)
	private String worksheetStatusCode;

	@Column(name = "NM", length = 40)
	private String worksheetStatusName;
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "worksheetStatus")
//	private Set<Worksheet> worksheets = new HashSet<Worksheet>(0);

	public WorksheetStatus() {
	}

	public String getWorksheetStatusCode() {
		return this.worksheetStatusCode;
	}

	public void setWorksheetStatusCode(String worksheetStatusCode) {
		this.worksheetStatusCode = worksheetStatusCode;
	}

	public String getWorksheetStatusName() {
		return this.worksheetStatusName;
	}

	public void setWorksheetStatusName(String worksheetStatusName) {
		this.worksheetStatusName = worksheetStatusName;
	}

}
