package org.kuali.ext.mm.businessobject;

// Generated Apr 16, 2009 10:01:00 AM by Hibernate Tools 3.2.4.GA

import java.sql.Clob;
import java.util.LinkedHashMap;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * XmlInvoice generated by hbm2java
 */
@Entity
@Table(name = "MM_XML_INVOICE_T")
public class XmlInvoice extends MMPersistableBusinessObjectBase implements
		java.io.Serializable {

	private static final long serialVersionUID = 5005148198989870649L;

	@Id
	@Column(name = "KEY_ID", unique = true, nullable = false, length = 100)
	private String keyId;

	@Column(name = "CATALOG_CD", nullable = false, length = 12)
	private String catalogCd;

	@Column(name = "ORDER_ID", nullable = false, precision = 8, scale = 0)
	private Integer orderId;

	@Column(name = "INVOICE_NBR", length = 15)
	private String invoiceNbr;

	@Column(name = "PROCESSED_IND", length = 1)
	private boolean processedInd;

	@Column(name = "INVOICE_XML")
	private Clob invoiceXml;

	public XmlInvoice() {
	}

	public String getKeyId() {
		return this.keyId;
	}

	public void setKeyId(String keyId) {
		this.keyId = keyId;
	}

	public String getCatalogCd() {
		return this.catalogCd;
	}

	public void setCatalogCd(String catalogCd) {
		this.catalogCd = catalogCd;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public String getInvoiceNbr() {
		return this.invoiceNbr;
	}

	public void setInvoiceNbr(String invoiceNbr) {
		this.invoiceNbr = invoiceNbr;
	}

	public boolean isProcessedInd() {
		return this.processedInd;
	}

	public void setProcessedInd(boolean processedInd) {
		this.processedInd = processedInd;
	}

	public Clob getInvoiceXml() {
		return this.invoiceXml;
	}

	public void setInvoiceXml(Clob invoiceXml) {
		this.invoiceXml = invoiceXml;
	}

	/**
	 * toStringMapper
	 * @return LinkedHashMap
	 */
	@Override
    public LinkedHashMap toStringMapper() {
		LinkedHashMap propMap = new LinkedHashMap();
		//TODO:  Autogenerated method

		return propMap;
	}

}
