insert into mm_agreement_t (AGREEMENT_NBR, OBJ_ID, VER_NBR, VNDR_CONTR_GNRTD_ID, VNDR_HDR_GNRTD_ID, VNDR_DTL_ASND_ID, VENDOR_NM, PO_TOTAL_LIMIT, AGREEMENT_LAG_DAYS, AGREEMENT_USED_AMT, AGREEMENT_BEGIN_DT, AGREEMENT_END_DT, B2B_IND, GHOST_CARD_IND, E_INVOICE_IND, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT)
values ('201042', sys_guid(), 1, 1, NULL, NULL, 'ADVANCE GLOVE & SAFETY CO INC', '75000.00', '5',  '0.00', to_date('07012009', 'MMDDYYYY'), to_date('03312010', 'MMDDYYYY'), 'N', 'N', 'N', '74', 'Y', CURRENT_DATE )
;
insert into mm_agreement_t (AGREEMENT_NBR, OBJ_ID, VER_NBR, VNDR_CONTR_GNRTD_ID, VNDR_HDR_GNRTD_ID, VNDR_DTL_ASND_ID, VENDOR_NM, PO_TOTAL_LIMIT, AGREEMENT_LAG_DAYS, AGREEMENT_USED_AMT, AGREEMENT_BEGIN_DT, AGREEMENT_END_DT, B2B_IND, GHOST_CARD_IND, E_INVOICE_IND, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT)
values ('201059', sys_guid(), 1, '4115', '6871', '0', 'WESCO DISTRIBUTION INC', '75000.00', '5',  '0.00', to_date('10012009', 'MMDDYYYY'), to_date('09302010', 'MMDDYYYY'), 'N', 'N', 'N', '74', 'Y', CURRENT_DATE )
;
insert into mm_agreement_t (AGREEMENT_NBR, OBJ_ID, VER_NBR, VNDR_CONTR_GNRTD_ID, VNDR_HDR_GNRTD_ID, VNDR_DTL_ASND_ID, VENDOR_NM, PO_TOTAL_LIMIT, AGREEMENT_LAG_DAYS, AGREEMENT_USED_AMT, AGREEMENT_BEGIN_DT, AGREEMENT_END_DT, B2B_IND, GHOST_CARD_IND, E_INVOICE_IND, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT)
values ('201079', sys_guid(), 1, '4123', '9998', '0', 'The Burrows Co', '75000.00', '5',  '0.00', to_date('02122010', 'MMDDYYYY'), to_date('01312011', 'MMDDYYYY'), 'N', 'N', 'N', '74', 'Y', CURRENT_DATE )
;
insert into mm_agreement_t (AGREEMENT_NBR, OBJ_ID, VER_NBR, VNDR_CONTR_GNRTD_ID, VNDR_HDR_GNRTD_ID, VNDR_DTL_ASND_ID, VENDOR_NM, PO_TOTAL_LIMIT, AGREEMENT_LAG_DAYS, AGREEMENT_USED_AMT, AGREEMENT_BEGIN_DT, AGREEMENT_END_DT, B2B_IND, GHOST_CARD_IND, E_INVOICE_IND, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT)
values ('201039', sys_guid(), 1, '4121', '19112', '0', 'STAPLES BUSINESS ADVANTAGE', '75000.00', '5',  '0.00', to_date('06092009', 'MMDDYYYY'), to_date('04302010', 'MMDDYYYY'), 'N', 'N', 'N', '74', 'Y', CURRENT_DATE )
;
insert into mm_agreement_t (AGREEMENT_NBR, OBJ_ID, VER_NBR, VNDR_CONTR_GNRTD_ID, VNDR_HDR_GNRTD_ID, VNDR_DTL_ASND_ID, VENDOR_NM, PO_TOTAL_LIMIT, AGREEMENT_LAG_DAYS, AGREEMENT_USED_AMT, AGREEMENT_BEGIN_DT, AGREEMENT_END_DT, B2B_IND, GHOST_CARD_IND, E_INVOICE_IND, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT)
values ('201065', sys_guid(), 1, '4117', '4116', '0', 'OFFICE MAX', '75000.00', '5',  '0.00', to_date('11012009', 'MMDDYYYY'), to_date('10312010', 'MMDDYYYY'), 'N', 'N', 'N', '74', 'Y', CURRENT_DATE )
;
insert into mm_agreement_t (AGREEMENT_NBR, OBJ_ID, VER_NBR, VNDR_CONTR_GNRTD_ID, VNDR_HDR_GNRTD_ID, VNDR_DTL_ASND_ID, VENDOR_NM, PO_TOTAL_LIMIT, AGREEMENT_LAG_DAYS, AGREEMENT_USED_AMT, AGREEMENT_BEGIN_DT, AGREEMENT_END_DT, B2B_IND, GHOST_CARD_IND, E_INVOICE_IND, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT)
values ('201060', sys_guid(), 1, '4119', '7430', '0', 'MEDLER ELECTRIC CO', '75000.00', '5',  '0.00', to_date('10012009', 'MMDDYYYY'), to_date('09302010', 'MMDDYYYY'), 'N', 'N', 'N', '74', 'Y', CURRENT_DATE )
;
insert into mm_agreement_t (AGREEMENT_NBR, OBJ_ID, VER_NBR, VNDR_CONTR_GNRTD_ID, VNDR_HDR_GNRTD_ID, VNDR_DTL_ASND_ID, VENDOR_NM, PO_TOTAL_LIMIT, AGREEMENT_LAG_DAYS, AGREEMENT_USED_AMT, AGREEMENT_BEGIN_DT, AGREEMENT_END_DT, B2B_IND, GHOST_CARD_IND, E_INVOICE_IND, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT)
values ('201061', sys_guid(), 1, '4120', '7726', '0', 'GREAT LAKES MULTIMEDIA', '75000.00', '5',  '0.00', to_date('09292009', 'MMDDYYYY'), to_date('08312010', 'MMDDYYYY'), 'N', 'N', 'N', '74', 'Y', CURRENT_DATE )
;
insert into mm_agreement_t (AGREEMENT_NBR, OBJ_ID, VER_NBR, VNDR_CONTR_GNRTD_ID, VNDR_HDR_GNRTD_ID, VNDR_DTL_ASND_ID, VENDOR_NM, PO_TOTAL_LIMIT, AGREEMENT_LAG_DAYS, AGREEMENT_USED_AMT, AGREEMENT_BEGIN_DT, AGREEMENT_END_DT, B2B_IND, GHOST_CARD_IND, E_INVOICE_IND, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT)
values ('201070', sys_guid(), 1, '4121', '6522', '0', 'FISHER SCIENTIFIC COMPANY LLC', '75000.00', '5',  '0.00', to_date('01012010', 'MMDDYYYY'), to_date('12312010', 'MMDDYYYY'), 'N', 'N', 'N', '74', 'Y', CURRENT_DATE )
;
insert into mm_agreement_t (AGREEMENT_NBR, OBJ_ID, VER_NBR, VNDR_CONTR_GNRTD_ID, VNDR_HDR_GNRTD_ID, VNDR_DTL_ASND_ID, VENDOR_NM, PO_TOTAL_LIMIT, AGREEMENT_LAG_DAYS, AGREEMENT_USED_AMT, AGREEMENT_BEGIN_DT, AGREEMENT_END_DT, B2B_IND, GHOST_CARD_IND, E_INVOICE_IND, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT)
values ('201048', sys_guid(), 1, '4122', '8024', '0', 'ABBOTT LABORATORIES INC', '75000.00', '5',  '0.00', to_date('07242009', 'MMDDYYYY'), to_date('06302010', 'MMDDYYYY'), 'N', 'N', 'N', '74', 'Y', CURRENT_DATE )
;
insert into mm_agreement_t (AGREEMENT_NBR, OBJ_ID, VER_NBR, VNDR_CONTR_GNRTD_ID, VNDR_HDR_GNRTD_ID, VNDR_DTL_ASND_ID, VENDOR_NM, PO_TOTAL_LIMIT, AGREEMENT_LAG_DAYS, AGREEMENT_USED_AMT, AGREEMENT_BEGIN_DT, AGREEMENT_END_DT, B2B_IND, GHOST_CARD_IND, E_INVOICE_IND, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT)
values ('201056', sys_guid(), 1, '4118', '4116', '0', 'OFFICE MAX', '75000.00', '5',  '0.00', to_date('09092009', 'MMDDYYYY'), to_date('08312010', 'MMDDYYYY'), 'N', 'N', 'N', '74', 'Y', CURRENT_DATE )
;
