INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1001','Adhesive, Bandage, Dressing & Sponges',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1002','Alcohol',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1003','Catheters',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1004','Cleaner',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1005','Gloves',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1006','Antiseptic Towelette',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1007','Needles & Syringes',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1008','Sets',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1009','Solutions',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1010','Surgical Blades',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1011','Scissors',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1012','Scalpel',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1013','Sutures',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1014','Incision Clip',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1015','Tray',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1016','Paper Towel',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1017','Surgical Drape',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1018','Nurses Cap',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1019','Post Op Shoe',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1020','Tube',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1021','Mask',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1022','Tape',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1023','Brace',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1024','Diaper',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1025','Training Pants',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1026','Underpads',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1027','Kits',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1028','Diagnostic Supplies & Equipment',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1029','CPR Accessories',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1030','Personal Care',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','1031','Tubing',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'20','2001','Appliances',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'20','2002','Beverages',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'20','2003','Cleaning Supplies',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'20','2004','Paper Products/Cutlery',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'20','2005','Pain Relievers',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'30','3001','Adhesives',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'30','3002','Cement',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'30','3003','Lumber',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'30','3004','Dowel',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'30','3005','Plywood',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'30','3006','Joint Compound',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'30','3007','Plaster',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'30','3008','Safety Tread',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'30','3009','Flagging Tape',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'30','3010','Steel',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','4001','Garden Stakes',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','4002','Visqueen',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','4003','Perlite',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','4004','Vermiculite',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','4005','Bedding',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5001','{1-Propanol}',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5002','{2-Propanol}',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5003','Acetone  HPLC',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5004','Acetone ACS UN1090',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5005','Acetone ChromeAR',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5006','Acetone High Purity',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5007','Acetonitrile  UV High Purity',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5008','Acetonitrile HPLC',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5009','Acetonitrile Methyl Cyanide',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5010','Acetronitrile Non Spectro',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5011','Alcohol -  Ethyl Alcohol',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5012','Alcohol - Isopropyl',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5013','Alcohol - Methyl',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5014','Alcohol - Rubbing',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5015','Aluminum Sulfate',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5016','Ammonium  Sulfate',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5017','Ammonium Chloride',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5018','Ammonium Hydroxide',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5019','Ascorbic Acid',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5020','Boric Acid',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5021','Buffer -Standard Solution',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5022','Butanol',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5023','Calcium Chloride',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5024','Chlorine',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5025','Chloroform  OmniSolv',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5026','Chloroform ACS',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5027','Chloroform GR',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5028','Counting cocktail',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5029','Culture Media',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5030','Cyclohesane',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5031','D-Gulcose',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5032','Dichloromethane  GR',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5033','Dichloromethane  Methylene  Chloride',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5034','Diethyl Ether',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5035','Dimethyl Sulfoxide',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5036','Drierite',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5037','Ethanol',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5038','Ethyl Acetate',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5039','Ethyl Ether',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5040','Ethylene',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5041','Formaldehyde',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5042','Formic',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5043','Glacial Acetic Acid  ACS',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5044','Glacial Acetic Acid  ACS Aldehyde Free',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5045','Glycerol',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5046','Glycine',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5047','Hexanes',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5048','HPLC Water',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5049','Hydrochloric',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5050','Hydrogen Peroxide',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5051','Isoflurane',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5052','Lactic Acid',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5053','Magnesioum',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5054','Methanol',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5055','Muriatic Acid',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5056','Nitric Acid',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5057','Pentane',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5058','Petroleum Ether',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5059','Phenol',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5060','Phosphoric Acid',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5061','Potassium Acetate',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5062','Potassium Chloride',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5063','Potassium Hydroxide',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5064','Potassium Iodide',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5065','Potassium Phosphate',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5066','Propianic Acid',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5067','Pyridine',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5068','Sodalime',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5069','Sodium Acetate',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5070','Sodium Bicarbonate',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5071','Sodium Chloride',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5072','Sodium Citrate',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5073','Sodium Dodecyl',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5074','Sodium Hydroxide',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5075','Sodium Nitrate',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5076','Sodium Phosphate',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5077','Sodium Pyrophospate',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5078','Sodium Sulfate',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5079','Sucrose',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5080','Sulfuric',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5081','Toluene',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5082','Triton',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5083','Trizma',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','5084','Xylenes',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'60','6001','Electrical Boxes',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'60','6002','Conduit',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'60','6003','Lighting',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'60','6004','Circuit',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'60','6005','Wire/Cable',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'70','7001','Glassware',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'70','7002','Tube',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'70','7003','Slide',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'70','7004','Vial',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'70','7005','Misc. Lab Glassware',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'70','7006','General Laboratory',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'80','8001','Furniture/Equipment',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'80','8002','Technology',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'80','8003','Office Supplies',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'80','8004','Paper & Pads',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'80','8005','File Folders & Accessories',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'80','8006','Labels & Label Maker',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'80','8007','Fasteners',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'80','8008','Writing Instruments',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'80','8009','Misc. Office Supplies',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'80','8010','Calendars',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'90','9001','Envelopes',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'90','9002','Mailing Tubes',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'90','9003','Disk Mailer',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'90','9004','Postage Stamp',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'90','9005','Boxes',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'90','9006','Shrink Wrap',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'90','9007','Envelope Moistener',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'91','9101','Paint',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'91','9102','Paint Accessories',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'92','9202','Plumbing Adhesives',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'92','9203','Plumbing',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'92','9204','Pipe & Fittings',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'92','9205','Misc. Plumbimg & Hvac',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'93','9301','Fasteners',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'93','9302','Hand Tools',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'93','9303','Adhesives & Abrasives',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'93','9304','Salt, Chemicals, and Lubricants',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'93','9305','Batteries & Accessories',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'93','9306','Gloves',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'93','9307','Housewares',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'94','9401','Acetylene',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'94','9402','Aerobic Gas Mixture',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'94','9403','Air',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'94','9404','Air/CO2',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'94','9405','Ammonia',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'94','9406','Argon',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'94','9407','Argon/Carbon Dioxide',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'94','9408','Carbon Dioxide',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'94','9409','Chlorine',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'94','9410','Flame Ionization',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'94','9411','Freon',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'94','9412','Helium',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'94','9413','Hydrogen',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'94','9414','Hydrogen Chloride',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'94','9415','Hydrogen Sulfide',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'94','9416','MethaneNitrogen',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'94','9417','Nitrous Oxide',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'94','9418','Oxygen',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'94','9419','Propane',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'94','9420','Propylene',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'94','9421','Refrigerator Gas',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'94','9422','Accessories',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'95','9501','Biohazarad Bag',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'95','9502','Band (chums)',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'95','9503','Hazmat Boot',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'95','9504','Sharps Collector',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'95','9505','Container',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'95','9506','Cover',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'95','9507','Coveralls',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'95','9508','Earmuff',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'95','9509','Glasses',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'95','9510','Gloves',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'95','9511','Goggles',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'95','9512','Spill Kit',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'95','9513','Earplugs',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'95','9514','Face Shield',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'95','9515','Respirator',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'81','8101','Epson',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'81','8102','Xerox',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'81','8103','Hewlett Packard',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9901','Apparel',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9902','Jewelry & Collectables',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9903','{"Be Spartan Green"}',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9904','Water Bottles',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9905','Mugs',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9906','School Supplies',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9907','Bags',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9908','Blanket',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9909','Calendar',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9910','Notecard',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9911','Chairmat',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9912','Cinchsack',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9913','Clip',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9914','Coaster',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9915','Decal',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9916','Cushion',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9917','Umbrella',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9918','Name Badge',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9919','Badge Reel',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9920','Towel',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9921','Tote',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9922','Tote/Blanket',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9923','Wristband',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9924','Lanyard',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9925','Tatoo',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9926','Tailgate Mat',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9927','Luggage Tag',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9928','Rain Poncho',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9929','Purse Hanger',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9930','Gift Label',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9931','Gift Wrap',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9932','Jar Opener',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9933','Luggage Strap',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','9934','Dog Leash',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'96','9601','Cleaning Supplies',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'96','9602','Towel & Tissue',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'96','9603','Trash Handling',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'96','9604','Cleaning Tools',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'96','9605','Personal Hygiene',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
  VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'96','9606','Miscellaneous',NULL,'Y',CURRENT_DATE);
