    -- Office Max Hosted Catalog Items (Sample)
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3Q10584','Q10584','EA',10.55,'Nice Pak Products, Inc. - Sani-Cloth HB Wipes, Description 160, Canister, Quantity 1/Each, Size 6 x 6-3/4',NULL,'N','4713000000','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3Q41200WH00','Q41200WH','EA',10.49,'Rubbermaid - 18'' Microfiber Dry Dusting Pads, Color White, Size 18", Type Room Dust Pad',NULL,'N','4713000000','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3Q41500-BL00','Q41500-B','EA',12.39,'Rubbermaid - Microfiber Quick Connect - Wet Pads, Size 18"',NULL,'N','4713000000','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3Q41800-GR00','Q41800-G','EA',14.08,'Rubbermaid - 18'' Microfiber Dry Dusting Pads, Color Green, Size 18", Type Pad with Fringe',NULL,'N','4713000000','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3Q42500-BL00','Q42500-B','EA',16.55,'Rubbermaid - Microfiber Wet Pad with Scrubber, Color Blue, Size 18"W, Type Microfiber',NULL,'N','4713000000','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3Q56000-YL00','Q56000-Y','EA',23.26,'Rubbermaid - Microfiber Quick Connect - Hall Dusting Frame, Size 18"',NULL,'N','4713000000','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3Q57000YL00','Q57000YL','EA',27.05,'Rubbermaid - Microfiber Quick Connect - 24'' Squeegee Frame, Size 24", Type Frame Only',NULL,'N','4713000000','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3Q76000-YL00','Q76000-Y','EA',17.14,'Rubbermaid - Microfiber Quick Connect - Ergo Handle, Color Yellow, Type Adjustable',NULL,'N','4713000000','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3Q89084','Q89084','EA',8.86,'Nice Pak Products, Inc. - Sani-Cloth Plus Germicidal Disposable Cloths, Quantity 1 Each, Size 160/Canister, Type Unscented',NULL,'N','4713000000','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3Q95000-YEL','Q95000-Y','EA',45.53,'Rubbermaid - MicroFiber Mop Bucket - Disinfecting Bucket, Color Yellow, Type Bucket',NULL,'N','4713000000','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3Q96600','Q96600','EA',42.45,'Rubbermaid - Pulse Caddy with Clean Connect, Size 1 each',NULL,'N','4713160000','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3Q96900YEL','Q96900YE','EA',145.89,'Rubbermaid - Pulse Mopping Kit, Size 18"L 58" Metal Handle, Type Aluminum',NULL,'N','4713160000','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3R1214CT','R1214CT','CT',28.95,'Amrep - Misty Glass '||Char(38)||' Mirror Cleaner with Ammonia, Quantity 4 Gallons/Carton, Size Gallon',NULL,'N','4713182400','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3R121-4EA','R121-4EA','EA',7.73,'Amrep - Misty Glass '||Char(38)||' Mirror Cleaner with Ammonia, Quantity 1, Size Gallon',NULL,'N','4713182400','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3R12234','R12234','EA',10.66,'Amrep - Misty Biodet ND32, Size Gallon Bottle, Type Pine Scent',NULL,'N','4713000000','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3R1254','R1254','EA',15.11,'Amrep - Misty Heavy Duty Glass Cleaner Concentrate, Size Gallon Bottle',NULL,'N','4713000000','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3R1684','R1684','EA',16.7,'Amrep - Misty Green All-Purpose Cleaner RTU, Size Gallon Bottle',NULL,'N','4713000000','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3R8004CT','R8004CT','CT',36.31,'Amrep - Misty Neutra Clean Floor Cleaner, Quantity 4, Size Gallon, Type Bottle',NULL,'N','4713180100','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3R800-4EA','R800-4EA','EA',10.2,'Amrep - Misty Neutra Clean Floor Cleaner, Quantity 1, Size Gallon, Type Bottle',NULL,'N','4713180100','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3R8234CT','R8234CT','CT',31.64,'Amrep - Redi-Steam Carpet Cleaner, Quantity 4/Carton, Size 1 Gallon, Type Bottle',NULL,'N','7611160400','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3R920-12CT','R920-12C','CT',52.31,'Amrep - Misty Nab Nonacid Bathroom Cleaner, Quantity 12 Bottles/Carton, Size 32-oz Bottle, Type Bottle',NULL,'N','4713180500','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3R92012EA','R92012EA','EA',4.93,'Amrep - Misty Nab Nonacid Bathroom Cleaner, Quantity 1 Each, Size 32 oz Bottle, Type Spearmint',NULL,'N','4713000000','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3R92512CT','R92512CT','CT',34.61,'Amrep - Misty Bolex (26% HCI) Bowl Cleaner, Quantity 12 - 32 Oz. Spray Bottles/Carton, Type Bottle',NULL,'N','4713182900','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3R93012CT','R93012CT','CT',48.24,'Amrep - Misty Bolex (10% HCI) Bowl Cleaner, Quantity 12 - 32 Oz. Spray Bottles/Carton, Type Bottle',NULL,'N','4713182900','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3RC250BP','RC250BP','EA',15.03,'Energizer - Energizer Double Duty Rechargeable Flashlight, Quantity 1',NULL,'N','4713000000','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3RC613','RC613','KT',16.21,'First Aid - Deluxe Personal Safety Pack, Dimensions 3-7/8" W x 2-7/8"D x 8-1/4"H, People One, Weight 1 Lb.',NULL,'N','4217200100','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3RC622','RC622','KT',19.25,'American Red Cross - Personal Emergency Preparedness Kit, Size Single Person',NULL,'N','4713000000','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3RC651','RC651','EA',15.51,'First Aid - Deluxe Germ Guard Personal Protection Pack, Dimensions 3-7/8" W x 2-7/8" D x 8-1/4" H, Pieces 300, Weight 1 Lb.',NULL,'N','4217200100','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3RC662','RC662','KT',48.22,'American Red Cross - Emergency Smartpack, Size 5 Person',NULL,'N','4713000000','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','W3RDU2020','RDU2020','EA',223.43,'Motorola - UHF/VHF Business Two-Way Radios, Type 89 Built-In Frequencies, UHF',NULL,'N','5216151100','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '06'),'Y');
   
    -- Office Max Furniture Hosted Catalog Items (Sample)
    
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8LA4896KH','LA4896KH','EA',445.11,'HON - Racetrack Conference Tables (Base '||Char(38)||' Top), Color Bourbon Cherry, Color/Finish Bourbon Cherry, Dimensions 48" x 96", Type Top Only, Matching Ribbon Edge, Weight 235 Lbs. (with',NULL,'N','5610170600','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8LA4896KN','LA4896KN','EA',445.11,'HON - Racetrack Conference Tables (Base '||Char(38)||' Top), Color Mahogany, Color/Finish Mahogany, Dimensions 48" x 96", Type Top Only, Matching Ribbon Edge, Weight 260 Lbs. (with base compone',NULL,'N','5610170600','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8LC3672KH','LC3672KH','EA',332.96,'HON - Rectangular Conference Tables, Color Bourbon Cherry, Dimensions 36" x 72", Type Top Only, Matching Ribbon Edge',NULL,'N','5610170600','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8LC3672KN','LC3672KN','EA',332.96,'HON - Rectangular Conference Tables, Color Mahogany, Dimensions 36" x 72", Type Top Only, Matching Ribbon Edge',NULL,'N','5610170600','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8LC4896KH','LC4896KH','EA',434.65,'HON - Rectangular Conference Tables, Color/Finish Bourbon Cherry, Dimensions 36" x 72", Type Top Component, Weight 247 Lbs. (including base)',NULL,'N','5610170600','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8LC4896KN','LC4896KN','EA',434.65,'HON - Rectangular Conference Tables, Color/Finish Mahogany, Dimensions 36" x 72", Type Table Top, Weight 247 Lbs. (including base)',NULL,'N','5610170600','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8LD42GM','LD42GM','EA',176.07,'HON - 10500 Series Round Table - Top Only, Color Medium Oak, Dimensions 42" Dia., Type Top Only, Weight 75 Lbs.',NULL,'N','5610151900','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8LD42GN','LD42GN','EA',176.07,'HON - 10500 Series Round Table - Top Only, Color Mahogany, Dimensions 42" Dia., Type Top Only, Weight 75 Lbs.',NULL,'N','5610151900','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8LD48GM','LD48GM','EA',194.66,'HON - 10500 Series Round Table - Top Only, Color Mahogany, Dimensions 48" Dia., Type Top Only, Weight 60 Lbs.',NULL,'N','5610151900','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8LD48GN','LD48GN','EA',194.66,'HON - 10500 Series Round Table - Top Only, Color Mahogany, Dimensions 48" Dia., Type Top Only, Weight 60 Lbs.',NULL,'N','5610151900','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8UTM1872MLCHR','UTM1872M','EA',163.73,'HON - Metal Base Utility Tables, Color Medium Oak/Putty, Dimensions 72" W x 18" D x 29" H',NULL,'N','5610151900','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8UTM1872QQCHR','UTM1872Q','EA',163.73,'HON - Metal Base Utility Tables, Color Light Gray/Light Gray, Dimensions 72" W x 18" D x 29" H',NULL,'N','5610151900','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8UTM1872ZPCHR','UTM1872Z','EA',184.13,'HON - Metal Base Utility Tables, Color Columbian Walnut, Dimensions 72" W x 18" D x 29" H',NULL,'N','5611210000','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8UTM2060MLCHR','UTM2060M','EA',146.64,'HON - Metal Base Utility Tables, Color Medium Oak/Putty, Dimensions 60" W x 20" D x 29" H',NULL,'N','5610151900','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8UTM2060QQCHR','UTM2060Q','EA',146.64,'HON - Metal Base Utility Tables, Color Light Gray/Light Gray, Dimensions 60" W x 20" D x 29" H',NULL,'N','5610151900','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8UTM2060ZPCHR','UTM2060Z','EA',165.38,'HON - Metal Base Utility Tables, Color Columbian Walnut, Dimensions 60" W x 20" D x 29" H',NULL,'N','5611210000','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8UTM3060MLCHR','UTM3060M','EA',160.42,'HON - Metal Base Utility Tables, Color Medium Oak/Putty, Dimensions 60" W x 30" D x 29" H',NULL,'N','5610151900','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8UTM3060QQCHR','UTM3060Q','EA',160.42,'HON - Metal Base Utility Tables, Color Light Gray/Light Gray, Dimensions 60" W x 30" D x 29" H',NULL,'N','5610151900','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8UTM3060ZPCHR','UTM3060Z','EA',180.82,'HON - Metal Base Utility Tables, Color Columbian Walnut, Dimensions 60" W x 30" D x 29" H',NULL,'N','5611210000','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8UTM3072MLCHR','UTM3072M','EA',189.05,'HON - Metal Base Utility Tables, Color Medium Oak/Putty, Dimensions 72" W x 30" D x 29" H',NULL,'N','5610151900','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8UTM3072QQCHR','UTM3072Q','EA',200.67,'HON - Metal Base Utility Tables, Color Light Gray/Light Gray, Dimensions 72" W x 30" D x 29" H',NULL,'N','5610151900','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8UTM3072ZPCHR','UTM3072Z','EA',226.03,'HON - Metal Base Utility Tables, Color Columbian Walnut, Dimensions 72" W x 30" D x 29" H',NULL,'N','5611210000','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8UTM3672MLCHR','UTM3672M','EA',213.35,'HON - Metal Base Utility Tables, Color Medium Oak/Putty, Dimensions 72" W x 36" D x 29" H',NULL,'N','5610151900','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8UTM3672QQCHR','UTM3672Q','EA',213.35,'HON - Metal Base Utility Tables, Color Light Gray/Light Gray, Dimensions 72" W x 36" D x 29" H',NULL,'N','5610151900','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8UTM3672ZPCHR','UTM3672Z','EA',240.36,'HON - Metal Base Utility Tables, Color Columbian Walnut, Dimensions 72" W x 36" D x 29" H',NULL,'N','5611210000','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8XFP36CHR','XFP36CHR','EA',325.41,'HON - Hospitality Tables - Bases Only, Color/Finish Chrome, Dimensions 36" Wide, Type 5-Column',NULL,'N','5610151900','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8XFP36P','XFP36P','EA',308.72,'HON - Hospitality Tables - Bases Only, Color/Finish Black, Dimensions 36" Wide, Type 5-Column',NULL,'N','5610151900','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8XSP26CHR','XSP26CHR','EA',151.6,'HON - Hospitality Tables - Bases Only, Color/Finish Chrome, Dimensions 26" Wide, Type Single Column',NULL,'N','5610151900','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8XSP26P','XSP26P','EA',151.6,'HON - Hospitality Tables - Bases Only, Color/Finish Black, Dimensions 26" Wide, Type Single-Column',NULL,'N','5610151900','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','E8XSP36CHR','XSP36CHR','EA',213.84,'HON - Hospitality Tables - Bases Only, Color/Finish Chrome, Dimensions 36" Wide, Type Single Column',NULL,'N','5610151900','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '09'),'Y');

    -- VWR Hosted Catalog Items (Sample)

INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-000-CS','022266551','CS',115.38,'Eppendorf  Combitip  Plus Tips for Eppendorf Repeater   Repeater Plus  and Repeater pro Pipettor  Total Volume: 25.0mL. Volume Range: 250uL-5mL. Increments: 250uL. Reservoirs have polyethylene plungers and polypropylene cylinders. Nonsterile. Package of 1',NULL,'N','4112160700','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-002-EA','022266993','EA',16.35,'Adapter for Eppendorf  Repeater   Repeater Plus  and Repeater pro Pipettor  Adapter for nonsterile  25mL tips.',NULL,'N','4112160700','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-004-CS','022496131','CS',151.72,'Eppendorf  Biopur Combitip  Plus Tips  For Eppendorf Repeater   Repeater Plus  and Repeater pro Pipettor. Total Volume: 25.0mL. Volume Range: 250uL-5mL. Increments: 250uL. Certified sterile  pyrogen-free  DNase-free  RNase-free  and ATP-free. Individually',NULL,'N','4112160700','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-007-PK','022496158','PK',103.57,'Adapter for Eppendorf  Repeater   Repeater Plus  and Repeater pro Pipettor  Adapter for sterile  25mL tips.',NULL,'N','4112160700','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-010-CS','022267655','CS',119.79,'Eppendorf  Combitip  Plus Tips for Eppendorf Repeater   Repeater Plus  and Repeater pro Pipettor  Total Volume: 25.0mL. Volume Range: 250 uL-5 mL. Increments: 250 uL. Reservoirs have polyethylene plungers and polypropylene cylinders. Sterile. Individually',NULL,'N','4112160700','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-012-CS','TY120SWHSM00','CS',118.35,'DuPont  Tyvek  Coverall  Made from tear-resistant  lightweight  spunbonded olefin. Offers splash  dry-particulate  and bacteria protection. Disposable  low-linting coveralls feature generous cut  serged seams  collar  and front zipper. Bulk packed. White.',NULL,'N','4618153200','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-026-CS','TY122SWHSM00','CS',145.33,'TYVCOV ZF HD BT EW SS SM25/CS',NULL,'N','4618153200','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-040-CS','TY125SWHSM00','CS',133.67,'DuPont  Tyvek  Coveralls with Elastic  Elastic closures around wrists and ankles to provide a good fit and guard against many dry particulates and light sprays. It''s  one-of-a-kind  inherent barrier won''t rip  tear  or abrade as easily as the barrier in l',NULL,'N','4618153200','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-054-CS','TY127SWHSM00','CS',142.96,'DuPont  Tyvek  Coverall with Attached Hood  Made from tear-resistant  lightweight  spunbonded olefin. Offers splash  dry-particulate  and bacteria protection. Disposable  low-linting  generous cut  serged seams  collar  front zipper  and elastic wrists an',NULL,'N','4618153200','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-068-CS','TY210SWHSM00','CS',112.08,'DuPont  Tyvek  Lab Coat  Made from tear-resistant  lightweight  spunbonded olefin. Offers splash  dry-particulate  and bacteria protection. Disposable  low-linting lab coat features serged seams  collar  and front snap closure. No pockets. Bulk packed. Wh',NULL,'N','4618153200','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-070-CS','TY210SWHMD00','CS',112.08,'DuPont  Tyvek  Lab Coat  Made from tear-resistant  lightweight  spunbonded olefin. Offers splash  dry-particulate  and bacteria protection. Disposable  low-linting lab coat features serged seams  collar  and front snap closure. No pockets. Bulk packed. Wh',NULL,'N','4618153200','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-072-CS','TY210SWHLG00','CS',112.08,'DuPont  Tyvek  Lab Coat  Made from tear-resistant  lightweight  spunbonded olefin. Offers splash  dry-particulate  and bacteria protection. Disposable  low-linting lab coat features serged seams  collar  and front snap closure. No pockets. Bulk packed. Wh',NULL,'N','4618153200','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-074-CS','TY210SWHXL00','CS',112.08,'DuPont  Tyvek  Lab Coat  Made from tear-resistant  lightweight  spunbonded olefin. Offers splash  dry-particulate  and bacteria protection. Disposable  low-linting lab coat features serged seams  collar  and front snap closure. No pockets. Bulk packed. Wh',NULL,'N','4618153200','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-076-CS','TY210SWH2X00','CS',118.76,'DuPont  Tyvek  Lab Coat  Made from tear-resistant  lightweight  spunbonded olefin. Offers splash  dry-particulate  and bacteria protection. Disposable  low-linting lab coat features serged seams  collar  and front snap closure. No pockets. Bulk packed. Wh',NULL,'N','4618153200','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-078-CS','TY210SWH3X00','CS',116.63,'DuPont  Tyvek  Lab Coat  Made from tear-resistant  lightweight  spunbonded olefin. Offers splash  dry-particulate  and bacteria protection. Disposable  low-linting lab coat features serged seams  collar  and front snap closure. No pockets. Bulk packed. Wh',NULL,'N','4618153200','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-080-CS','TY210SWH4X00','CS',136,'DuPont  Tyvek  Lab Coat  Made from tear-resistant  lightweight  spunbonded olefin. Offers splash  dry-particulate  and bacteria protection. Disposable  low-linting lab coat features serged seams  collar  and front snap closure. No pockets. Bulk packed. Wh',NULL,'N','4618153200','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-082-CS','TY212SWHSM00','CS',114.6,'DuPont  Tyvek  Lab Coat  Made from lightweight  tear-resistant  spunbonded olefin. Offers splash  dry-particulate  and bacteria protection. Disposable  low-linting lab coat features serged seams  collar  and front snap closure. Two pockets. Bulk packed. W',NULL,'N','4618153200','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-084-CS','TY212SWHMD00','CS',114.6,'DuPont  Tyvek  Lab Coat  Made from lightweight  tear-resistant  spunbonded olefin. Offers splash  dry-particulate  and bacteria protection. Disposable  low-linting lab coat features serged seams  collar  and front snap closure. Two pockets. Bulk packed. W',NULL,'N','4618153200','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-086-CS','TY212SWHLG00','CS',114.6,'DuPont  Tyvek  Lab Coat  Made from lightweight  tear-resistant  spunbonded olefin. Offers splash  dry-particulate  and bacteria protection. Disposable  low-linting lab coat features serged seams  collar  and front snap closure. Two pockets. Bulk packed. W',NULL,'N','4618153200','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-088-CS','TY212SWHXL00','CS',114.6,'DuPont  Tyvek  Lab Coat  Made from lightweight  tear-resistant  spunbonded olefin. Offers splash  dry-particulate  and bacteria protection. Disposable  low-linting lab coat features serged seams  collar  and front snap closure. Two pockets. Bulk packed. W',NULL,'N','4618153200','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-090-CS','TY212SWH2X00','CS',121.47,'DuPont  Tyvek  Lab Coat  Made from lightweight  tear-resistant  spunbonded olefin. Offers splash  dry-particulate  and bacteria protection. Disposable  low-linting lab coat features serged seams  collar  and front snap closure. Two pockets. Bulk packed. W',NULL,'N','4618153200','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-092-CS','TY212SWH3X00','CS',128.75,'DuPont  Tyvek  Lab Coat  Made from lightweight  tear-resistant  spunbonded olefin. Offers splash  dry-particulate  and bacteria protection. Disposable  low-linting lab coat features serged seams  collar  and front snap closure. Two pockets. Bulk packed. W',NULL,'N','4618153200','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-094-CS','TY212SWH4X00','CS',139.07,'DuPont  Tyvek  Lab Coat  Made from lightweight  tear-resistant  spunbonded olefin. Offers splash  dry-particulate  and bacteria protection. Disposable  low-linting lab coat features serged seams  collar  and front snap closure. Two pockets. Bulk packed. W',NULL,'N','4618153200','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-097-CS','TY303SWHSM00','CS',148.81,'SHIRT TYVEK  SS SM CS50',NULL,'N','4618153200','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-099-CS','TY303SWHMD00','CS',148.81,'SHIRT TYVEK SS MED CS50',NULL,'N','4618153200','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-101-CS','TY303SWHLG00','CS',148.81,'SHIRT TYVEK SS LG CS50',NULL,'N','4618153200','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-103-CS','TY303SWHXL00','CS',148.81,'TYVEK SHIRT X-LARGE CS50',NULL,'N','4618153200','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-105-CS','TY303SWH2X00','CS',157.73,'SHIRT TYVEK SS 2XL CS50',NULL,'N','4618153200','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-107-CS','TY303SWH3X00','CS',167.18,'SHIRT TYVEK SS 3XL CS50',NULL,'N','4618153200','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','10010-111-CS','TY350SWHSM00','CS',123.44,'DuPont  Tyvek  Pants  Pants provide superior protection from light liquid splashes and dry particulates  including asbestos  lead paint  and dirt/dust. Fabricated to allow air and moisture to pass through. Breathable  tear- and abrasion-resistant. Elastic',NULL,'N','4618153200','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '07'),'Y');


    -- Fisher Scientific Hosted Catalog Items (Sample)

INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9640P1ABX','RP-9640-P1ABX','EA',213.23,'NEDL1-D1 Fusion Protein, Lab Vision; 50uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9640PABX','RP-9640-PABX','EA',315.67,'NEDL1-D1 Fusion Protein, Lab Vision; 100uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9641P1ABX','RP-9641-P1ABX','EA',213.23,'NEDL1-D2 Fusion Protein, Lab Vision; 50uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9641PABX','RP-9641-PABX','EA',315.67,'NEDL1-D2 Fusion Protein, Lab Vision; 100uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9642P1ABX','RP-9642-P1ABX','EA',213.23,'PABPN1 Fusion Protein, Lab Vision; 50uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9642PABX','RP-9642-PABX','EA',315.67,'PABPN1 Fusion Protein, Lab Vision; 100uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9644P1ABX','RP-9644-P1ABX','EA',213.23,'SMURF1-D2 Fusion Protein, Lab Vision; 50uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9644PABX','RP-9644-PABX','EA',315.67,'SMURF1-D2 Fusion Protein, Lab Vision; 100uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9645P1ABX','RP-9645-P1ABX','EA',213.23,'SMURF2-D1 Fusion Protein, Lab Vision; 50uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9645PABX','RP-9645-PABX','EA',315.67,'SMURF2-D1 Fusion Protein, Lab Vision; 100uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9646P1ABX','RP-9646-P1ABX','EA',213.23,'SMURF2-D2 Fusion Protein, Lab Vision; 50uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9646PABX','RP-9646-PABX','EA',315.67,'SMURF2-D2 Fusion Protein, Lab Vision; 100uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9648P1ABX','RP-9648-P1ABX','EA',213.23,'WWP1-D2 Fusion Protein, Lab Vision; 50uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9648PABX','RP-9648-PABX','EA',315.67,'WWP1-D2 Fusion Protein, Lab Vision; 100uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9649P1ABX','RP-9649-P1ABX','EA',213.23,'WWP1-D3 Fusion Protein, Lab Vision; 50uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9649PABX','RP-9649-PABX','EA',315.67,'WWP1-D3 Fusion Protein, Lab Vision; 100uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9650P1ABX','RP-9650-P1ABX','EA',213.23,'WWP1-D4 Fusion Protein, Lab Vision; 50uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9650PABX','RP-9650-PABX','EA',315.67,'WWP1-D4 Fusion Protein, Lab Vision; 100uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9651P1ABX','RP-9651-P1ABX','EA',213.23,'WWP2-D3 Fusion Protein, Lab Vision; 50uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9651PABX','RP-9651-PABX','EA',315.67,'WWP2-D3 Fusion Protein, Lab Vision; 100uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9652P1ABX','RP-9652-P1ABX','EA',213.23,'WWP2-D4 Fusion Protein, Lab Vision; 50uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9652PABX','RP-9652-PABX','EA',315.67,'WWP2-D4 Fusion Protein, Lab Vision; 100uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9653P1ABX','RP-9653-P1ABX','EA',213.23,'YAP1 Fusion Protein, Lab Vision; 50uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9653PABX','RP-9653-PABX','EA',315.67,'YAP1 Fusion Protein, Lab Vision; 100uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9654P1ABX','RP-9654-P1ABX','EA',213.23,'AIP1-D2 Fusion Protein., Lab Vision; 50uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9654PABX','RP-9654-PABX','EA',315.67,'AIP1-D2 Fusion Protein., Lab Vision; 100uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9655P1ABX','RP-9655-P1ABX','EA',213.23,'APBB1 Fusion Protein, Lab Vision; 50uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9655PABX','RP-9655-PABX','EA',315.67,'APBB1 Fusion Protein, Lab Vision; 100uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9656P1ABX','RP-9656-P1ABX','EA',213.23,'APBB2 Fusion Protein, Lab Vision; 50uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
INSERT INTO mm_catalog_item_t (CATALOG_ITEM_ID,OBJ_ID,VER_NBR,DISTRIBUTOR_NBR,MANUFACTURER_NBR,CATALOG_UNIT_OF_ISSUE_CD,CATALOG_PRC,CATALOG_DESC,RECYCLED_IND,WILLCALL_IND,UNSPSC_CD,ACTV_IND,LAST_UPDATE_DT,CATALOG_ID,DISPLAYABLE_IND)
VALUES(MM_CATALOG_ITEM_S.nextval,sys_guid(),'1','RP9656PABX','RP-9656-PABX','EA',315.67,'APBB2 Fusion Protein, Lab Vision; 100uL; Recombinant; Source: E.Coli 1/EA',NULL,'N','12352202','Y',CURRENT_DATE,(select catalog_id from mm_catalog_t where catalog_cd = '08'),'Y');
COMMIT;
update mm_catalog_item_t t set t.unspsc_cd= ''  where t.unspsc_cd=' ';
COMMIT;
update mm_catalog_item_t t set t.unspsc_cd=rtrim(ltrim(unspsc_cd));
COMMIT;
update mm_catalog_item_t t set t.catalog_desc=rtrim(ltrim(catalog_desc));

