INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
  VALUES('10',SYS_GUID(),1,'HEALTH CARE','Y',CURRENT_DATE);
INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
  VALUES('20',SYS_GUID(),1,'BREAKROOM SUPPLIES','Y',CURRENT_DATE);
INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
  VALUES('30',SYS_GUID(),1,'BUILDING MATERIALS','Y',CURRENT_DATE);
INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
  VALUES('40',SYS_GUID(),1,'LAWN & GARDEN','Y',CURRENT_DATE);
INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
  VALUES('50',SYS_GUID(),1,'CHEMICALS','Y',CURRENT_DATE);
INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
  VALUES('60',SYS_GUID(),1,'ELECTRICAL','Y',CURRENT_DATE);
INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
  VALUES('70',SYS_GUID(),1,'LABORATORY','Y',CURRENT_DATE);
INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
  VALUES('80',SYS_GUID(),1,'OFFICE PRODUCTS','Y',CURRENT_DATE);
INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
  VALUES('90',SYS_GUID(),1,'SHIPPING & MAILING','Y',CURRENT_DATE);
INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
  VALUES('91',SYS_GUID(),1,'PAINT SUPPLIES','Y',CURRENT_DATE);
INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
  VALUES('92',SYS_GUID(),1,'PLUMBING & HVAC','Y',CURRENT_DATE);
INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
  VALUES('93',SYS_GUID(),1,'HARDWARE & MATERIALS','Y',CURRENT_DATE);
INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
  VALUES('94',SYS_GUID(),1,'CYLINDER GASSES & ACCESSORIES','Y',CURRENT_DATE);
INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
  VALUES('95',SYS_GUID(),1,'SAFETY','Y',CURRENT_DATE);
INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
  VALUES('81',SYS_GUID(),1,'TONERS','Y',CURRENT_DATE);
INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
  VALUES('99',SYS_GUID(),1,'MSU MERCHANDISE','Y',CURRENT_DATE);
INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
  VALUES('96',SYS_GUID(),1,'CUSTODIAL','Y',CURRENT_DATE);
