INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, ACTV_IND, LAST_UPDATE_DT)
VALUES 
('heckam11', SYS_GUID(), '1', 'BARBARA', 'HECKAMAN', 'Y', CURRENT_DATE)
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, ACTV_IND, LAST_UPDATE_DT)
VALUES 
('pridgeo1', SYS_GUID(), '1', 'KARYN', 'PEARL', 'Y', CURRENT_DATE)
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, ACTV_IND, LAST_UPDATE_DT)
VALUES 
('rousej', SYS_GUID(), '1', 'JAN', 'ROUSE', 'Y', CURRENT_DATE)
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, ACTV_IND, LAST_UPDATE_DT)
VALUES 
('merriott', SYS_GUID(), '1', 'VIVIENNE', 'MERRIOTT', 'Y', CURRENT_DATE)
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, ACTV_IND, LAST_UPDATE_DT)
VALUES 
('georgep', SYS_GUID(), '1', 'PAM', 'GEORGE', 'Y', CURRENT_DATE)
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, ACTV_IND, LAST_UPDATE_DT)
VALUES 
('kokenake', SYS_GUID(), '1', 'KIM', 'KOKENAKES', 'Y', CURRENT_DATE)
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, ACTV_IND, LAST_UPDATE_DT)
VALUES 
('phillipm', SYS_GUID(), '1', 'MELINDA', 'PHILLIPS', 'Y', CURRENT_DATE)
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, ACTV_IND, LAST_UPDATE_DT)
VALUES 
('obriend', SYS_GUID(), '1', 'DENISE', 'OBRIEN', 'Y', CURRENT_DATE)
; 
