INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('JWEINZWE', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Jon Weinzweig' )
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('LIASCOTT', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Lia Scott' )
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('BGRICE', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Bill Grice' )
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('KPEARL', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Karyn Pearl' )
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('BSHUMAKE', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Boyd Shumaker' )
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('JANKING', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Janice King' )
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('SZKARLR', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Karl Reinking' )
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('SZMATSIS', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Alex Matsis' )
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('PLLACEY', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Phillip Lacey' )
;
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('KDESLOOVER', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Ken Desloover' )
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('KCATTON', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Kris Catton' )
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('NOREENM', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Noreen McIntyre' )
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('TDUMONT', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Tonya Dumont' )
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('NALAVI', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Naser Alavi' )
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('SCHNEPP', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Devin Schnepp' )
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('RPONRAJ', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Ram Ponrah' )
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('TERRYM', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Mark Terry' )
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('RSHRIVASTAVA', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Rahul Shrivastava' )
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('ASHLEYAM', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Amy Ashley' )
;
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('STR05', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Cain, Gayle' )
;
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('STR06', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Smock, Nancy' )
;
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('STR10', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Lyon, John C' )
;
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('STR14', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Michaels, Mary' )
;
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('STR15', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Rouse, Jan' )
;
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('STR17', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Riebow, Sandy' )
;
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('STR179', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Karle Delo' )
;
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('STR19', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Grice, William' )
;
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('STR24', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Hakes, Tom' )
;
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('STR26', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Dysinger, Darryl' )
;
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('STR29', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Cargill, Carrie' )
;
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('STR31', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Houser, Mike' )
;
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('STR32', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Lowe, Bill' )
;
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('STR35', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Carpenter, Doug' )
;
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('STR37', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Black, Elijan' )
;
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('STR41', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Smith, Rodney' )
;
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('STR58', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Botsford, Julie' )
;
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('WHITMA32', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Joshua Whitman' )
;
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('KGALLING', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Kay Cole' )
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('CJKIM', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Chris Kim' )
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('JDLAWREN', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Jen Carmichael' )
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('KATIEJAR', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Katie Jaramillo' )
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('CASEBEER', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Karen Casebeer' )
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('BGLEPENS', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Barbara Lepenske' )
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('ADMIN', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'Admin' )
; 
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, ACTV_IND, LAST_UPDATE_DT, NM )
VALUES 
('MMUSER', SYS_GUID(), '1', 'Y', CURRENT_DATE, 'MM User' )
; 
