-- UCD Data
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','16','Batteries',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','18','Carpentry, including Lumber',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','19','Door Stops',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','20','Fans',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','22','Cables and Cords',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','24','Adhesives',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','29','Oils, Lubricants, Fuels',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','32','Electrical',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','33','Fly Swatters',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','35','Tools',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','36','Hand Tools - Cutting',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','37','Hand Tools - Miscellaneous',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','38','Hand Tools - Wrenches',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','39','Hand Tools - Pliers',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','41','Garden Tools',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','45','Bulbs, Lamps, Flashlights',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','46','Lamps, Incandescent',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','51','Wraps',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','55','Tape',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','56','String and Twine',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','61','Gloves',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','90','Tubing',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'10','99','Miscellaneous',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'20','10','Chairs',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'20','20','Computer Accessories',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'20','30','Miscellaneous',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'20','40','Rainin Pipetters',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'30','10','Binders',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'30','20','Paper',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'30','30','Janitorial Paper',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'30','40','Index Cards and Guides',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'30','50','Folders',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'30','60','Miscellaneous',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'30','70','Toner Cartridges',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','00','Chemicals - Miscellaneous',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','01','Ignitors',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','02','Chemicals - Inorganic Reagent',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','03','Chemicals - Organic Reagent',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','04','Chemicals - Tax Free Alcohol',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','05','Chemicals - Scintillation Cocktails',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','06','Microscope Bulbs',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','07','Gloves',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','13','Gases',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','14','Protective Clothing',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','18','Corks & Rubber Stoppers',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','1A','Tapes & Dispensers',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','20','Glassware - Beakers',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','23','Glassware - Bottles',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','26','Glassware - Cover Glass - Slides',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','29','Glassware - Cylinders',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','31','Glassware - Flasks',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','33','Glassware - Funnels',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','35','Glassware - Miscellaneous',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','37','Glassware - Pipettes',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','39','Glassware - Tubes',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','41','Glassware - Vials',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','46','Millipore Filters',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','48','Measuring Tools',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','50','Plasticware Miscellaneous',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','53','General Supplies',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','54','Writing and Marking Supplies',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','55','Filters',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','57','Paper - Filter and Weighing',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','59','Furniture',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','60','Brushes',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','70','Plasticware Bottles and Vials',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','71','Ice',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','73','Plasticware Dishes',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','76','Plasticware Flasks',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','79','Plasticware Pipettes',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','82','Plasticware Pipet Tips',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','85','Pipetman Pipettes',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','88','Plasticware Tubes',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'40','99','Miscellaneous',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','40','Tools',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','48','General Aid Supplies',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','77','Physical Assistance Aids',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','80','Furniture',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','84','Clothing',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','86','Gloves',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'50','99','Miscellaneous',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'60','00','Chemicals & Additives',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'60','10','Tools (also see Hardware)',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'60','99','Miscellaneous',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'63','19','Brushes and Sponges',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'63','20','Personal Care Products',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'63','26','Cleansers, Disinfectants and Soaps',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'63','31','Chemicals',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'63','33','Cleaning Tools and Supplies',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'63','42','Gloves',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'63','45','Cleaning Products and Supplies',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'63','53','Kimwipes and Rags',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'63','77','Paper Products',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'63','99','Cans',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'68','82','Food Service',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'68','85','Food Preparation',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'68','88','Food Storage',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'70','13','Accessories (Mice, Keyboard Trays, etc.)',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'70','15','Cleaning Supplies',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'70','16','Adapters',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'70','19','Switches and Other Computer Hardware',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'70','21','Printer Toner',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'70','23','Printer Cartridges',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'70','30','Disks, CDs, and Tapes (Blank)',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'70','31','Diskettes - 3 1/2',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'70','32','Diskettes - 5 1/4',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'70','33','Diskettes - 8',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'70','40','Cables - Miscellaneous',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'70','41','Cables - Printer',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'70','42','Cables - Serial/RS232',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'70','43','Cables - Centronics',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'70','44','Cables - Video',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'70','46','Cables - SCSI',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'70','47','Cables - Unshielded',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'70','48','Cables - USB',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'70','49','Cables - Accessories',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'70','77','Software',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'70','99','Miscellaneous',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','00','Furniture',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','04','Accessories',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','08','Desktop and Typewriter Supplies',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','0A','Furniture - Chairs/Stools',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','0B','Furniture - Bookcases/Files/Stor Cabinet',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','11','Paper',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','12','Post-Its',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','13','Glue & Adhesives',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','14','Forms',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','15','Labels',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','16','Envelopes',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','17','Paper Letter Size',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','18','Paper Legal Size',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','19','Filing Supplies',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','1A','Labels - Round',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','1B','Labels - File Folder',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','20','Paper Punched',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','21','Paper Special (Astrobrite, Index, etc,)',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','25','Calendars',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','26','Cleaning Items',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','28','Copier Supplies',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','29','Fax Supplies',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','2A','Binder Filing Supplies',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','33','Ribbons',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','35','Hole Punches',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','36','Scissors',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','38','Clocks and Timers',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','41','Tape - Miscellaneous',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','43','Dividers, Guides and Indexes',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','44','Paper - Bond, Copier and Rag Bond',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','45','Paper - Astrobright and Index',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','46','Paper - Index Cards',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','47','Paper - Computer',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','48','Paper - Quadrille and Scratch Pads',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','4A','Tape - Embossing/Labeling',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','4B','Tape - Filament/Masking/Scotch',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','50','Paper - Fax',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','51','Binders - Pressboard',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','54','Folders and Expanding Pockets',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','57','Erasers',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','5A','Binders - Vinyl',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','63','Books',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','67','Staplers, Staples and Staple Removers',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','69','Rubber Bands',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','71','Tags Manila and Marking',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','73','Correction Fluid and Tape',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','75','Clips and Fasteners',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','7A','Tape Dispensers',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','7B','Spirit Masters/Transparencies',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','81','Pencil Sharpeners',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','83','Sheet Protectors and Reinforcements',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','84','Pendaflex Tabs/Inserts',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','90','Rulers',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','93','Sorting Aids',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','95','Cartridges - Toner',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','96','Cartridges - DeskJet/InkJet',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'71','99','Miscellaneous',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'72','10','Pencils and Leads',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'72','20','Ballpoint Pens and Refills',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'72','30','Highlighters and Markers',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'72','40','Felt, Nylon and Polyester Tip Pens',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'72','50','Rolling Ball Pens',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'72','60','Rubber Stamps, Inks and Pads',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'72','70','Miscellaneous',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'72','80','Chalk and Whiteboard Supplies',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'99','99','Miscellaneous',NULL,'Y',CURRENT_DATE);

-- MSU Data
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'63','9A','Miscellaneous',NULL,'Y',CURRENT_DATE);

INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'68','9A','Miscellaneous',NULL,'Y',CURRENT_DATE);

INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'80','10','Ears',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'80','50','Miscellaneous',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'80','60','Pants',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'80','70','Shirt',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'80','80','Sweats',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'80','90','Wrist',NULL,'Y',CURRENT_DATE);
INSERT INTO mm_catalog_subgroup_t (CATALOG_SUBGROUP_ID,OBJ_ID,VER_NBR,CATALOG_GROUP_CD,CATALOG_SUBGROUP_CD,CATALOG_SUBGROUP_DESC,PRIOR_CATALOG_SUBGROUP_ID,ACTV_IND,LAST_UPDATE_DT)
VALUES(MM_CATALOG_SUBGROUP_S.NEXTVAL,SYS_GUID(),1,'80','99','Wrist',NULL,'Y',CURRENT_DATE);
