INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XAX00151EA','https://fscimage.fishersci.com/msds/08575.htm','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XAX00153EA','https://fscimage.fishersci.com/msds/08576.htm','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XBX00109DA','https://fscimage.fishersci.com/msds/08578.htm','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XBX00109EA','https://fscimage.fishersci.com/msds/08578.htm','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XBX00109EE','https://www.fishersci.com/itemdetail?catnum=XBX00109EE','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XBX00110DA','https://fscimage.fishersci.com/msds/04316.htm','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XBX00110EA','https://fscimage.fishersci.com/msds/04316.htm','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XBX00111DA','https://fscimage.fishersci.com/msds/02500.htm','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XBX00111EA','https://fscimage.fishersci.com/msds/02500.htm','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XBX00112DA','https://fscimage.fishersci.com/msds/04315.htm','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XBX00112EA','https://fscimage.fishersci.com/msds/04315.htm','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XBX00112EE','https://www.fishersci.com/itemdetail?catnum=XBX00112EE','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XBX00138CB','https://fscimage.fishersci.com/msds/95424.htm','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XBX00138DA','https://fscimage.fishersci.com/msds/95424.htm','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XBX00321EA','https://www.fishersci.com/itemdetail?catnum=XBX00321EA','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XBX00327DA','https://fscimage.fishersci.com/msds/08579.htm','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XBX00327EA','https://fscimage.fishersci.com/msds/08579.htm','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'Z02OX952200','https://www.fishersci.com/itemdetail?catnum=Z02OX952200','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'Z11500','https://fscimage.fishersci.com/msds/88125.htm','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'Z12500','https://fscimage.fishersci.com/msds/45375.htm','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'S930002','https://maxbuyer.officemax.com/shop/images/products/imgs_180/100001.jpg','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'S930010','https://maxbuyer.officemax.com/shop/images/products/imgs_180/100001.jpg','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'S930011','https://maxbuyer.officemax.com/shop/images/products/imgs_180/100001.jpg','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'S930020','https://maxbuyer.officemax.com/shop/images/products/imgs_180/100001.jpg','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'S948337','https://shop.boiseoffice.com/shop/images/products/imgs_180/100001.jpg','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'S948349','https://shop.boiseoffice.com/shop/images/products/imgs_180/100001.jpg','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'S948473','https://shop.boiseoffice.com/shop/images/products/imgs_180/100001.jpg','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'S7Q2020A','https://maxbuyer.officemax.com/shop/images/products/imgs_180/100001.jpg','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'S7VZ01049','https://maxbuyer.officemax.com/shop/images/products/imgs_180/139593.jpg','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'S7VZ01094','https://maxbuyer.officemax.com/shop/images/products/imgs_180/139594.jpg','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'S7VZ01182','https://maxbuyer.officemax.com/shop/images/products/imgs_180/100001.jpg','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'S900210','https://maxbuyer.officemax.com/shop/images/products/imgs_180/100001.jpg','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'S900211','https://maxbuyer.officemax.com/shop/images/products/imgs_180/100001.jpg','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'S7MC420','https://maxbuyer.officemax.com/shop/images/products/imgs_180/100001.jpg','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'S7CD30','https://maxbuyer.officemax.com/shop/images/products/imgs_180/100001.jpg','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'S7CDW-320','https://maxbuyer.officemax.com/shop/images/products/imgs_180/85784.jpg','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'S795079','https://maxbuyer.officemax.com/shop/images/products/imgs_180/100001.jpg','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'S795101','https://maxbuyer.officemax.com/shop/images/products/imgs_180/140292.jpg','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'S795160','https://maxbuyer.officemax.com/shop/images/products/imgs_180/136011.jpg','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'S795169','https://maxbuyer.officemax.com/shop/images/products/imgs_180/136011.jpg','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XG497-IV','http://www.vwrsp.com/catalog/product/info/index.cgi?catalog_number=XG497-IV','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XG497-MM','http://www.vwrsp.com/catalog/product/info/index.cgi?catalog_number=XG497-MM','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XG498-I','http://www.vwrsp.com/catalog/product/info/index.cgi?catalog_number=XG498-I','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XG498-II','http://www.vwrsp.com/catalog/product/info/index.cgi?catalog_number=XG498-II','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XG498-III','http://www.vwrsp.com/catalog/product/info/index.cgi?catalog_number=XG498-III','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XG498-IV','http://www.vwrsp.com/catalog/product/info/index.cgi?catalog_number=XG498-IV','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XG498-MM','http://www.vwrsp.com/catalog/product/info/index.cgi?catalog_number=XG498-MM','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XG5550-I','http://www.vwrsp.com/catalog/product/info/index.cgi?catalog_number=XG5550-I','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XG5550-II','http://www.vwrsp.com/catalog/product/info/index.cgi?catalog_number=XG5550-II','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XG5550-IV','http://www.vwrsp.com/catalog/product/info/index.cgi?catalog_number=XG5550-IV','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XG5550-MM','http://www.vwrsp.com/catalog/product/info/index.cgi?catalog_number=XG5550-MM','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XG5550-V','http://www.vwrsp.com/catalog/product/info/index.cgi?catalog_number=XG5550-V','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XG4867-III','http://www.vwrsp.com/catalog/product/info/index.cgi?catalog_number=XG4867-III','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XG4867-IV','http://www.vwrsp.com/catalog/product/info/index.cgi?catalog_number=XG4867-IV','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XG4867-MM','http://www.vwrsp.com/catalog/product/info/index.cgi?catalog_number=XG4867-MM','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XG4868-I','http://www.vwrsp.com/catalog/product/info/index.cgi?catalog_number=XG4868-I','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XG4868-II','http://www.vwrsp.com/catalog/product/info/index.cgi?catalog_number=XG4868-II','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XG4868-III','http://www.vwrsp.com/catalog/product/info/index.cgi?catalog_number=XG4868-III','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XG4868-IV','http://www.vwrsp.com/catalog/product/info/index.cgi?catalog_number=XG4868-IV','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
INSERT INTO MM_CATALOG_IMAGE_T (OBJ_ID,VER_NBR,CATALOG_IMAGE_NM,CATALOG_IMAGE_URL,ACTV_IND,LAST_UPDATE_DT,CATALOG_IMAGE_ID)
VALUES(SYS_GUID(),1,'XG4868-MM','http://www.vwrsp.com/catalog/product/info/index.cgi?catalog_number=XG4868-MM','Y',CURRENT_DATE,MM_CATALOG_IMAGE_S.nextval);
