INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, CUSTOMER_PASSWORD, ACTV_IND, LAST_UPDATE_DT)
   VALUES('selke', SYS_GUID(), '1', 'Susan', 'Selke', NULL, 'Y', CURRENT_DATE);
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, CUSTOMER_PASSWORD, ACTV_IND, LAST_UPDATE_DT)
   VALUES('shelle', SYS_GUID(), '1', 'Kevin', 'Shelle', NULL, 'Y', CURRENT_DATE);
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, CUSTOMER_PASSWORD, ACTV_IND, LAST_UPDATE_DT)
   VALUES('berding', SYS_GUID(), '1', 'Thomas', 'Berding', NULL, 'Y', CURRENT_DATE);
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, CUSTOMER_PASSWORD, ACTV_IND, LAST_UPDATE_DT)
   VALUES('hawley', SYS_GUID(), '1', 'Martin', 'Hawley', NULL, 'Y', CURRENT_DATE);
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, CUSTOMER_PASSWORD, ACTV_IND, LAST_UPDATE_DT)
   VALUES('grotjohn', SYS_GUID(), '1', 'Timothy', 'Grotjohn', NULL, 'Y', CURRENT_DATE);
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, CUSTOMER_PASSWORD, ACTV_IND, LAST_UPDATE_DT)
   VALUES('wade', SYS_GUID(), '1', 'Peggy', 'Wade', NULL, 'Y', CURRENT_DATE);
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, CUSTOMER_PASSWORD, ACTV_IND, LAST_UPDATE_DT)
   VALUES('mccracke', SYS_GUID(), '1', 'John', 'McCracken', NULL, 'Y', CURRENT_DATE);
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, CUSTOMER_PASSWORD, ACTV_IND, LAST_UPDATE_DT)
   VALUES('thomasho', SYS_GUID(), '1', 'Michael', 'Thomashow', NULL, 'Y', CURRENT_DATE);
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, CUSTOMER_PASSWORD, ACTV_IND, LAST_UPDATE_DT)
   VALUES('haywood', SYS_GUID(), '1', 'Joseph', 'Haywood', NULL, 'Y', CURRENT_DATE);
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, CUSTOMER_PASSWORD, ACTV_IND, LAST_UPDATE_DT)
   VALUES('hamilton', SYS_GUID(), '1', 'Deanne', 'Hamilton', NULL, 'Y', CURRENT_DATE);
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, CUSTOMER_PASSWORD, ACTV_IND, LAST_UPDATE_DT)
   VALUES('plaut', SYS_GUID(), '1', 'Karen', 'Plaut', NULL, 'Y', CURRENT_DATE);
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, CUSTOMER_PASSWORD, ACTV_IND, LAST_UPDATE_DT)
   VALUES('kells', SYS_GUID(), '1', 'James', 'Kells', NULL, 'Y', CURRENT_DATE);
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, CUSTOMER_PASSWORD, ACTV_IND, LAST_UPDATE_DT)
   VALUES('goebel', SYS_GUID(), '1', 'Steven', 'Goebel', NULL, 'Y', CURRENT_DATE);
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, CUSTOMER_PASSWORD, ACTV_IND, LAST_UPDATE_DT)
   VALUES('mason', SYS_GUID(), '1', 'Ronald', 'Mason', NULL, 'Y', CURRENT_DATE);
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, CUSTOMER_PASSWORD, ACTV_IND, LAST_UPDATE_DT)
   VALUES('dunlap', SYS_GUID(), '1', 'James', 'Dunlap', NULL, 'Y', CURRENT_DATE);
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, CUSTOMER_PASSWORD, ACTV_IND, LAST_UPDATE_DT)
   VALUES('gosselin', SYS_GUID(), '1', 'Gaston', 'gosselin', NULL, 'Y', CURRENT_DATE);
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, CUSTOMER_PASSWORD, ACTV_IND, LAST_UPDATE_DT)
   VALUES('ellerhor', SYS_GUID(), '1', 'Robert', 'Ellerhorst', NULL, 'Y', CURRENT_DATE);
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, CUSTOMER_PASSWORD, ACTV_IND, LAST_UPDATE_DT)
   VALUES('daoust', SYS_GUID(), '1', 'Ruthann', 'daoust', NULL, 'Y', CURRENT_DATE);
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, CUSTOMER_PASSWORD, ACTV_IND, LAST_UPDATE_DT)
   VALUES('procopio', SYS_GUID(), '1', 'Guy', 'procopio', NULL, 'Y', CURRENT_DATE);
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, CUSTOMER_PASSWORD, ACTV_IND, LAST_UPDATE_DT)
   VALUES('hull', SYS_GUID(), '1', 'Mike', 'hull', NULL, 'Y', CURRENT_DATE);
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, CUSTOMER_PASSWORD, ACTV_IND, LAST_UPDATE_DT)
   VALUES('corley', SYS_GUID(), '1', 'Karen', 'corley', NULL, 'Y', CURRENT_DATE);
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, CUSTOMER_PASSWORD, ACTV_IND, LAST_UPDATE_DT)
   VALUES('simmons1', SYS_GUID(), '1', 'Mark', 'Simmons', NULL, 'Y', CURRENT_DATE);
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, CUSTOMER_PASSWORD, ACTV_IND, LAST_UPDATE_DT)
   VALUES('nelson', SYS_GUID(), '1', 'Brenda', 'nelson', NULL, 'Y', CURRENT_DATE);
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, CUSTOMER_PASSWORD, ACTV_IND, LAST_UPDATE_DT)
   VALUES('noud', SYS_GUID(), '1', 'Carol', 'noud', NULL, 'Y', CURRENT_DATE);
INSERT INTO MM_CUSTOMER_T ( PRNCPL_NM, OBJ_ID, VER_NBR, FIRST_NM, LAST_NM, CUSTOMER_PASSWORD, ACTV_IND, LAST_UPDATE_DT)
   VALUES('marcis', SYS_GUID(), '1', 'Pamela', 'marcis', NULL, 'Y', CURRENT_DATE);
