INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
VALUES('10',SYS_GUID(),1,'Hardware','Y',CURRENT_DATE);
INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
VALUES('20',SYS_GUID(),1,'Ergonomic Aids and Products','Y',CURRENT_DATE);
INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
VALUES('30',SYS_GUID(),1,'Recycle Products','Y',CURRENT_DATE);
INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
VALUES('40',SYS_GUID(),1,'Laboratory Products','Y',CURRENT_DATE);
INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
VALUES('50',SYS_GUID(),1,'Medical Products','Y',CURRENT_DATE);
INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
VALUES('60',SYS_GUID(),1,'Agriculture & Horticulture','Y',CURRENT_DATE);
INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
VALUES('63',SYS_GUID(),1,'Janitorial','Y',CURRENT_DATE);
INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
VALUES('68',SYS_GUID(),1,'Food Service and Handling','Y',CURRENT_DATE);
INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
VALUES('70',SYS_GUID(),1,'Computer Products','Y',CURRENT_DATE);
INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
VALUES('71',SYS_GUID(),1,'Office Products','Y',CURRENT_DATE);
INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
VALUES('72',SYS_GUID(),1,'Office - Writing and Marking','Y',CURRENT_DATE);
INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
VALUES('80',SYS_GUID(),1,'Swag','Y',CURRENT_DATE);
INSERT INTO mm_catalog_group_t (CATALOG_GROUP_CD,OBJ_ID,VER_NBR,CATALOG_GROUP_NM,ACTV_IND,LAST_UPDATE_DT)
VALUES('99',SYS_GUID(),1,'Shipouts','Y',CURRENT_DATE);
