INSERT INTO  MM_DISPOSITION_T (DISPOSITION_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT) 
VALUES ('HAZARDOUS', SYS_GUID(),1,'HAZARDOUS DISPOSE OF PROPERLY','Y',CURRENT_DATE)
;
INSERT INTO  MM_DISPOSITION_T (DISPOSITION_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT) 
VALUES ('TRASH', SYS_GUID(),1,'PLACE IN TRASH','Y',CURRENT_DATE)
;
INSERT INTO  MM_DISPOSITION_T (DISPOSITION_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT) 
VALUES ('RTRN_VENDOR', SYS_GUID(),1,'RETURN TO VENDOR','Y',CURRENT_DATE)
;
INSERT INTO  MM_DISPOSITION_T (DISPOSITION_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT) 
VALUES ('RTRN_SHELF', SYS_GUID(),1,'RETURN TO WAREHOUSE SHELF','Y',CURRENT_DATE)
;
