INSERT INTO mm_markup_t (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_ORG_CD,MARKUP_ACCOUNT_NBR,MARKUP_FIXED_AMT,MARKUP_BEGIN_DT,MARKUP_END_DT,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('A01',sys_guid(),1,'SUPPLY EXPRESS ACCOUNT MARK-UP','SUPPLY EXPRESS ACCOUNT MARK-UP',0,NULL,'3',NULL,'CSL1241',NULL,NULL,NULL,'01','Y',CURRENT_DATE);
INSERT INTO mm_markup_t (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_ORG_CD,MARKUP_ACCOUNT_NBR,MARKUP_FIXED_AMT,MARKUP_BEGIN_DT,MARKUP_END_DT,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('A02',sys_guid(),1,'MATERIEL MANAGEMENT ORGANIZATION MARKUP','MATERIEL MANAGEMENT ORGANIZATION MARKUP',0,NULL,'3','ACMM',NULL,NULL,NULL,NULL,'02','Y',CURRENT_DATE);
INSERT INTO mm_markup_t (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_ORG_CD,MARKUP_ACCOUNT_NBR,MARKUP_FIXED_AMT,MARKUP_BEGIN_DT,MARKUP_END_DT,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('A05',sys_guid(),1,'COMMODITY FIXED PRICE','COMMODITY FIXED PRICE',NULL,NULL,NULL,NULL,NULL,5,TO_DATE('2008-01-01', 'YYYY-MM-DD'),TO_DATE('2009-12-31', 'YYYY-MM-DD'),'04','Y',CURRENT_DATE);
INSERT INTO mm_markup_t (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_ORG_CD,MARKUP_ACCOUNT_NBR,MARKUP_FIXED_AMT,MARKUP_BEGIN_DT,MARKUP_END_DT,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('W08',sys_guid(),1,'WAREHOUSE 8 PERCENT','WAREHOUSE DEFAULT 8 PERCENT MARKUP',0.08,'63',NULL,NULL,NULL,NULL,TO_DATE('2008-01-01', 'YYYY-MM-DD'),TO_DATE('2009-12-31', 'YYYY-MM-DD'),'07','Y',CURRENT_DATE);
-- UCD Markup Rates
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('1016',SYS_GUID(),1,'HARDWARE BATTERIES','HARDWARE BATTERIES',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('1018',SYS_GUID(),1,'HARDWARE CARPENTRY, INCLUDING LUMBER','HARDWARE CARPENTRY, INCLUDING LUMBER',0.13,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('1019',SYS_GUID(),1,'HARDWARE DOOR STOPS','HARDWARE DOOR STOPS',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('1024',SYS_GUID(),1,'HARDWARE ADHESIVES','HARDWARE ADHESIVES',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('1029',SYS_GUID(),1,'HARDWARE OILS, LUBRICANTS, FUELS','HARDWARE OILS, LUBRICANTS, FUELS',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('1032',SYS_GUID(),1,'HARDWARE ELECTRICAL','HARDWARE ELECTRICAL',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('1033',SYS_GUID(),1,'HARDWARE FLY SWATTERS','HARDWARE FLY SWATTERS',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('1036',SYS_GUID(),1,'HARDWARE HAND TOOLS - CUTTING','HARDWARE HAND TOOLS - CUTTING',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('1037',SYS_GUID(),1,'HARDWARE HAND TOOLS - MISCELLANEOUS','HARDWARE HAND TOOLS - MISCELLANEOUS',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('1041',SYS_GUID(),1,'HARDWARE GARDEN TOOLS','HARDWARE GARDEN TOOLS',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('1045',SYS_GUID(),1,'HARDWARE BULBS, LAMPS, FLASHLIGHTS','HARDWARE BULBS, LAMPS, FLASHLIGHTS',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('1046',SYS_GUID(),1,'HARDWARE LAMPS, INCANDESCENT','HARDWARE LAMPS, INCANDESCENT',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('1051',SYS_GUID(),1,'HARDWARE WRAPS','HARDWARE WRAPS',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('1055',SYS_GUID(),1,'HARDWARE TAPE','HARDWARE TAPE',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('2030',SYS_GUID(),1,'ERGONOMIC AIDS & PRODUCTS MISCELLANEOUS','ERGONOMIC AIDS & PRODUCTS MISCELLANEOUS',0.12,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('3010',SYS_GUID(),1,'RECYCLED PRODUCTS BINDERS','RECYCLED PRODUCTS BINDERS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('3020',SYS_GUID(),1,'RECYCLED PRODUCTS PAPER','RECYCLED PRODUCTS PAPER',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('3050',SYS_GUID(),1,'RECYCLED PRODUCTS FOLDERS','RECYCLED PRODUCTS FOLDERS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('4000',SYS_GUID(),1,'LABORATORY CHEMICALS - MISCELLANEOUS','LABORATORY CHEMICALS - MISCELLANEOUS',0,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('4004',SYS_GUID(),1,'LABORATORY CHEMICALS - TAX FREE ALCOHOL','LABORATORY CHEMICALS - TAX FREE ALCOHOL',0.13,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('4007',SYS_GUID(),1,'LABORATORY GLOVES','LABORATORY GLOVES',0.15,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('4013',SYS_GUID(),1,'LABORATORY GASES','LABORATORY GASES',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('4020',SYS_GUID(),1,'LABORATORY GLASSWARE - BEAKERS','LABORATORY GLASSWARE - BEAKERS',0.13,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('4026',SYS_GUID(),1,'LABORATORY GLASSWARE COVER GLASS SLIDES','LABORATORY GLASSWARE COVER GLASS SLIDES',0.13,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('4031',SYS_GUID(),1,'LABORATORY GLASSWARE - FLASKS','LABORATORY GLASSWARE - FLASKS',0.13,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('4041',SYS_GUID(),1,'LABORATORY GLASSWARE - VIALS','LABORATORY GLASSWARE - VIALS',0.13,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('4053',SYS_GUID(),1,'LABORATORY GENERAL SUPPLIES','LABORATORY GENERAL SUPPLIES',0.13,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('4057',SYS_GUID(),1,'LABORATORY PAPER - FILTER AND WEIGHING','LABORATORY PAPER - FILTER AND WEIGHING',0.13,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('4060',SYS_GUID(),1,'LABORATORY BRUSHES','LABORATORY BRUSHES',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('4070',SYS_GUID(),1,'LABORATORY PLASTICWARE BOTTLES AND VIALS','LABORATORY PLASTICWARE BOTTLES AND VIALS',0.13,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('4071',SYS_GUID(),1,'LABORATORY ICE','LABORATORY ICE',0.222,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('4082',SYS_GUID(),1,'LABORATORY PLASTICWARE PIPET TIPS','LABORATORY PLASTICWARE PIPET TIPS',0.15,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('4085',SYS_GUID(),1,'LABORATORY PIPETMAN PIPETTES','LABORATORY PIPETMAN PIPETTES',0.12,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('4088',SYS_GUID(),1,'LABORATORY PLASTICWARE TUBES','LABORATORY PLASTICWARE TUBES',0.13,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('5040',SYS_GUID(),1,'MEDICAL TOOLS','MEDICAL TOOLS',0.13,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('5048',SYS_GUID(),1,'MEDICAL GENERAL AID SUPPLIES','MEDICAL GENERAL AID SUPPLIES',0.13,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('5084',SYS_GUID(),1,'MEDICAL CLOTHING','MEDICAL CLOTHING',0.13,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('5099',SYS_GUID(),1,'MEDICAL MISCELLANEOUS','MEDICAL MISCELLANEOUS',0.13,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('6000',SYS_GUID(),1,'AGRICULTURE & HORTICULTURE CHEMICALS','AGRICULTURE & HORTICULTURE CHEMICALS',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('6099',SYS_GUID(),1,'AGRICULTURE & HORTICULTURE MISCELLANEOUS','AGRICULTURE & HORTICULTURE MISCELLANEOUS',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('6319',SYS_GUID(),1,'JANITORIAL BRUSHES AND SPONGES','JANITORIAL BRUSHES AND SPONGES',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('6326',SYS_GUID(),1,'JANITORIAL CLEANSERS, DISINFECTANTS ','JANITORIAL CLEANSERS, DISINFECTANTS',0.12,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('6331',SYS_GUID(),1,'JANITORIAL CHEMICALS','JANITORIAL CHEMICALS',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('6333',SYS_GUID(),1,'JANITORIAL CLEANING TOOLS AND SUPPLIES','JANITORIAL CLEANING TOOLS AND SUPPLIES',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('6342',SYS_GUID(),1,'JANITORIAL GLOVES','JANITORIAL GLOVES',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('6345',SYS_GUID(),1,'JANITORIAL CLEANING PRODUCTS & SUPPLIES','JANITORIAL CLEANING PRODUCTS & SUPPLIES',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('6353',SYS_GUID(),1,'JANITORIAL KIMWIPES AND RAGS','JANITORIAL KIMWIPES AND RAGS',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('6377',SYS_GUID(),1,'JANITORIAL PAPER PRODUCTS','JANITORIAL PAPER PRODUCTS',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('6882',SYS_GUID(),1,'FOOD SERVICE AND HANDLING FOOD SERVICE','FOOD SERVICE AND HANDLING FOOD SERVICE',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('6888',SYS_GUID(),1,'FOOD SERVICE AND HANDLING FOOD STORAGE','FOOD SERVICE AND HANDLING FOOD STORAGE',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7013',SYS_GUID(),1,'COMPUTER ACCESSORIES (MICE, KEYBOARDS)','COMPUTER ACCESSORIES (MICE, KEYBOARDS)',0.13,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7016',SYS_GUID(),1,'COMPUTER ADAPTERS','COMPUTER ADAPTERS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7019',SYS_GUID(),1,'COMPUTER SWITCHES AND COMPUTER HARDWARE','COMPUTER SWITCHES AND COMPUTER HARDWARE',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7021',SYS_GUID(),1,'COMPUTER PRINTER TONER','COMPUTER PRINTER TONER',0,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7023',SYS_GUID(),1,'COMPUTER PRINTER CARTRIDGES','COMPUTER PRINTER CARTRIDGES',0,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7030',SYS_GUID(),1,'COMPUTER DISKS, CDS, AND TAPES (BLANK)','COMPUTER DISKS, CDS, AND TAPES (BLANK)',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7031',SYS_GUID(),1,'COMPUTER DISKETTES - 3 1/2','COMPUTER DISKETTES - 3 1/2',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7040',SYS_GUID(),1,'COMPUTER CABLES - MISCELLANEOUS','COMPUTER CABLES - MISCELLANEOUS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7099',SYS_GUID(),1,'COMPUTER MISCELLANEOUS','COMPUTER MISCELLANEOUS',0.12,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7100',SYS_GUID(),1,'OFFICE FURNITURE','OFFICE FURNITURE',0.12,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7104',SYS_GUID(),1,'OFFICE ACCESSORIES','OFFICE ACCESSORIES',0.12,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7108',SYS_GUID(),1,'OFFICE DESKTOP AND TYPEWRITER SUPPLIES','OFFICE DESKTOP AND TYPEWRITER SUPPLIES',0.12,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7111',SYS_GUID(),1,'OFFICE PAPER','OFFICE PAPER',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7112',SYS_GUID(),1,'OFFICE POST-ITS','OFFICE POST-ITS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7113',SYS_GUID(),1,'OFFICE GLUE & ADHESIVES','OFFICE GLUE & ADHESIVES',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7114',SYS_GUID(),1,'OFFICE FORMS','OFFICE FORMS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7115',SYS_GUID(),1,'OFFICE LABELS','OFFICE LABELS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7116',SYS_GUID(),1,'OFFICE ENVELOPES','OFFICE ENVELOPES',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7119',SYS_GUID(),1,'OFFICE FILING SUPPLIES','OFFICE FILING SUPPLIES',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('711A',SYS_GUID(),1,'OFFICE LABELS - ROUND','OFFICE LABELS - ROUND',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('711B',SYS_GUID(),1,'OFFICE LABELS - FILE FOLDER','OFFICE LABELS - FILE FOLDER',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7125',SYS_GUID(),1,'OFFICE CALENDARS','OFFICE CALENDARS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7126',SYS_GUID(),1,'OFFICE CLEANING ITEMS','OFFICE CLEANING ITEMS',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7128',SYS_GUID(),1,'OFFICE COPIER SUPPLIES','OFFICE COPIER SUPPLIES',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7129',SYS_GUID(),1,'OFFICE FAX SUPPLIES','OFFICE FAX SUPPLIES',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('712A',SYS_GUID(),1,'OFFICE BINDER FILING SUPPLIES','OFFICE BINDER FILING SUPPLIES',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7133',SYS_GUID(),1,'OFFICE RIBBONS','OFFICE RIBBONS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7135',SYS_GUID(),1,'OFFICE HOLE PUNCHES','OFFICE HOLE PUNCHES',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7138',SYS_GUID(),1,'OFFICE CLOCKS AND TIMERS','OFFICE CLOCKS AND TIMERS',0.13,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7141',SYS_GUID(),1,'OFFICE TAPE - MISCELLANEOUS','OFFICE TAPE - MISCELLANEOUS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7143',SYS_GUID(),1,'OFFICE DIVIDERS, GUIDES AND INDEXES','OFFICE DIVIDERS, GUIDES AND INDEXES',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7144',SYS_GUID(),1,'OFFICE PAPER - BOND, COPIER AND RAG BOND','OFFICE PAPER - BOND, COPIER AND RAG BOND',0.13,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7145',SYS_GUID(),1,'OFFICE PAPER - ASTROBRIGHT AND INDEX','OFFICE PAPER - ASTROBRIGHT AND INDEX',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7146',SYS_GUID(),1,'OFFICE PAPER - INDEX CARDS','OFFICE PAPER - INDEX CARDS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7148',SYS_GUID(),1,'OFFICE PAPER - QUADRILLE AND SCRATCH PAD','OFFICE PAPER - QUADRILLE AND SCRATCH PAD',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('714A',SYS_GUID(),1,'OFFICE TAPE - EMBOSSING/LABELING','OFFICE TAPE - EMBOSSING/LABELING',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('714B',SYS_GUID(),1,'OFFICE TAPE - FILAMENT/MASKING/SCOTCH','OFFICE TAPE - FILAMENT/MASKING/SCOTCH',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7150',SYS_GUID(),1,'OFFICE PAPER - FAX','OFFICE PAPER - FAX',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7151',SYS_GUID(),1,'OFFICE BINDERS - PRESSBOARD','OFFICE BINDERS - PRESSBOARD',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7154',SYS_GUID(),1,'OFFICE FOLDERS AND EXPANDING POCKETS','OFFICE FOLDERS AND EXPANDING POCKETS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7157',SYS_GUID(),1,'OFFICE ERASERS','OFFICE ERASERS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('715A',SYS_GUID(),1,'OFFICE BINDERS - VINYL','OFFICE BINDERS - VINYL',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7163',SYS_GUID(),1,'OFFICE BOOKS','OFFICE BOOKS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7167',SYS_GUID(),1,'OFFICE STAPLERS, AND STAPLE REMOVERS','OFFICE STAPLERS, AND STAPLE REMOVERS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7169',SYS_GUID(),1,'OFFICE RUBBER BANDS','OFFICE RUBBER BANDS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7173',SYS_GUID(),1,'OFFICE CORRECTION FLUID AND TAPE','OFFICE CORRECTION FLUID AND TAPE',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7175',SYS_GUID(),1,'OFFICE CLIPS AND FASTENERS','OFFICE CLIPS AND FASTENERS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('717A',SYS_GUID(),1,'OFFICE TAPE DISPENSERS','OFFICE TAPE DISPENSERS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('717B',SYS_GUID(),1,'OFFICE SPIRIT MASTERS/TRANSPARENCIES','OFFICE SPIRIT MASTERS/TRANSPARENCIES',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7181',SYS_GUID(),1,'OFFICE PENCIL SHARPENERS','OFFICE PENCIL SHARPENERS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7183',SYS_GUID(),1,'OFFICE SHEET PROTECTORS & REINFORCEMENTS','OFFICE SHEET PROTECTORS & REINFORCEMENTS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7184',SYS_GUID(),1,'OFFICE PENDAFLEX TABS/INSERTS','OFFICE PENDAFLEX TABS/INSERTS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7190',SYS_GUID(),1,'OFFICE RULERS','OFFICE RULERS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7193',SYS_GUID(),1,'OFFICE SORTING AIDS','OFFICE SORTING AIDS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7195',SYS_GUID(),1,'OFFICE CARTRIDGES - TONER','OFFICE CARTRIDGES - TONER',0.12,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7199',SYS_GUID(),1,'OFFICE MISCELLANEOUS','OFFICE MISCELLANEOUS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7210',SYS_GUID(),1,'OFFICE - WRITING AND MARKING PENCILS','OFFICE - WRITING AND MARKING PENCILS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7220',SYS_GUID(),1,'OFFICE - WRITING AND MARKING PENS','OFFICE - WRITING AND MARKING PENS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7230',SYS_GUID(),1,'OFFICE - MARKING HIGHLIGHTERS','OFFICE - MARKING HIGHLIGHTERS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7240',SYS_GUID(),1,'OFFICE - WRITING AND MARKING FELT','OFFICE - WRITING AND MARKING FELT',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7250',SYS_GUID(),1,'OFFICE - WRITING ROLLING BALL PENS','OFFICE - WRITING ROLLING BALL PENS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7260',SYS_GUID(),1,'OFFICE - MARKING RUBBER STAMPS','OFFICE - MARKING RUBBER STAMPS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7270',SYS_GUID(),1,'OFFICE - WRITING AND MARKING MISC.','OFFICE - WRITING AND MARKING MISC.',0,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7280',SYS_GUID(),1,'OFFICE - CHALK AND WHITEBOARD SUPPLIES','OFFICE - CHALK AND WHITEBOARD SUPPLIES',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7311',SYS_GUID(),1,'VISUAL AND AUDIO COMMUNICATIONS','VISUAL AND AUDIO COMMUNICATIONS',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7315',SYS_GUID(),1,'VISUAL AUDIO COMMUNICATIONS DIRECTORIES','VISUAL AUDIO COMMUNICATIONS DIRECTORIES',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7319',SYS_GUID(),1,'VISUAL PHOTOGRAPHY AND VIDEO SUPPLIES','VISUAL PHOTOGRAPHY AND VIDEO SUPPLIES',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7399',SYS_GUID(),1,'VISUAL AND AUDIO COMMUNICATIONS MISC.','VISUAL AND AUDIO COMMUNICATIONS MISC.',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7420',SYS_GUID(),1,'OFFICE - FORMS SYSTEMWIDE 71443','OFFICE - FORMS SYSTEMWIDE 71443',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('7430',SYS_GUID(),1,'OFFICE - FORMS CAMPUS 71461','OFFICE - FORMS CAMPUS 71461',0.224,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('8000',SYS_GUID(),1,'CONTAINERS PLASTIC BAGS','CONTAINERS PLASTIC BAGS',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('8002',SYS_GUID(),1,'CONTAINERS PAPER BAGS','CONTAINERS PAPER BAGS',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('8059',SYS_GUID(),1,'CONTAINERS MISCELLANEOUS','CONTAINERS MISCELLANEOUS',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('8081',SYS_GUID(),1,'CONTAINERS FOOD STORAGE','CONTAINERS FOOD STORAGE',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('8099',SYS_GUID(),1,'CONTAINERS BOXES','CONTAINERS BOXES',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('8715',SYS_GUID(),1,'MAILING & SHIPPING SUPPLIES PAPER','MAILING & SHIPPING SUPPLIES PAPER',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('8725',SYS_GUID(),1,'MAILING & SHIPPING SUPPLIES BOXES','MAILING & SHIPPING SUPPLIES BOXES',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('9231',SYS_GUID(),1,'SECURITY PROTECTIVE CLOTHING','SECURITY PROTECTIVE CLOTHING',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('9233',SYS_GUID(),1,'SECURITY GLOVES','SECURITY GLOVES',0.25,NULL,null,'06','Y',current_date);
INSERT INTO mm_markup_t  (MARKUP_CD,OBJ_ID,VER_NBR,MARKUP_NM,MARKUP_DESC,MARKUP_RT,WAREHOUSE_CD,MARKUP_COA_CD,MARKUP_TYPE_CD,ACTV_IND,LAST_UPDATE_DT)
VALUES('9299',SYS_GUID(),1,'SECURITY PADLOCKS','SECURITY PADLOCKS',0.25,NULL,null,'06','Y',current_date);
