INSERT INTO mm_markup_t (MARKUP_CD, OBJ_ID, VER_NBR, MARKUP_NM, MARKUP_RT, WAREHOUSE_CD, MARKUP_COA_CD, MARKUP_ORG_CD, MARKUP_ACCOUNT_NBR, MARKUP_FIXED_AMT, MARKUP_BEGIN_DT, MARKUP_END_DT, MARKUP_TYPE_CD, CATALOG_GROUP_CD, CATALOG_SUBGROUP_ID, ACTV_IND, LAST_UPDATE_DT)
VALUES('C01', sys_guid(), 1, 'CASH PURCHASE MARK-UP', 0.1000, '74', NULL, NULL, NULL, NULL, TO_DATE('2010-01-01', 'YYYY-MM-DD'), TO_DATE('2015-12-31', 'YYYY-MM-DD'), '08', NULL, NULL, 'Y', CURRENT_DATE)
;
INSERT INTO mm_markup_t (MARKUP_CD, OBJ_ID, VER_NBR, MARKUP_NM, MARKUP_RT, WAREHOUSE_CD, MARKUP_COA_CD, MARKUP_ORG_CD, MARKUP_ACCOUNT_NBR, MARKUP_FIXED_AMT, MARKUP_BEGIN_DT, MARKUP_END_DT, MARKUP_TYPE_CD, CATALOG_GROUP_CD, CATALOG_SUBGROUP_ID, ACTV_IND, LAST_UPDATE_DT)
VALUES('C11', sys_guid(), 1, 'CASH PURCHASE MARK-UP', 0.1000, 'SI', NULL, NULL, NULL, NULL, TO_DATE('2010-01-01', 'YYYY-MM-DD'), TO_DATE('2015-12-31', 'YYYY-MM-DD'), '08', NULL, NULL, 'Y', CURRENT_DATE)
;
INSERT INTO mm_markup_t (MARKUP_CD, OBJ_ID, VER_NBR, MARKUP_NM, MARKUP_RT, WAREHOUSE_CD, MARKUP_COA_CD, MARKUP_ORG_CD, MARKUP_ACCOUNT_NBR, MARKUP_FIXED_AMT, MARKUP_BEGIN_DT, MARKUP_END_DT, MARKUP_TYPE_CD, CATALOG_GROUP_CD, CATALOG_SUBGROUP_ID, ACTV_IND, LAST_UPDATE_DT)
VALUES('C21', sys_guid(), 1, 'CASH PURCHASE MARK-UP', 0.1000, 'NS', NULL, NULL, NULL, NULL, TO_DATE('2010-01-01', 'YYYY-MM-DD'), TO_DATE('2015-12-31', 'YYYY-MM-DD'), '08', NULL, NULL, 'Y', CURRENT_DATE)
;
INSERT INTO mm_markup_t (MARKUP_CD, OBJ_ID, VER_NBR, MARKUP_NM, MARKUP_RT, WAREHOUSE_CD, MARKUP_COA_CD, MARKUP_ORG_CD, MARKUP_ACCOUNT_NBR, MARKUP_FIXED_AMT, MARKUP_BEGIN_DT, MARKUP_END_DT, MARKUP_TYPE_CD, CATALOG_GROUP_CD, CATALOG_SUBGROUP_ID, ACTV_IND, LAST_UPDATE_DT)
VALUES('C31', sys_guid(), 1, 'CASH PURCHASE MARK-UP', 0.1000, 'SH', NULL, NULL, NULL, NULL, TO_DATE('2010-01-01', 'YYYY-MM-DD'), TO_DATE('2015-12-31', 'YYYY-MM-DD'), '08', NULL, NULL, 'Y', CURRENT_DATE)
;
INSERT INTO mm_markup_t (MARKUP_CD, OBJ_ID, VER_NBR, MARKUP_NM, MARKUP_RT, WAREHOUSE_CD, MARKUP_COA_CD, MARKUP_ORG_CD, MARKUP_ACCOUNT_NBR, MARKUP_FIXED_AMT, MARKUP_BEGIN_DT, MARKUP_END_DT, MARKUP_TYPE_CD, CATALOG_GROUP_CD, CATALOG_SUBGROUP_ID, ACTV_IND, LAST_UPDATE_DT)
VALUES('C41', sys_guid(), 1, 'CASH PURCHASE MARK-UP', 0.1000, 'NC', NULL, NULL, NULL, NULL, TO_DATE('2010-01-01', 'YYYY-MM-DD'), TO_DATE('2015-12-31', 'YYYY-MM-DD'), '08', NULL, NULL, 'Y', CURRENT_DATE)
;
INSERT INTO mm_markup_t (MARKUP_CD, OBJ_ID, VER_NBR, MARKUP_NM, MARKUP_RT, WAREHOUSE_CD, MARKUP_COA_CD, MARKUP_ORG_CD, MARKUP_ACCOUNT_NBR, MARKUP_FIXED_AMT, MARKUP_BEGIN_DT, MARKUP_END_DT, MARKUP_TYPE_CD, CATALOG_GROUP_CD, CATALOG_SUBGROUP_ID, ACTV_IND, LAST_UPDATE_DT)
VALUES('C51', sys_guid(), 1, 'CASH PURCHASE MARK-UP', 0.1000, 'MG', NULL, NULL, NULL, NULL, TO_DATE('2010-01-01', 'YYYY-MM-DD'), TO_DATE('2015-12-31', 'YYYY-MM-DD'), '08', NULL, NULL, 'Y', CURRENT_DATE)
;
INSERT INTO mm_markup_t (MARKUP_CD, OBJ_ID, VER_NBR, MARKUP_NM, MARKUP_RT, WAREHOUSE_CD, MARKUP_COA_CD, MARKUP_ORG_CD, MARKUP_ACCOUNT_NBR, MARKUP_FIXED_AMT, MARKUP_BEGIN_DT, MARKUP_END_DT, MARKUP_TYPE_CD, CATALOG_GROUP_CD, CATALOG_SUBGROUP_ID, ACTV_IND, LAST_UPDATE_DT)
VALUES('W01', sys_guid(), 1, 'WAREHOUSE PERCENT MARKUP', 0.0800, '74', NULL, NULL, NULL, NULL, TO_DATE('2010-01-01', 'YYYY-MM-DD'), TO_DATE('2015-12-31', 'YYYY-MM-DD'), '07', NULL, NULL, 'Y', CURRENT_DATE)
;
INSERT INTO mm_markup_t (MARKUP_CD, OBJ_ID, VER_NBR, MARKUP_NM, MARKUP_RT, WAREHOUSE_CD, MARKUP_COA_CD, MARKUP_ORG_CD, MARKUP_ACCOUNT_NBR, MARKUP_FIXED_AMT, MARKUP_BEGIN_DT, MARKUP_END_DT, MARKUP_TYPE_CD, CATALOG_GROUP_CD, CATALOG_SUBGROUP_ID, ACTV_IND, LAST_UPDATE_DT)
VALUES('W11', sys_guid(), 1, 'WAREHOUSE PERCENT MARKUP', 0.0800, 'SI', NULL, NULL, NULL, NULL, TO_DATE('2010-01-01', 'YYYY-MM-DD'), TO_DATE('2015-12-31', 'YYYY-MM-DD'), '07', NULL, NULL, 'Y', CURRENT_DATE)
;
INSERT INTO mm_markup_t (MARKUP_CD, OBJ_ID, VER_NBR, MARKUP_NM, MARKUP_RT, WAREHOUSE_CD, MARKUP_COA_CD, MARKUP_ORG_CD, MARKUP_ACCOUNT_NBR, MARKUP_FIXED_AMT, MARKUP_BEGIN_DT, MARKUP_END_DT, MARKUP_TYPE_CD, CATALOG_GROUP_CD, CATALOG_SUBGROUP_ID, ACTV_IND, LAST_UPDATE_DT)
VALUES('W21', sys_guid(), 1, 'WAREHOUSE PERCENT MARKUP', 0.0800, 'NS', NULL, NULL, NULL, NULL, TO_DATE('2010-01-01', 'YYYY-MM-DD'), TO_DATE('2015-12-31', 'YYYY-MM-DD'), '07', NULL, NULL, 'Y', CURRENT_DATE)
;
INSERT INTO mm_markup_t (MARKUP_CD, OBJ_ID, VER_NBR, MARKUP_NM, MARKUP_RT, WAREHOUSE_CD, MARKUP_COA_CD, MARKUP_ORG_CD, MARKUP_ACCOUNT_NBR, MARKUP_FIXED_AMT, MARKUP_BEGIN_DT, MARKUP_END_DT, MARKUP_TYPE_CD, CATALOG_GROUP_CD, CATALOG_SUBGROUP_ID, ACTV_IND, LAST_UPDATE_DT)
VALUES('W31', sys_guid(), 1, 'WAREHOUSE PERCENT MARKUP', 0.0800, 'SH', NULL, NULL, NULL, NULL, TO_DATE('2010-01-01', 'YYYY-MM-DD'), TO_DATE('2015-12-31', 'YYYY-MM-DD'), '07', NULL, NULL, 'Y', CURRENT_DATE)
;
INSERT INTO mm_markup_t (MARKUP_CD, OBJ_ID, VER_NBR, MARKUP_NM, MARKUP_RT, WAREHOUSE_CD, MARKUP_COA_CD, MARKUP_ORG_CD, MARKUP_ACCOUNT_NBR, MARKUP_FIXED_AMT, MARKUP_BEGIN_DT, MARKUP_END_DT, MARKUP_TYPE_CD, CATALOG_GROUP_CD, CATALOG_SUBGROUP_ID, ACTV_IND, LAST_UPDATE_DT)
VALUES('W41', sys_guid(), 1, 'WAREHOUSE PERCENT MARKUP', 0.0800, 'NC', NULL, NULL, NULL, NULL, TO_DATE('2010-01-01', 'YYYY-MM-DD'), TO_DATE('2015-12-31', 'YYYY-MM-DD'), '07', NULL, NULL, 'Y', CURRENT_DATE)
;
INSERT INTO mm_markup_t (MARKUP_CD, OBJ_ID, VER_NBR, MARKUP_NM, MARKUP_RT, WAREHOUSE_CD, MARKUP_COA_CD, MARKUP_ORG_CD, MARKUP_ACCOUNT_NBR, MARKUP_FIXED_AMT, MARKUP_BEGIN_DT, MARKUP_END_DT, MARKUP_TYPE_CD, CATALOG_GROUP_CD, CATALOG_SUBGROUP_ID, ACTV_IND, LAST_UPDATE_DT)
VALUES('W51', sys_guid(), 1, 'WAREHOUSE PERCENT MARKUP', 0.0800, 'MG', NULL, NULL, NULL, NULL, TO_DATE('2010-01-01', 'YYYY-MM-DD'), TO_DATE('2015-12-31', 'YYYY-MM-DD'), '07', NULL, NULL, 'Y', CURRENT_DATE)
;
