INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200941268', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200941'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200941'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR26'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '31516560') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200941269', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200941'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200941'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR26'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '31554720') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200941270', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200941'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200941'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR26'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '31535820') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200964099', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200964'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200964'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR26'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '31558090') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200970040', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200970'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200970'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35371560') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200970041', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200970'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200970'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35371560') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200972119', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200972'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200972'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR179'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '34022390') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200972120', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200972'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200972'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR179'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '34022960') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200972121', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200972'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200972'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR179'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '34022620') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200975019', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200975'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200975'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR179'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '34004020') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200977018', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200977'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200977'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35099430') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200979092', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200979'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200979'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35021800') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200979102', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200979'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200979'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35021595') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200979103', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200979'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200979'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35086975') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200980126', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200980'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200980'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35312060') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200980137', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200980'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200980'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '36534940') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200980139', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200980'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200980'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR26'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '33017020') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200980141', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200980'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200980'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR26'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '32094000') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200980142', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200980'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200980'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR26'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '32543140') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200980143', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200980'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200980'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '36511630') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200980144', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200980'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200980'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR26'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '32543130') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200981176', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200981'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200981'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR26'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '33568890') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200981177', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200981'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200981'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR26'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '33503980') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200981178', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200981'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200981'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR26'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '33514800') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200985050', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200985'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200985'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35368340') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200986095', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200986'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200986'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR179'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '34053840') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200986097', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200986'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200986'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR19'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '34050160') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200990050', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200990'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200990'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR15'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '34002520') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200990057', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200990'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200990'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR179'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '34002800') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200990058', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200990'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200990'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR26'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '34003500') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200991028', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200991'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200991'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR15'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '34041590') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200994122', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200994'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200994'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35086331') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200994124', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200994'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200994'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35086320') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200994125', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200994'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200994'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35031410') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200994126', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200994'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200994'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35004270') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200994127', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200994'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200994'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35031420') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200996078', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200996'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200996'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR179'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '33953020') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200996081', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200996'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200996'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR179'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '33922060') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200996082', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200996'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200996'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR179'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '33913350') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '200998065', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '200998'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '200998'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR26'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '31019920') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201002036', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201002'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201002'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35553520') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201003074', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201003'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201003'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR26'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '31053060') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201004126', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201004'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201004'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR179'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '34094621') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201004127', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201004'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201004'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR179'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '34094669') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201004128', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201004'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201004'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR179'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '34094627') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201004130', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201004'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201004'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR19'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '34017758') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201005035', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201005'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201005'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '34543660') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201007021', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201007'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201007'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR26'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '33087260') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201007022', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201007'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201007'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR26'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '33007760') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201009039', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201009'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201009'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35373720') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201011007', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201011'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201011'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '34587380') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201013091', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201013'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201013'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR179'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '34013480') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201013092', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201013'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201013'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR179'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '34009460') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201013093', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201013'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201013'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR179'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '34009240') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201016009', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201016'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201016'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR179'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '34095182') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201016010', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201016'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201016'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR179'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '34095182') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201016011', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201016'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201016'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR179'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '34095182') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201020003', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201020'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201020'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35087500') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201020006', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201020'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201020'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35087400') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201020016', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201020'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201020'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35087500') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201020020', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201020'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201020'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35088860') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201020021', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201020'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201020'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35087500') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201020022', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201020'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201020'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35088800') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201022018', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201022'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201022'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR26'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '31079520') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201023017', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201023'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201023'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR15'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '34019180') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201024007', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201024'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201024'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR26'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '32502090') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201024008', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201024'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201024'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR26'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '32502030') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201025006', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201025'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201025'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR179'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '34090860') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201025009', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201025'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201025'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR179'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '34090860') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201026013', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201026'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201026'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR26'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '32542160') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201026014', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201026'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201026'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR26'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '31015210') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201028023', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201028'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201028'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35373300') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201028028', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201028'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201028'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35301330') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201028029', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201028'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201028'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35351121') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201028030', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201028'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201028'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35301330') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201028031', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201028'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201028'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35373140') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201029010', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201029'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201029'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35375080') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201029011', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201029'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201029'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35325060') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201030029', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201030'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201030'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35326200') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201030030', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201030'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201030'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35374100') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201030031', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201030'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201030'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35311450') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201031010', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201031'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201031'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35357900') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201031011', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201031'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201031'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35373460') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201031012', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201031'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201031'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35372300') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201031013', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201031'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201031'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35373411') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201032022', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201032'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201032'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35546420') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201032023', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201032'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201032'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35546420') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201032026', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201032'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201032'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35324890') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201032027', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201032'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201032'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35310220') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201032028', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201032'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201032'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35311640') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201032032', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201032'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201032'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35362140') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201032033', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201032'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201032'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35387800') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201032034', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201032'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201032'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35302000') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201032035', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201032'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201032'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35300510') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201033004', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201033'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201033'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR179'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '33975990') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201034001', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201034'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201034'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '34542600') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201034024', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201034'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201034'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR26'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '32542580') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201034030', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201034'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201034'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35086290') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201034031', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201034'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201034'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '36501070') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201034033', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201034'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201034'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35503800') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201034034', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201034'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201034'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '34525080') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201034035', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201034'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201034'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '34525840') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201034036', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201034'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201034'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '34524320') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
INSERT INTO MM_ORDER_DOC_T ( FDOC_NBR, OBJ_ID, VER_NBR, ORDER_ID, ORDER_TYPE_CD, VENDOR_HEADER_GENERATED_ID, VENDOR_DETAIL_ASSIGNED_ID, VENDOR_NM, CUSTOMER_PROFILE_ID, ORDER_DOC_STATUS_CD, WAREHOUSE_CD, CAMPUS_CD, LAST_UPDATE_DT )
VALUES (MM_SYS_GUID_S.nextval, SYS_GUID(), '1', '201036001', 'STOCK', (select MM_AGREEMENT_T.VNDR_CONTR_GNRTD_ID from MM_AGREEMENT_T where AGREEMENT_NBR = '201036'), 
         1, (select MM_AGREEMENT_T.VENDOR_NM from MM_AGREEMENT_T where AGREEMENT_NBR = '201036'), 
        (select MM_PROFILE_T.PROFILE_ID from MM_PROFILE_T where CUSTOMER_PRNCPL_ID = 'STR32'), 
        'P',
        (select cz.WAREHOUSE_CD from MM_STOCK_BALANCE_T cb join MM_BIN_T cc on cc.bin_id = cb.bin_id join MM_ZONE_T cz on cz.zone_id = cc.zone_id
        where cb.STOCK_ID = (select bb.STOCK_ID from MM_STOCK_T bb where bb.STOCK_DISTRIBUTOR_NBR = '35366300') and rownum < 2), 
       'ZZ', CURRENT_DATE )
;
Commit;
update MM_ORDER_DOC_T
  set ORDER_CREATE_DT = LAST_UPDATE_DT
;
