INSERT INTO MM_PROFILE_T ( PROFILE_ID, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, ACTV_IND, PROFILE_DEFAULT_IND, LAST_UPDATE_DT )
VALUES (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'ASHLEYAM', 'ashleyam@msu.edu', '555-666-1234', 'Y', 'Y', CURRENT_DATE )
;
INSERT INTO MM_PROFILE_T ( PROFILE_ID, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, ACTV_IND, PROFILE_DEFAULT_IND, LAST_UPDATE_DT )
VALUES (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'STR05', 'STR05@usdwp.msu.edu', '555-666-1234', 'Y', 'Y', CURRENT_DATE )
;
INSERT INTO MM_PROFILE_T ( PROFILE_ID, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, ACTV_IND, PROFILE_DEFAULT_IND, LAST_UPDATE_DT )
VALUES (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'STR06', 'STR06@usdwp.msu.edu', '555-666-1234', 'Y', 'Y', CURRENT_DATE )
;
INSERT INTO MM_PROFILE_T ( PROFILE_ID, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, ACTV_IND, PROFILE_DEFAULT_IND, LAST_UPDATE_DT )
VALUES (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'STR10', 'STR10@usdwp.msu.edu', '555-666-1234', 'Y', 'Y', CURRENT_DATE )
;
INSERT INTO MM_PROFILE_T ( PROFILE_ID, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, ACTV_IND, PROFILE_DEFAULT_IND, LAST_UPDATE_DT )
VALUES (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'STR14', 'STR14@usdwp.msu.edu', '555-666-1234', 'Y', 'Y', CURRENT_DATE )
;
INSERT INTO MM_PROFILE_T ( PROFILE_ID, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, ACTV_IND, PROFILE_DEFAULT_IND, LAST_UPDATE_DT )
VALUES (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'STR15', 'STR15@usdwp.msu.edu', '555-666-1234', 'Y', 'Y', CURRENT_DATE );
;
INSERT INTO MM_PROFILE_T ( PROFILE_ID, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, ACTV_IND, PROFILE_DEFAULT_IND, LAST_UPDATE_DT )
VALUES (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'STR17', 'STR17@usdwp.msu.edu', '555-666-1234', 'Y', 'Y', CURRENT_DATE );
;
INSERT INTO MM_PROFILE_T ( PROFILE_ID, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, ACTV_IND, PROFILE_DEFAULT_IND, LAST_UPDATE_DT )
VALUES (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'STR179', 'STR179@usdwp.msu.edu', '555-666-1234', 'Y', 'Y', CURRENT_DATE );
;
INSERT INTO MM_PROFILE_T ( PROFILE_ID, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, ACTV_IND, PROFILE_DEFAULT_IND, LAST_UPDATE_DT )
VALUES (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'STR19', 'STR19@usdwp.msu.edu', '555-666-1234', 'Y', 'Y', CURRENT_DATE );
;
INSERT INTO MM_PROFILE_T ( PROFILE_ID, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, ACTV_IND, PROFILE_DEFAULT_IND, LAST_UPDATE_DT )
VALUES (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'STR24', 'STR24@usdwp.msu.edu', '555-666-1234', 'Y', 'Y', CURRENT_DATE );
;
INSERT INTO MM_PROFILE_T ( PROFILE_ID, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, ACTV_IND, PROFILE_DEFAULT_IND, LAST_UPDATE_DT )
VALUES (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'STR26', 'STR26@usdwp.msu.edu', '555-666-1234', 'Y', 'Y', CURRENT_DATE );
;
INSERT INTO MM_PROFILE_T ( PROFILE_ID, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, ACTV_IND, PROFILE_DEFAULT_IND, LAST_UPDATE_DT )
VALUES (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'STR29', 'STR29@usdwp.msu.edu', '555-666-1234', 'Y', 'Y', CURRENT_DATE );
;
INSERT INTO MM_PROFILE_T ( PROFILE_ID, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, ACTV_IND, PROFILE_DEFAULT_IND, LAST_UPDATE_DT )
VALUES (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'STR31', 'STR31@usdwp.msu.edu', '555-666-1234', 'Y', 'Y', CURRENT_DATE );
;
INSERT INTO MM_PROFILE_T ( PROFILE_ID, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, ACTV_IND, PROFILE_DEFAULT_IND, LAST_UPDATE_DT )
VALUES (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'STR32', 'STR32@usdwp.msu.edu', '555-666-1234', 'Y', 'Y', CURRENT_DATE );
;
INSERT INTO MM_PROFILE_T ( PROFILE_ID, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, ACTV_IND, PROFILE_DEFAULT_IND, LAST_UPDATE_DT )
VALUES (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'STR35', 'STR35@usdwp.msu.edu', '555-666-1234', 'Y', 'Y', CURRENT_DATE );
;
INSERT INTO MM_PROFILE_T ( PROFILE_ID, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, ACTV_IND, PROFILE_DEFAULT_IND, LAST_UPDATE_DT )
VALUES (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'STR37', 'STR37@usdwp.msu.edu', '555-666-1234', 'Y', 'Y', CURRENT_DATE );
;
INSERT INTO MM_PROFILE_T ( PROFILE_ID, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, ACTV_IND, PROFILE_DEFAULT_IND, LAST_UPDATE_DT )
VALUES (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'STR41', 'STR41@usdwp.msu.edu', '555-666-1234', 'Y', 'Y', CURRENT_DATE );
;
INSERT INTO MM_PROFILE_T ( PROFILE_ID, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, ACTV_IND, PROFILE_DEFAULT_IND, LAST_UPDATE_DT )
VALUES (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'STR58', 'STR58@usdwp.msu.edu', '555-666-1234', 'Y', 'Y', CURRENT_DATE );
;
INSERT INTO MM_PROFILE_T ( PROFILE_ID, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, ACTV_IND, PROFILE_DEFAULT_IND, LAST_UPDATE_DT )
VALUES (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'WHITMA32', 'whitma32@msu.edu', '555-666-1234', 'Y', 'Y', CURRENT_DATE );
;
INSERT INTO MM_PROFILE_T ( PROFILE_ID, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, ACTV_IND, PROFILE_DEFAULT_IND, LAST_UPDATE_DT )
VALUES (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'SZMATSIS', 'aamatsis@ucdavis.edu', '555-666-1234', 'Y', 'Y', CURRENT_DATE );
;
INSERT INTO MM_PROFILE_T ( PROFILE_ID, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, ACTV_IND, PROFILE_DEFAULT_IND, LAST_UPDATE_DT )
VALUES (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'NOREENM', 'njmcintyre@ucdavis.edu', '555-666-1234', 'Y', 'Y', CURRENT_DATE );
;
INSERT INTO MM_PROFILE_T ( PROFILE_ID, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, ACTV_IND, PROFILE_DEFAULT_IND, LAST_UPDATE_DT )
VALUES (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'SZKARLR', 'kwreinking@ucdavis.edu', '555-666-1234', 'Y', 'Y', CURRENT_DATE );
;
INSERT INTO MM_PROFILE_T ( PROFILE_ID, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, ACTV_IND, PROFILE_DEFAULT_IND, LAST_UPDATE_DT )
VALUES (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'PLLACEY', 'pllacey@ucdavis.edu', '555-666-1234', 'Y', 'Y', CURRENT_DATE );
;
INSERT INTO MM_PROFILE_T ( PROFILE_ID, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, ACTV_IND, PROFILE_DEFAULT_IND, LAST_UPDATE_DT )
VALUES (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'CASEBEER', 'klcasebeer@ucdavis.edu', '555-666-1234', 'Y', 'Y', CURRENT_DATE );
;
INSERT INTO MM_PROFILE_T ( PROFILE_ID, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, ACTV_IND, PROFILE_DEFAULT_IND, LAST_UPDATE_DT )
VALUES (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'JDLAWREN', 'jdlawrence@ucdavis.edu', '555-666-1234', 'Y', 'Y', CURRENT_DATE );
;
INSERT INTO MM_PROFILE_T ( PROFILE_ID, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, ACTV_IND, PROFILE_DEFAULT_IND, LAST_UPDATE_DT )
VALUES (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'LIASCOTT', 'liascott@ucdavis.edu', '555-666-1234', 'Y', 'Y', CURRENT_DATE );
;
INSERT INTO MM_PROFILE_T ( PROFILE_ID, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, ACTV_IND, PROFILE_DEFAULT_IND, LAST_UPDATE_DT )
VALUES (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'BGLEPENS', 'bglepenske@ucdavis.edu', '555-666-1234', 'Y', 'Y', CURRENT_DATE );
;
INSERT INTO MM_PROFILE_T ( PROFILE_ID, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, ACTV_IND, PROFILE_DEFAULT_IND, LAST_UPDATE_DT )
VALUES (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'KGALLING', 'kaycole@ucdavis.edu', '555-666-1234', 'Y', 'Y', CURRENT_DATE );
;
insert into MM_PROFILE_T (Profile_Id, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, DELIVERY_BUILDING_CD, DELIVERY_BUILDING_RM_NBR, ACTV_IND,PROFILE_DEFAULT_IND, LAST_UPDATE_DT)
values (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'SCHNEPP', 'schneppd@msu.edu', '555-666-1234', 'BLDG', '304A', 'Y', 'Y', SYSDATE)
;
insert into MM_PROFILE_T (Profile_Id, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, DELIVERY_BUILDING_CD, DELIVERY_BUILDING_RM_NBR, ACTV_IND,PROFILE_DEFAULT_IND, LAST_UPDATE_DT)
values (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'MMUSER', 'alavinas@ais.msu.edu', '555-666-1234', 'BLDG', '304A', 'Y', 'Y', SYSDATE)
;
insert into MM_PROFILE_T (Profile_Id, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, DELIVERY_BUILDING_CD, DELIVERY_BUILDING_RM_NBR, ACTV_IND,PROFILE_DEFAULT_IND, LAST_UPDATE_DT)
values (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'ADMIN', 'terrym@ais.msu.edu', '555-666-1234', 'BLDG', '304A', 'Y', 'Y', SYSDATE)
;
