insert into MM_PROFILE_T (Profile_Id, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, DELIVERY_BUILDING_CD, DELIVERY_BUILDING_RM_NBR, BILLING_BUILDING_CD, ORG_CD, CAMPUS_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, PROJECT_CD, PROFILE_DEFAULT_IND, NOTIFY_IND, PERSONAL_IND, ACTV_IND, LAST_UPDATE_DT)
values (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'heckam11', 'heckam11@msu.edu', '517-884-6232', '0133', '101B', '0133', '10074363', 'EL', 'MS', 'GA012483', NULL, NULL, 'Y', 'N', 'N', 'Y', SYSDATE)
;
insert into MM_PROFILE_T (Profile_Id, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, DELIVERY_BUILDING_CD, DELIVERY_BUILDING_RM_NBR, BILLING_BUILDING_CD, ORG_CD, CAMPUS_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, PROJECT_CD, PROFILE_DEFAULT_IND, NOTIFY_IND, PERSONAL_IND, ACTV_IND, LAST_UPDATE_DT)
values (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'pridgeo1', 'pridgeo1@msu.edu', '517-353-3121x440', '0133', '102', '0133', '10074363', 'EL', 'MS', 'GA012483', NULL, NULL, 'Y', 'N', 'N', 'Y', SYSDATE)
;
insert into MM_PROFILE_T (Profile_Id, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, DELIVERY_BUILDING_CD, DELIVERY_BUILDING_RM_NBR, BILLING_BUILDING_CD, ORG_CD, CAMPUS_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, PROJECT_CD, PROFILE_DEFAULT_IND, NOTIFY_IND, PERSONAL_IND, ACTV_IND, LAST_UPDATE_DT)
values (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'rousej', 'rousej@msu.edu', '517-353-3121x470', '0133', '102', '0133', '10074363', 'EL', 'MS', 'GA012483', NULL, NULL, 'Y', 'N', 'N', 'Y', SYSDATE)
;
insert into MM_PROFILE_T (Profile_Id, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, DELIVERY_BUILDING_CD, DELIVERY_BUILDING_RM_NBR, BILLING_BUILDING_CD, ORG_CD, CAMPUS_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, PROJECT_CD, PROFILE_DEFAULT_IND, NOTIFY_IND, PERSONAL_IND, ACTV_IND, LAST_UPDATE_DT)
values (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'merriott', 'merriott@msu.edu', '517-353-3121x427', '0133', '102', '0133', '10074363', 'EL', 'MS', 'GA012483', NULL, NULL, 'Y', 'N', 'N', 'Y', SYSDATE)
;
insert into MM_PROFILE_T (Profile_Id, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, DELIVERY_BUILDING_CD, DELIVERY_BUILDING_RM_NBR, BILLING_BUILDING_CD, ORG_CD, CAMPUS_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, PROJECT_CD, PROFILE_DEFAULT_IND, NOTIFY_IND, PERSONAL_IND, ACTV_IND, LAST_UPDATE_DT)
values (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'georgep', 'georgep@msu.edu', '517-884-6138', '0088', '100', '0088', '10074363', 'EL', 'MS', 'GA012483', NULL, NULL, 'Y', 'N', 'N', 'Y', SYSDATE)
;
insert into MM_PROFILE_T (Profile_Id, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, DELIVERY_BUILDING_CD, DELIVERY_BUILDING_RM_NBR, BILLING_BUILDING_CD, ORG_CD, CAMPUS_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, PROJECT_CD, PROFILE_DEFAULT_IND, NOTIFY_IND, PERSONAL_IND, ACTV_IND, LAST_UPDATE_DT)
values (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'kokenake', 'kokenake@msu.edu', '517-884-6186', '0133', '101E', '0133', '10074363', 'EL', 'MS', 'GA012483', NULL, NULL, 'Y', 'N', 'N', 'Y', SYSDATE)
;
insert into MM_PROFILE_T (Profile_Id, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, DELIVERY_BUILDING_CD, DELIVERY_BUILDING_RM_NBR, BILLING_BUILDING_CD, ORG_CD, CAMPUS_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, PROJECT_CD, PROFILE_DEFAULT_IND, NOTIFY_IND, PERSONAL_IND, ACTV_IND, LAST_UPDATE_DT)
values (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'phillipm', 'phillipm@msu.edu', '517-884-6168', '0133', '102', '0133', '10074363', 'EL', 'MS', 'GA012483', NULL, NULL, 'Y', 'N', 'N', 'Y', SYSDATE)
;
insert into MM_PROFILE_T (Profile_Id, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, DELIVERY_BUILDING_CD, DELIVERY_BUILDING_RM_NBR, BILLING_BUILDING_CD, ORG_CD, CAMPUS_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, PROJECT_CD, PROFILE_DEFAULT_IND, NOTIFY_IND, PERSONAL_IND, ACTV_IND, LAST_UPDATE_DT)
values (MM_PROFILE_S.nextval, SYS_GUID(), '1', 'DEFAULT', 'obriend', 'obriend@msu.edu', '517-884-6158', '0088', '121', '0088', '10074363', 'EL', 'MS', 'GA012483', NULL, NULL, 'Y', 'N', 'N', 'Y', SYSDATE)
;
insert into MM_PROFILE_T (Profile_Id, OBJ_ID, VER_NBR, PROFILE_NM, CUSTOMER_PRNCPL_NM, PROFILE_EMAIL, PROFILE_PHONE_NBR, DELIVERY_BUILDING_CD, DELIVERY_BUILDING_RM_NBR, BILLING_BUILDING_CD, ORG_CD, CAMPUS_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, PROJECT_CD, PROFILE_DEFAULT_IND, NOTIFY_IND, PERSONAL_IND, ACTV_IND, LAST_UPDATE_DT)
values (MM_PROFILE_S.nextval, SYS_GUID(), '1', '10076200-GA012523', 'terry', 'terrym@msu.edu', '517-353-3121', '0067', '301', '0067', '10076200', 'EL', 'MS', 'GA012523', NULL, NULL, 'Y', 'N', 'N', 'Y', SYSDATE)
;
Commit;
update MM_WAREHOUSE_T
  set BILLING_PROFILE_ID = (select profile_id from mm_profile_t where customer_prncpl_nm = 'KOKENAKE')
;
