insert into MM_PROFILE_T (Profile_Id, PROFILE_NM, CUSTOMER_PRNCPL_ID, PROFILE_ADDRESS_ID, PROFILE_EMAIL, DELIVERY_BUILDING_CD, DELIVERY_BUILDING_RM_NBR, ACTV_IND,PROFILE_DEFAULT_IND, LAST_UPDATE_DT)
values (MM_CUSTOMER_PROFILE_S.nextval, 'Devin', 'SCHNEPP', 1, 'schneppd@msu.edu', 'BLDG', '304A', 'Y', 'Y', SYSDATE);
