INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('OBSOLETE', SYS_GUID(), '1', 'OBSOLETE STOCK', 'D', 'OBSO', 'Y', CURRENT_DATE ) 
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('DAMAGED', SYS_GUID(), '1', 'DAMAGED GOODS', 'D', 'SHRO', 'Y', CURRENT_DATE ) 
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('MISTAKE', SYS_GUID(), '1', 'VENDOR MISTAKE NO CHARGE', 'I', 'SHRO', 'Y', CURRENT_DATE ) 
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('PAPERWRK', SYS_GUID(), '1', 'NO PAPERWORK RECEIVED', 'I', 'SHRO', 'Y', CURRENT_DATE )
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('EXPIRED', SYS_GUID(), '1', 'EXPIRATION DATE EXCEEDED', 'D', 'SHRO', 'Y', CURRENT_DATE )
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('MANAGMNT', SYS_GUID(), '1', 'MANAGEMENT DECISION', 'I', 'SHRO', 'Y', CURRENT_DATE ) 
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('CONDENSA', SYS_GUID(), '1', 'ALCOHOL CONDENSATION', 'D', 'SHRO', 'Y', CURRENT_DATE ) 
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('EVAPORAT', SYS_GUID(), '1', 'ALCOHOL EVAPORATION', 'D', 'SHRO', 'Y', CURRENT_DATE ) 
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('PICK ERR', SYS_GUID(), '1', 'PICKING ERROR', 'I', 'SHRO', 'Y', CURRENT_DATE ) 
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('BAD_RCPT', SYS_GUID(), '1', 'RECEIVED LESS THAN RECORDED', 'D', 'SHRO', 'Y', CURRENT_DATE ) 
;
