\INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('INCOBS', SYS_GUID(), '1', 'Increase for Obsolete Stock', 'I', 'OBSO', 'Y', CURRENT_DATE ) 
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('IVENMST', SYS_GUID(), '1', 'Increase Vendor Mistake - No Charge', 'I', 'SHRO', 'Y', CURRENT_DATE ) 
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('IPICKERR', SYS_GUID(), '1', 'Increase Picking Error', 'I', 'SHRO', 'Y', CURRENT_DATE ) 
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('IVENERR', SYS_GUID(), '1', 'Increase Vendor Price Error', 'I', 'SHRO', 'Y', CURRENT_DATE ) 
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('IQTYBIN', SYS_GUID(), '1', 'Increase Quantity to Match Bin Balance', 'I', 'SHRO', 'Y', CURRENT_DATE )
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('ISPOTBUY', SYS_GUID(), '1', 'Increase Spot Buy', 'I', 'SHRO', 'Y', CURRENT_DATE )
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('ITRDRTN', SYS_GUID(), '1', 'Increase Trade Show Return', 'I', 'SHRO', 'Y', CURRENT_DATE ) 
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('ISHWRET', SYS_GUID(), '1', 'Increase Showroom Return', 'I', 'SHRO', 'Y', CURRENT_DATE )
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('IALCOCON', SYS_GUID(), '1', 'Increase Alcohol Condensation', 'I', 'SHRO', 'Y', CURRENT_DATE )
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('PHYINV', SYS_GUID(), '1', 'Physical Inventory', 'N', 'SHRO', 'Y', CURRENT_DATE ) 
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('DOBSOSTK', SYS_GUID(), '1', 'Decrease for Obsolete Stock', 'D', 'OBSO', 'Y', CURRENT_DATE ) 
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('DVENMST', SYS_GUID(), '1', 'Decrease Vendor Mistake - No Charge', 'D', 'SHRO', 'Y', CURRENT_DATE ) 
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('DPICKERR', SYS_GUID(), '1', 'Decrease Picking Error', 'D', 'SHRO', 'Y', CURRENT_DATE ) 
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('DVENERR', SYS_GUID(), '1', 'Decrease Vendor Price Error', 'D', 'SHRO', 'Y', CURRENT_DATE ) 
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('DGTYBIN', SYS_GUID(), '1', 'Decrease Quantity to Match Bin Balance', 'D', 'SHRO', 'Y', CURRENT_DATE )
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('DTRDSHOW', SYS_GUID(), '1', 'Decrease for Trade Show', 'D', 'SHRO', 'Y', CURRENT_DATE ) 
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('DSHWITEM', SYS_GUID(), '1', 'Decrease for Showroom Items Removed', 'D', 'SHRO', 'Y', CURRENT_DATE )
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('DRTNCRT', SYS_GUID(), '1', 'Decrease Return for Credit(remove from Stock)', 'D', 'SHRO', 'Y', CURRENT_DATE )
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('DRTNDEF', SYS_GUID(), '1', 'Decrease Return Defective', 'D', 'SHRO', 'Y', CURRENT_DATE )
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('DALCOEVA', SYS_GUID(), '1', 'Decrease Alcohol Evaporation', 'D', 'SHRO', 'Y', CURRENT_DATE )
;
INSERT INTO MM_STOCK_TRANS_REASON_T ( STOCK_TRANS_REASON_CD, OBJ_ID, VER_NBR, NM, INCREMENT_DECREMENT_IND, OBJECT_TYPE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('DCORRECT', SYS_GUID(), '1', 'Decrease for Receipt Correction', 'D', 'SHRO', 'Y', CURRENT_DATE )
;
