INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', '74', 'CG', 'MS', 'GZ051100', NULL, '6428', NULL, '4050', NULL, NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', '74', 'IC', 'MS', 'XT022956', NULL, '6564', NULL, '4050', NULL, NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', '74', 'TX', 'MS', 'AD023236', NULL, '4069', NULL, '1100', NULL, NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', '74', 'WR', 'MS', 'XT022956', NULL, '6564', NULL, '4050', NULL, NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', 'SI', 'CG', 'MS', 'GZ051100', NULL, '6428', NULL, '4050', NULL, NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', 'SI', 'IC', 'MS', 'XT022956', NULL, '6564', NULL, '4050', NULL, NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', 'SI', 'TX', 'MS', 'AD023236', NULL, '4069', NULL, '1100', NULL, NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', 'SI', 'WR', 'MS', 'XT022956', NULL, '6564', NULL, '4050', NULL, NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', 'NS', 'CG', 'MS', 'GZ051100', NULL, '6428', NULL, '4050', NULL, NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', 'NS', 'IC', 'MS', 'XT022956', NULL, '6564', NULL, '4050', NULL, NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', 'NS', 'TX', 'MS', 'AD023236', NULL, '4069', NULL, '1100', NULL, NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', 'NS', 'WR', 'MS', 'XT022956', NULL, '6564', NULL, '4050', NULL, NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', 'SH', 'CG', 'MS', 'GZ051100', NULL, '6428', NULL, '4050', NULL, NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', 'SH', 'IC', 'MS', 'XT022956', NULL, '6564', NULL, '4050', NULL, NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', 'SH', 'TX', 'MS', 'AD023236', NULL, '4069', NULL, '1100', NULL, NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', 'SH', 'WR', 'MS', 'XT022956', NULL, '6564', NULL, '4050', NULL, NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', 'NC', 'CG', 'MS', 'GZ051100', NULL, '6428', NULL, '4050', NULL, NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', 'NC', 'IC', 'MS', 'XT022956', NULL, '6564', NULL, '4050', NULL, NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', 'NC', 'TX', 'MS', 'AD023236', NULL, '4069', NULL, '1100', NULL, NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', 'NC', 'WR', 'MS', 'XT022956', NULL, '6564', NULL, '4050', NULL, NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', 'MG', 'CG', 'MS', 'GZ051100', NULL, '6428', NULL, '4050', NULL, NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', 'MG', 'IC', 'MS', 'XT022956', NULL, '6564', NULL, '4050', NULL, NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', 'MG', 'TX', 'MS', 'AD023236', NULL, '4069', NULL, '1100', NULL, NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', 'MG', 'WR', 'MS', 'XT022956', NULL, '6564', NULL, '4050', NULL, NULL, 'Y', CURRENT_DATE )
;
