INSERT INTO MM_WAREHOUSE_T ( WAREHOUSE_CD, OBJ_ID, VER_NBR, WAREHOUSE_NME, ADDRESS_CD, CONSOLIDATION_CD, DEFAULT_MARKUP_CD, BUYOUT_IND, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('AA', SYS_GUID(), '1', 'MAIN WAREHOUSE',  '1', 'N', '01', 'N', 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_T ( WAREHOUSE_CD, OBJ_ID, VER_NBR, WAREHOUSE_NME, ADDRESS_CD, CONSOLIDATION_CD, DEFAULT_MARKUP_CD, BUYOUT_IND, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('AB', SYS_GUID(), '1', 'WAREHOUSE STORE',  '2', 'N', '01', 'N', 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_T ( WAREHOUSE_CD, OBJ_ID, VER_NBR, WAREHOUSE_NME, DEFAULT_MARKUP_CD, BUYOUT_IND, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('63', SYS_GUID(), '1', 'MSU MAIN WAREHOUSE', 'W08', 'N', 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_T ( WAREHOUSE_CD, OBJ_ID, VER_NBR, WAREHOUSE_NME, DEFAULT_MARKUP_CD, BUYOUT_IND, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('NS', SYS_GUID(), '1', 'MSU NON STOCKED', 'W08', 'N', 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_T ( WAREHOUSE_CD, OBJ_ID, VER_NBR, WAREHOUSE_NME, DEFAULT_MARKUP_CD, BUYOUT_IND, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('SI', SYS_GUID(), '1', 'MSU SPECIALTY ITEMS', 'W08', 'N', 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_T ( WAREHOUSE_CD, OBJ_ID, VER_NBR, WAREHOUSE_NME, ADDRESS_CD, CONSOLIDATION_CD, DEFAULT_MARKUP_CD, BUYOUT_IND, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('01', SYS_GUID(), '1', 'UCD - CENTRAL STOREHOUSE',  '1234', 'N', '01', 'N', 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_T ( WAREHOUSE_CD, OBJ_ID, VER_NBR, WAREHOUSE_NME, ADDRESS_CD, CONSOLIDATION_CD, DEFAULT_MARKUP_CD, BUYOUT_IND, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('04', SYS_GUID(), '1', 'UCD - SUPPLY EXPRESS',  '1234', 'N', '01', 'N', 'Y', CURRENT_DATE )
;





