INSERT INTO MM_WAREHOUSE_ACCOUNT_TYPE_T ( WAREHOUSE_ACCOUNT_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('CG', SYS_GUID(), '1', 'COST OF GOODS SOLD ACCOUNT', 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNT_TYPE_T ( WAREHOUSE_ACCOUNT_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('IC', SYS_GUID(), '1', 'INCOME ACCOUNT', 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNT_TYPE_T ( WAREHOUSE_ACCOUNT_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('TX', SYS_GUID(), '1', 'SALES TAX CLEARING ACCOUNT', 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNT_TYPE_T ( WAREHOUSE_ACCOUNT_TYPE_CD, OBJ_ID, VER_NBR, NM, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('WR', SYS_GUID(), '1', 'WAREHOUSE RESALE ACCOUNT', 'Y', CURRENT_DATE )
;
