INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', '01', 'CG', '3', 'CSL1120', '00000', '8065', '000', '0054', '000', NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', '01', 'CO', '3', 'CSL1120', '00000', '8103', '000', '0054', '000', NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', '01', 'CS', '3', 'CSL1120', '00000', '8102', '000', '0054', '000', NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', '04', 'CG', '3', 'CSL2120', '00000', '8065', '000', '0054', '000', NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', '04', 'CO', '3', 'CSL2120', '00000', '8103', '000', '0054', '000', NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', '04', 'CS', '3', 'CSL2120', '00000', '8102', '000', '0054', '000', NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', '01', 'WR', '3', 'CSL1241', '00000', '8065', '000', '0054', '000', NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', '01', 'WO', '3', 'CSL1241', '00000', '8103', '000', '0054', '000', NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', '01', 'WS', '3', 'CSL1241', '00000', '8102', '000', '0054', '000', NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', '04', 'WR', '3', 'CSL2241', '00000', '8065', '000', '0054', '000', NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', '04', 'WO', '3', 'CSL2241', '00000', '8103', '000', '0054', '000', NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', '04', 'WS', '3', 'CSL2241', '00000', '8102', '000', '0054', '000', NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', '01', 'TX', '3', 'MMTAXLB', '00000', '0510', '000', '0054', '000', NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', '01', 'IC', '3', 'MMCS00', '00000', '3900', '000', '0054', '000', NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_ACCOUNTS_T ( WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_ACCOUNTS_S.nextval, SYS_GUID(), '1', '01', 'RI', '3', 'MMCS00', '00000', '3900', '000', '0054', '000', NULL, 'Y', CURRENT_DATE )
;
insert into mm_warehouse_accounts_t (WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT)
values (MM_WAREHOUSE_ACCOUNTS_S.nextval, sys_guid(), 1, '63', 'CG', 'BA', '6044900', null, '5330', null, '8000', null, null, 'Y', current_timestamp);
insert into mm_warehouse_accounts_t (WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT)
values (MM_WAREHOUSE_ACCOUNTS_S.nextval, sys_guid(), 1, '63', 'CO', 'BA', '6044900', null, '5177', null, '8000', null, null, 'Y', current_timestamp);
insert into mm_warehouse_accounts_t (WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT)
values (MM_WAREHOUSE_ACCOUNTS_S.nextval, sys_guid(), 1, '63', 'CS', 'BA', '6044900', null, '5140', null, '8000', null, null, 'Y', current_timestamp);
insert into mm_warehouse_accounts_t (WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT)
values (MM_WAREHOUSE_ACCOUNTS_S.nextval, sys_guid(), 1, '63', 'WR', 'BA', '6044901', null, '5330', null, '8000', null, null, 'Y', current_timestamp);
insert into mm_warehouse_accounts_t (WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT)
values (MM_WAREHOUSE_ACCOUNTS_S.nextval, sys_guid(), 1, '63', 'WO', 'BA', '6044901', null, '5177', null, '8000', null, null, 'Y', current_timestamp);
insert into mm_warehouse_accounts_t (WAREHOUSE_ACCOUNT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_ACCOUNT_TYPE_CD, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, PROJECT_CD, ACTV_IND, LAST_UPDATE_DT)
values (MM_WAREHOUSE_ACCOUNTS_S.nextval, sys_guid(), 1, '63', 'WS', 'BA', '6044901', null, '5140', null, '8000', null, null, 'Y', current_timestamp);
