INSERT INTO MM_WAREHOUSE_T ( WAREHOUSE_CD, OBJ_ID, VER_NBR, WAREHOUSE_NME, ADDRESS_CD, CONSOLIDATION_CD, DEFAULT_MARKUP_CD, DEFAULT_FIN_COA_CD, DEFAULT_ORG_CD, BUYOUT_IND, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('74', SYS_GUID(), '1', 'MAIN WAREHOUSE',  '1', 'N', 'W01', 'MS', '10074000', 'N', 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_T ( WAREHOUSE_CD, OBJ_ID, VER_NBR, WAREHOUSE_NME, ADDRESS_CD, CONSOLIDATION_CD, DEFAULT_MARKUP_CD, DEFAULT_FIN_COA_CD, DEFAULT_ORG_CD, BUYOUT_IND, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('SI', SYS_GUID(), '1', 'SPECIALTY', '1', 'N', 'W01', 'MS', '10074000', 'N', 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_T ( WAREHOUSE_CD, OBJ_ID, VER_NBR, WAREHOUSE_NME, ADDRESS_CD, CONSOLIDATION_CD, DEFAULT_MARKUP_CD, DEFAULT_FIN_COA_CD, DEFAULT_ORG_CD, BUYOUT_IND, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('NS', SYS_GUID(), '1', 'NON-STOCK', '1', 'N', 'W01', 'MS', '10074000', 'N', 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_T ( WAREHOUSE_CD, OBJ_ID, VER_NBR, WAREHOUSE_NME, ADDRESS_CD, CONSOLIDATION_CD, DEFAULT_MARKUP_CD, DEFAULT_FIN_COA_CD, DEFAULT_ORG_CD, BUYOUT_IND, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('SH', SYS_GUID(), '1', 'SHOP',  '1', 'N', 'W01', 'MS', '10074000', 'N', 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_T ( WAREHOUSE_CD, OBJ_ID, VER_NBR, WAREHOUSE_NME, ADDRESS_CD, CONSOLIDATION_CD, DEFAULT_MARKUP_CD, DEFAULT_FIN_COA_CD, DEFAULT_ORG_CD, BUYOUT_IND, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('NC', SYS_GUID(), '1', 'NCRS',  '1', 'N', 'W01', 'MS', '10074000', 'N', 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_T ( WAREHOUSE_CD, OBJ_ID, VER_NBR, WAREHOUSE_NME, ADDRESS_CD, CONSOLIDATION_CD, DEFAULT_MARKUP_CD, DEFAULT_FIN_COA_CD, DEFAULT_ORG_CD, BUYOUT_IND, ACTV_IND, LAST_UPDATE_DT )
VALUES 
('MG', SYS_GUID(), '1', 'MISC',  '1', 'N', 'W01', 'MS', '10074000', 'N', 'Y', CURRENT_DATE )
;
