INSERT INTO MM_WAREHOUSE_OBJECT_T ( WAREHOUSE_OBJECT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_OBJECT_TYPE_CD, FIN_COA_CD, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_OBJECT_S.nextval, SYS_GUID(), '1', '74', 'OBSO', 'MS', '6564', NULL, '4050', NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_OBJECT_T ( WAREHOUSE_OBJECT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_OBJECT_TYPE_CD, FIN_COA_CD, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_OBJECT_S.nextval, SYS_GUID(), '1', '74', 'SHRO', 'MS', '6564', NULL, '4050', NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_OBJECT_T ( WAREHOUSE_OBJECT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_OBJECT_TYPE_CD, FIN_COA_CD, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_OBJECT_S.nextval, SYS_GUID(), '1', 'SI', 'OBSO', 'MS', '6564', NULL, '4050', NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_OBJECT_T ( WAREHOUSE_OBJECT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_OBJECT_TYPE_CD, FIN_COA_CD, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_OBJECT_S.nextval, SYS_GUID(), '1', 'SI', 'SHRO', 'MS', '6564', NULL, '4050', NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_OBJECT_T ( WAREHOUSE_OBJECT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_OBJECT_TYPE_CD, FIN_COA_CD, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_OBJECT_S.nextval, SYS_GUID(), '1', 'NS', 'OBSO', 'MS', '6564', NULL, '4050', NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_OBJECT_T ( WAREHOUSE_OBJECT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_OBJECT_TYPE_CD, FIN_COA_CD, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_OBJECT_S.nextval, SYS_GUID(), '1', 'NS', 'SHRO', 'MS', '6564', NULL, '4050', NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_OBJECT_T ( WAREHOUSE_OBJECT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_OBJECT_TYPE_CD, FIN_COA_CD, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_OBJECT_S.nextval, SYS_GUID(), '1', 'SH', 'OBSO', 'MS', '6564', NULL, '4050', NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_OBJECT_T ( WAREHOUSE_OBJECT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_OBJECT_TYPE_CD, FIN_COA_CD, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_OBJECT_S.nextval, SYS_GUID(), '1', 'SH', 'SHRO', 'MS', '6564', NULL, '4050', NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_OBJECT_T ( WAREHOUSE_OBJECT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_OBJECT_TYPE_CD, FIN_COA_CD, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_OBJECT_S.nextval, SYS_GUID(), '1', 'NC', 'OBSO', 'MS', '6564', NULL, '4050', NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_OBJECT_T ( WAREHOUSE_OBJECT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_OBJECT_TYPE_CD, FIN_COA_CD, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_OBJECT_S.nextval, SYS_GUID(), '1', 'NC', 'SHRO', 'MS', '6564', NULL, '4050', NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_OBJECT_T ( WAREHOUSE_OBJECT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_OBJECT_TYPE_CD, FIN_COA_CD, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_OBJECT_S.nextval, SYS_GUID(), '1', 'MG', 'OBSO', 'MS', '6564', NULL, '4050', NULL, 'Y', CURRENT_DATE )
;
INSERT INTO MM_WAREHOUSE_OBJECT_T ( WAREHOUSE_OBJECT_ID, OBJ_ID, VER_NBR, WAREHOUSE_CD, WAREHOUSE_OBJECT_TYPE_CD, FIN_COA_CD, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, OFFSET_OBJECT_CD, OFFSET_SUB_OBJ_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_WAREHOUSE_OBJECT_S.nextval, SYS_GUID(), '1', 'MG', 'SHRO', 'MS', '6564', NULL, '4050', NULL, 'Y', CURRENT_DATE )
;
