INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '01', 'ZONE 01', 'AA', 'Y', CURRENT_DATE )
; 
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '02', 'ZONE 02', 'AA', 'Y', CURRENT_DATE )
; 
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '03', 'ZONE 03', 'AA', 'Y', CURRENT_DATE )
; 
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '04', 'ZONE 04', 'AA', 'Y', CURRENT_DATE )
; 
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '05', 'ZONE 05', 'AA', 'Y', CURRENT_DATE )
; 
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '06', 'ZONE 06', 'AA', 'Y', CURRENT_DATE )
; 
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '07', 'ZONE 07', 'AA', 'Y', CURRENT_DATE )
; 
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '08', 'ZONE 08', 'AA', 'Y', CURRENT_DATE )
; 
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '09', 'ZONE 09', 'AA', 'Y', CURRENT_DATE )
; 
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '10', 'ZONE 10', 'AA', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '11', 'ZONE 11', 'AA', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '12', 'ZONE 12', 'AA', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '13', 'ZONE 13', 'AA', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '14', 'ZONE 14', 'AA', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '15', 'ZONE 15', 'AA', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '16', 'ZONE 16', 'AA', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '17', 'ZONE 17', 'AA', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '18', 'ZONE 18', 'AA', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '19', 'ZONE 19', 'AA', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '20', 'ZONE 20', 'AA', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '21', 'ZONE 21', 'AA', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '22', 'ZONE 22', 'AA', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '23', 'ZONE 23', 'AA', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '24', 'ZONE 24', 'AA', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '25', 'ZONE 25', 'AA', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '26', 'ZONE 26', 'AA', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '27', 'ZONE 27', 'AA', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '28', 'ZONE 28', 'AA', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '29', 'ZONE 29', 'AA', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '30', 'ZONE 30', 'AA', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '01', 'ZONE 01', 'AB', 'Y', CURRENT_DATE )
; 
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '02', 'ZONE 02', 'AB', 'Y', CURRENT_DATE )
; 
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '03', 'ZONE 03', 'AB', 'Y', CURRENT_DATE )
; 
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '04', 'ZONE 04', 'AB', 'Y', CURRENT_DATE )
; 
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '05', 'ZONE 05', 'AB', 'Y', CURRENT_DATE )
; 
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '06', 'ZONE 06', 'AB', 'Y', CURRENT_DATE )
; 
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '07', 'ZONE 07', 'AB', 'Y', CURRENT_DATE )
; 
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES 
(MM_ZONE_S.nextval, SYS_GUID(), '1', '08', 'ZONE 08', 'AB', 'Y', CURRENT_DATE )
; 
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '01',
          'ZONE LOCATION  01',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '02',
          'ZONE LOCATION  02',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '03',
          'ZONE LOCATION  03',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '04',
          'ZONE LOCATION  04',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '05',
          'ZONE LOCATION  05',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '06',
          'ZONE LOCATION  06',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '07',
          'ZONE LOCATION  07',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '08',
          'ZONE LOCATION  08',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '09',
          'ZONE LOCATION  09',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '10',
          'ZONE LOCATION  10',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '11',
          'ZONE LOCATION  11',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '12',
          'ZONE LOCATION  12',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '13',
          'ZONE LOCATION  13',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '14',
          'ZONE LOCATION  14',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '15',
          'ZONE LOCATION  15',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '16',
          'ZONE LOCATION  16',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '17',
          'ZONE LOCATION  17',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '18',
          'ZONE LOCATION  18',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '19',
          'ZONE LOCATION  19',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '20',
          'ZONE LOCATION  20',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '21',
          'ZONE LOCATION  21',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '22',
          'ZONE LOCATION  22',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '23',
          'ZONE LOCATION  23',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '24',
          'ZONE LOCATION  24',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '25',
          'ZONE LOCATION  25',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '26',
          'ZONE LOCATION  26',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '27',
          'ZONE LOCATION  27',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '28',
          'ZONE LOCATION  28',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '29',
          'ZONE LOCATION  29',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '30',
          'ZONE LOCATION  30',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '31',
          'ZONE LOCATION  31',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '32',
          'ZONE LOCATION  32',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '33',
          'ZONE LOCATION  33',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '37',
          'ZONE LOCATION  37',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '40',
          'ZONE LOCATION  40',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '42',
          'ZONE LOCATION  42',
          'SI', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '43',
          'ZONE LOCATION  43',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '44',
          'ZONE LOCATION  44',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '45',
          'ZONE LOCATION  45',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '46',
          'ZONE LOCATION  46',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '46',
          'ZONE LOCATION  46',
          'SI', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '47',
          'ZONE LOCATION  47',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '48',
          'ZONE LOCATION  48',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '49',
          'ZONE LOCATION  49',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '65',
          'ZONE LOCATION  65',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', 'CA',
          'ZONE LOCATION  CA',
          '63', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', 'CA',
          'ZONE LOCATION  CA',
          'NS', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', 'CR',
          'ZONE LOCATION  CR',
          'NS', 'Y', CURRENT_DATE )
;
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', 'SH',
          'ZONE LOCATION  SH',
          '63', 'Y', CURRENT_DATE )
;
