INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '01', 'Zone 01 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '02', 'Zone 02 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '03', 'Zone 03 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '04', 'Zone 04 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '05', 'Zone 05 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '06', 'Zone 06 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '07', 'Zone 07 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '08', 'Zone 08 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '09', 'Zone 09 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '10', 'Zone 10 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '11', 'Zone 11 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '11', 'Zone 11 for SI', 'SI', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '12', 'Zone 12 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '13', 'Zone 13 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '14', 'Zone 14 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '15', 'Zone 15 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '16', 'Zone 16 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '17', 'Zone 17 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '18', 'Zone 18 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '19', 'Zone 19 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '20', 'Zone 20 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '21', 'Zone 21 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '22', 'Zone 22 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '23', 'Zone 23 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '24', 'Zone 24 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '25', 'Zone 25 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '26', 'Zone 26 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '27', 'Zone 27 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '28', 'Zone 28 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '29', 'Zone 29 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '30', 'Zone 30 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '31', 'Zone 31 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '32', 'Zone 32 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '33', 'Zone 33 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '34', 'Zone 34 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '35', 'Zone 35 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '37', 'Zone 37 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '40', 'Zone 40 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '42', 'Zone 42 for SI', 'SI', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '43', 'Zone 43 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '44', 'Zone 44 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '45', 'Zone 45 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '46', 'Zone 46 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '46', 'Zone 46 for SI', 'SI', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '47', 'Zone 47 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '48', 'Zone 48 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '49', 'Zone 49 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', '65', 'Zone 65 for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', 'CA', 'Zone CA for 74', '74', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', 'CA', 'Zone CA for NS', 'NS', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', 'CA', 'Zone CA for SI', 'SI', 'Y', CURRENT_DATE);
INSERT INTO MM_ZONE_T ( ZONE_ID, OBJ_ID, VER_NBR, ZONE_CD, ZONE_DESC, WAREHOUSE_CD, ACTV_IND, LAST_UPDATE_DT )
   VALUES (MM_ZONE_S.nextval, SYS_GUID(), '1', 'CR', 'Zone CR for NS', 'NS', 'Y', CURRENT_DATE);
