CREATE INDEX MM_CATALOG_ITEM_PENDING_IDX1 ON MM_CATALOG_ITEM_PENDING_T(UNSPSC_CD);
CREATE INDEX MM_CATALOG_ITEM_PENDING_IDX2 ON MM_CATALOG_ITEM_PENDING_T(DISTRIBUTOR_NBR);
CREATE INDEX MM_CATALOG_IMAGE_IDX1 ON MM_CATALOG_IMAGE_T(CATALOG_IMAGE_NM);
CREATE INDEX MM_UNSPSC_IDX1 ON MM_UNSPSC_T(CODE);
CREATE INDEX MM_CATALOG_ITEM_IDX1 ON MM_CATALOG_ITEM_T(DISTRIBUTOR_NBR);

CREATE INDEX MM_CATALOG_SEARCH_IDX1 ON MM_CATALOG_ITEM_SEARCH_T(catalog_desc) INDEXTYPE IS CTXSYS.CTXCAT;  
CREATE INDEX MM_CATALOG_SEARCH_IDX2 ON MM_CATALOG_ITEM_SEARCH_T (Distributor_Nbr);