insert into KRNS_CMP_TYP_T (CAMPUS_TYP_CD, CMP_TYP_NM, DOBJ_MAINT_CD_ACTV_IND, OBJ_ID, VER_NBR, ACTV_IND)
values ('B', 'BOTH', 'Y', SYS_GUID(), 1 'Y');

insert into KRNS_CMP_TYP_T (CAMPUS_TYP_CD, CMP_TYP_NM, DOBJ_MAINT_CD_ACTV_IND, OBJ_ID, VER_NBR, ACTV_IND)
values ('F', 'FISCAL', 'Y', SYS_GUID(), 1 'Y');

insert into KRNS_CMP_TYP_T (CAMPUS_TYP_CD, CMP_TYP_NM, DOBJ_MAINT_CD_ACTV_IND, OBJ_ID, VER_NBR, ACTV_IND)
values ('P', 'PHYSICAL', 'Y', SYS_GUID(), 1 'Y');

