insert into KRNS_NTE_TYP_T (NTE_TYP_CD, OBJ_ID, VER_NBR, TYP_DESC_TXT, ACTV_IND)
values ('BO', SYS_GUID(), 1 'DOCUMENT BUSINESS OBJECT', 'Y');

insert into KRNS_NTE_TYP_T (NTE_TYP_CD, OBJ_ID, VER_NBR, TYP_DESC_TXT, ACTV_IND)
values ('DH', SYS_GUID(), 1 'DOCUMENT HEADER', 'Y');

